In [1]:
import pandas as pd
from pathlib import Path
import os
from camara_deputados.ingestion.data_loader import DataLoader

In [2]:
#instâncias

bronze = DataLoader('bronze')

📍 Caminho resolvido: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/bronze

In [3]:
dfs_bronze = bronze.carregar_parquets()

📂 Lendo dados da camada bronze: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/bronze

✅ deputado_detalhamento: 1000 linhas, 34 colunas
✅ deputado_frentes: 271053 linhas, 6 colunas
✅ deputado_lista: 1000 linhas, 10 colunas
✅ frentes: 100 linhas, 5 colunas
✅ frentes_detalhamento: 100 linhas, 22 colunas
✅ partidos: 15 linhas, 5 colunas
✅ partidos_detalhamento: 15 linhas, 23 colunas
✅ proposicoes: 135 linhas, 10 colunas
✅ proposicoes_autores: 343 linhas, 8 colunas
✅ proposicoes_detalhamento: 135 linhas, 36 colunas
✅ proposicoes_temas: 141 linhas, 5 colunas
✅ proposicoes_votacoes: 819 linhas, 13 colunas
✅ tipos_Autor: 58 linhas, 5 colunas
✅ tipos_proposicao: 544 linhas, 5 colunas
✅ votacoes_detalhamento: 819 linhas, 21 colunas
✅ votacoes_orientacao: 1883 linhas, 7 colunas
✅ votos_deputados: 41678 linhas, 13 colunas

🎯 Carregamento finalizado.

In [5]:
def analisar_dfs(dfs):
    resultado = []

    for nome_tabela, df in dfs.items():
        for coluna in df.columns:
            
            total = len(df)
            nulos = df[coluna].isnull().sum()
            
            resultado.append({
                "tabela": nome_tabela,
                "coluna": coluna,
                "tipo": df[coluna].dtype,
                "nulos": nulos,
                "%_nulos": nulos / total,
                "unicos": df[coluna].astype(str).nunique(),
                "total_linhas": total
            })

    return pd.DataFrame(resultado)

In [6]:
df_analise = analisar_dfs(dfs_bronze)

In [ ]:
df_analise[df_analise["tabela"] == "deputados_detalhamento"]

Empty DataFrame
Columns: [tabela, coluna, tipo, nulos, %_nulos, unicos, total_linhas]
Index: []

In [ ]:
df_analise[df_analise['tabela'] == 'deputados_lista']

Empty DataFrame
Columns: [tabela, coluna, tipo, nulos, %_nulos, unicos, total_linhas]
Index: []

In [ ]:
df_analise[df_analise['tabela']=='frentes']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
50,frentes,id,int64,0,0.0,100,100
51,frentes,uri,str,0,0.0,100,100
52,frentes,titulo,str,0,0.0,100,100
53,frentes,idLegislatura,int64,0,0.0,1,100
54,frentes,data_extracao,datetime64[us],0,0.0,1,100

In [ ]:
df_analise[df_analise['tabela']=='partidos']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
77,partidos,id,int64,0,0.0,15,15
78,partidos,sigla,str,0,0.0,15,15
79,partidos,nome,str,0,0.0,14,15
80,partidos,uri,str,0,0.0,15,15
81,partidos,data_extracao,datetime64[us],0,0.0,1,15

In [7]:
df_analise[df_analise['tabela'].isin(['proposicoes','proposicoes_detalhamento'])]

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
105,proposicoes,id,int64,0,0.000000,135,135
106,proposicoes,uri,str,0,0.000000,135,135
107,proposicoes,siglaTipo,str,0,0.000000,12,135
108,proposicoes,codTipo,int64,0,0.000000,21,135
109,proposicoes,numero,int64,0,0.000000,93,135
110,proposicoes,ano,int64,0,0.000000,9,135
111,proposicoes,ementa,str,0,0.000000,133,135
112,proposicoes,dataApresentacao,str,0,0.000000,118,135
113,proposicoes,ano_ref,int64,0,0.000000,9,135
114,proposicoes,data_extracao,datetime64[us],0,0.000000,1,135
123,proposicoes_detalhamento,id,int64,0,0.000000,135,135
124,proposicoes_detalhamento,uri,str,0,0.000000,135,135
125,proposicoes_detalhamento,siglaTipo,str,0,0.000000,12,135
126,proposicoes_detalhamento,codTipo,int64,0,0.000000,21,135
127,proposicoes_detalhamento,numero,int64,0,0.000000,93,135
128,proposicoes_detalhamento,ano,int64,0,0.000000,9,135
129,proposicoes_detalhamento,ementa,str,0,0.000000,133,135
130,proposicoes_detalhamento,dataApresentacao,str,0,0.000000,118,135
131,proposicoes_detalhamento,uriOrgaoNumerador,str,45,0.333333,23,135
132,proposicoes_detalhamento,uriAutores,str,0,0.000000,135,135
133,proposicoes_detalhamento,descricaoTipo,str,0,0.000000,21,135
134,proposicoes_detalhamento,ementaDetalhada,str,30,0.222222,17,135
135,proposicoes_detalhamento,keywords,str,30,0.222222,70,135
136,proposicoes_detalhamento,uriPropPrincipal,object,135,1.000000,0,135
137,proposicoes_detalhamento,uriPropAnterior,object,135,1.000000,0,135
138,proposicoes_detalhamento,uriPropPosterior,str,113,0.837037,22,135
139,proposicoes_detalhamento,urlInteiroTeor,str,4,0.029630,131,135
140,proposicoes_detalhamento,urnFinal,object,135,1.000000,0,135
141,proposicoes_detalhamento,texto,object,135,1.000000,0,135
142,proposicoes_detalhamento,justificativa,object,135,1.000000,0,135
143,proposicoes_detalhamento,statusProposicao.dataHora,str,2,0.014815,107,135
144,proposicoes_detalhamento,statusProposicao.sequencia,float64,2,0.014815,72,135
145,proposicoes_detalhamento,statusProposicao.siglaOrgao,str,2,0.014815,20,135
146,proposicoes_detalhamento,statusProposicao.uriOrgao,str,0,0.000000,21,135
147,proposicoes_detalhamento,statusProposicao.uriUltimoRelator,str,50,0.370370,70,135
148,proposicoes_detalhamento,statusProposicao.regime,str,0,0.000000,7,135
149,proposicoes_detalhamento,statusProposicao.descricaoTramitacao,str,2,0.014815,23,135
150,proposicoes_detalhamento,statusProposicao.codTipoTramitacao,str,2,0.014815,23,135
151,proposicoes_detalhamento,statusProposicao.descricaoSituacao,str,34,0.251852,19,135
152,proposicoes_detalhamento,statusProposicao.codSituacao,float64,34,0.251852,19,135
153,proposicoes_detalhamento,statusProposicao.despacho,str,0,0.000000,123,135
154,proposicoes_detalhamento,statusProposicao.url,str,100,0.740741,35,135
155,proposicoes_detalhamento,statusProposicao.ambito,str,0,0.000000,1,135
156,proposicoes_detalhamento,statusProposicao.apreciacao,str,0,0.000000,5,135
157,proposicoes_detalhamento,source_id,int64,0,0.000000,135,135
158,proposicoes_detalhamento,data_extracao,datetime64[us],0,0.000000,1,135

In [9]:
df_proposicoes_detalhamento = bronze.carregar_tabela('partidos_detalhamento')

✅ partidos_detalhamento: 15 linhas, 23 colunas

In [11]:
df_proposicoes_autores = dfs_bronze['proposicoes_autores']

In [12]:
df_proposicoes_autores.info()

<class 'pandas.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   uri              343 non-null    str
 1   nome             343 non-null    str
 2   codTipo          343 non-null    int64
 3   tipo             343 non-null    str
 4   ordemAssinatura  343 non-null    int64
 5   proponente       343 non-null    int64
 6   source_id        343 non-null    int64
 7   data_extracao    343 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 50.2 KB

In [15]:
df_proposicoes_autores.sample(10)

,uri,nome,codTipo,tipo,ordemAssinatura,proponente,source_id,data_extracao
159,https://dadosabertos.camara.leg.br/api/v2/depu...,Fernando Rodolfo,10000,Deputado(a),115,1,2268427,2026-05-01 14:19:06.088189
322,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,Órgão do Poder Executivo,1,1,2481884,2026-05-01 14:19:06.088189
232,https://dadosabertos.camara.leg.br/api/v2/depu...,Pedro Westphalen,10000,Deputado(a),151,1,2268427,2026-05-01 14:19:06.088189
228,https://dadosabertos.camara.leg.br/api/v2/depu...,Pastor Eurico,10000,Deputado(a),123,1,2268427,2026-05-01 14:19:06.088189
312,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,Órgão do Poder Executivo,1,1,2416825,2026-05-01 14:19:06.088189
240,https://dadosabertos.camara.leg.br/api/v2/depu...,Ricardo Barros,10000,Deputado(a),128,1,2268427,2026-05-01 14:19:06.088189
85,https://dadosabertos.camara.leg.br/api/v2/depu...,Walter Pinheiro,10000,Deputado(a),2,1,257161,2026-05-01 14:19:06.088189
4,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,Órgão do Poder Executivo,1,1,2167562,2026-05-01 14:19:06.088189
299,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,Órgão do Poder Executivo,1,1,2345501,2026-05-01 14:19:06.088189
60,https://dadosabertos.camara.leg.br/api/v2/depu...,Carmen Zanotto,10000,Deputado(a),1,1,2181447,2026-05-01 14:19:06.088189

In [17]:
df_proposicoes_autores['uri'].iloc[8]

'https://dadosabertos.camara.leg.br/api/v2/deputados/73584'

In [ ]:
df_proposicoes_detalhamento[['codTipo','siglaTipo','descricaoTipo']].drop_duplicates()

    codTipo siglaTipo                                     descricaoTipo
0       139        PL                                    Projeto de Lei
7       134       MSC                                          Mensagem
8       610       DOC                                         Documento
9       291       MPV                                 Medida Provisória
20      720      PROC                                  Processo Interno
21     1033       DOC                      Ofício do Congresso Nacional
22      412       MSC             Mensagem de Restituição de Autógrafos
32      425       TVR               Permissão Rádio Frequência Modulada
33      401       MSC  Mensagem de Concessão ou Renovação de Rádio e TV
35      181        OF                                            Ofício
36      436       TVR                            Renovação TV Educativa
40      427       TVR                       Renovação Rádio Comunitária
58     1028       DOC                          Ofício do Senado Federal

In [ ]:
df_proposicoes_detalhamento['ementa'].iloc[2]

'Altera o art. 121 do Decreto-Lei nº 2.848, de 7 de dezembro de 1940- Código Penal -  para prever como homicídio qualificado aquele praticado contra membros do Ministério Público e Magistratura, no exercício de sua função ou por causa dela e dá outras providências.\r\n\r\nNOVA EMENTA: Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), e as Leis nºs 8.072, de 25 de julho de 1990 (Lei dos Crimes Hediondos), 12.694, de 24 julho de 2012, e 13.709, de 14 agosto de 2018 (Lei Geral de Proteção de Dados Pessoais), para reconhecer como atividade de risco permanente as atribuições inerentes ao Poder Judiciário e ao Ministério Público e garantir aos seus membros medidas de proteção, bem como recrudescer o tratamento penal destinado aos crimes de homicídio e de lesão corporal dolosa contra eles, desde que no exercício da função ou em decorrência dela, ou contra seu cônjuge, companheiro ou parente, inclusive por afinidade, até o terceiro grau, em razão dessa condição.'

In [ ]:
df_proposicoes_detalhamento[
    df_proposicoes_detalhamento['keywords'].isnull()
][['ementa','keywords']]

                                               ementa keywords
8   ATA DA 30ª REUNIÃO EXTRAORDINÁRIA\nREALIZADA E...      NaN
14  Submete à apreciação do Congresso Nacional o t...      NaN
20  Propõe que a Comissão de Defesa do Consumidor ...      NaN
21  Comunica calendário de tramitação da MPV 1200/...      NaN
32  Submete à apreciação do Congresso Nacional o a...      NaN
33  Submete à apreciação do Congresso Nacional o a...      NaN
35  Ofício de Dispensa de Redação Final do PL 6399...      NaN
36  Submete à apreciação do Congresso Nacional o a...      NaN
37  Submete à apreciação do Congresso Nacional o a...      NaN
38  Submete à apreciação do Congresso Nacional o a...      NaN
39  Submete à apreciação do Congresso Nacional o a...      NaN
40  Submete à apreciação do Congresso Nacional o a...      NaN
41  Submete à apreciação do Congresso Nacional o a...      NaN
42  Submete à apreciação do Congresso Nacional o a...      NaN
43  Submete à apreciação do Congresso Nacional o a...      NaN
44  Submete à apreciação do Congresso Nacional o a...      NaN
46  Nos termos do art. 9 do Regimento Interno da C...      NaN
48  REPRESENTAÇÃO POR QUEBRA DE DECORO E ABUSO DE ...      NaN
58  Ofício SF 1447/2025 que comunica restituição d...      NaN
59  Ofício SF 1448/2025 que comunica restituição d...      NaN

In [ ]:
df_proposicoes_detalhamento[['ementa','keywords']]

In [ ]:
df_analise[df_analise['tabela'] == 'tipos_proposicao']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
177,tipos_proposicao,cod,str,0,0.000000,544,544
178,tipos_proposicao,sigla,str,0,0.000000,182,544
179,tipos_proposicao,nome,str,0,0.000000,521,544
180,tipos_proposicao,descricao,str,3,0.005515,173,544
181,tipos_proposicao,data_extracao,datetime64[us],0,0.000000,1,544

In [ ]:
df_tiposProposicao = dfs_bronze['tipos_proposicao']

In [ ]:
display(df_tiposProposicao)

,cod,sigla,nome,descricao,data_extracao
0,27,OF,Ofício do Congresso Nacional,,2026-04-21 08:56:09.295878
1,129,CON,Consulta,Consulta,2026-04-21 08:56:09.295878
2,130,EMC,Emenda na Comissão,Emenda Apresentada na Comissão,2026-04-21 08:56:09.295878
3,131,EMP,Emenda de Plenário,Emenda de Plenário,2026-04-21 08:56:09.295878
4,132,EMS,Emenda/Substitutivo do Senado,Emenda/Substitutivo do Senado,2026-04-21 08:56:09.295878
...,...,...,...,...,...
539,1098,DOC,Ofício de Órgão da Câmara dos Deputados,,2026-04-21 08:56:09.295878
540,1099,ATA_PRE,Ata Preparatória,,2026-04-21 08:56:09.295878
541,1100,SAP,Sustação de Andamento de Ação Penal,,2026-04-21 08:56:09.295878
542,1101,REC,Recurso contra parecer terminativo do Conselho...,"Art. 14, § 4º, inciso III, do CEDP",2026-04-21 08:56:09.295878
543,1102,OFM,Ofício à Mesa,,2026-04-21 08:56:09.295878

In [ ]:
df_proposicoesTemas = dfs_bronze['proposicoes_temas']

In [ ]:
df_proposicoesTemas.sample(5)

,codTema,tema,relevancia,source_id,data_extracao
18,70,Finanças Públicas e Orçamento,0,2345498,2026-04-19 18:24:25.731797
61,41,Cidades e Desenvolvimento Urbano,0,2599898,2026-04-19 18:24:25.731797
40,70,Finanças Públicas e Orçamento,0,2599885,2026-04-19 18:24:25.731797
53,70,Finanças Públicas e Orçamento,0,2599894,2026-04-19 18:24:25.731797
52,40,Economia,0,2599894,2026-04-19 18:24:25.731797

In [ ]:
#confirmando se há apenas um cod por tema


df_proposicoesTemas.groupby('codTema')['tema'].nunique()

codTema
34    1
37    1
40    1
41    1
42    1
43    1
44    1
46    1
48    1
52    1
54    1
55    1
56    1
57    1
58    1
62    1
64    1
66    1
70    1
72    1
76    1
Name: tema, dtype: int64

In [ ]:
df_analise[df_analise['tabela'] == 'votacoes_detalhamento']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
182,votacoes_detalhamento,id,str,0,0.000000,271,271
183,votacoes_detalhamento,uri,str,0,0.000000,271,271
184,votacoes_detalhamento,data,str,0,0.000000,67,271
185,votacoes_detalhamento,dataHoraRegistro,str,0,0.000000,255,271
186,votacoes_detalhamento,siglaOrgao,str,0,0.000000,14,271
187,votacoes_detalhamento,uriOrgao,str,0,0.000000,16,271
188,votacoes_detalhamento,idOrgao,int64,0,0.000000,16,271
189,votacoes_detalhamento,uriEvento,str,65,0.239852,64,271
190,votacoes_detalhamento,idEvento,float64,65,0.239852,64,271
191,votacoes_detalhamento,descricao,str,0,0.000000,133,271
192,votacoes_detalhamento,aprovacao,float64,7,0.025830,2,271
193,votacoes_detalhamento,descUltimaAberturaVotacao,str,213,0.785978,31,271
194,votacoes_detalhamento,dataHoraUltimaAberturaVotacao,str,213,0.785978,56,271
195,votacoes_detalhamento,efeitosRegistrados,object,0,0.000000,72,271
196,votacoes_detalhamento,objetosPossiveis,object,0,0.000000,167,271
197,votacoes_detalhamento,proposicoesAfetadas,object,0,0.000000,26,271
198,votacoes_detalhamento,ultimaApresentacaoProposicao.dataHoraRegistro,str,66,0.243542,143,271
199,votacoes_detalhamento,ultimaApresentacaoProposicao.descricao,str,64,0.236162,146,271
200,votacoes_detalhamento,ultimaApresentacaoProposicao.uriProposicaoCitada,str,155,0.571956,59,271
201,votacoes_detalhamento,source_id,str,0,0.000000,271,271
202,votacoes_detalhamento,data_extracao,datetime64[us],0,0.000000,1,271

In [ ]:
df_votacoes_detalhamento = dfs_bronze['votacoes_detalhamento']

display(df_votacoes_detalhamento)

,id,uri,data,dataHoraRegistro,siglaOrgao,uriOrgao,idOrgao,uriEvento,idEvento,descricao,...,descUltimaAberturaVotacao,dataHoraUltimaAberturaVotacao,efeitosRegistrados,objetosPossiveis,proposicoesAfetadas,ultimaApresentacaoProposicao.dataHoraRegistro,ultimaApresentacaoProposicao.descricao,ultimaApresentacaoProposicao.uriProposicaoCitada,source_id,data_extracao
0,369205-154,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-09,2023-08-09T21:59:25,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,69153.0,Aprovada a Redação Final assinada pela Relator...,...,Votação da Redação Final.,2023-08-09T21:59:04,[],"[{'ano': 0, 'codTipo': 889, 'dataApresentacao'...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2023-08-10T13:04:07,Parecer às Emendas de Plenário proferido pela ...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-154,2026-04-19 18:53:12.134593
1,369205-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-09,2023-08-09T21:58:06,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,69153.0,Aprovada a Subemenda Substitutiva Global ao Pr...,...,Votação em turno único.,2023-08-09T21:46:57,[],"[{'ano': 0, 'codTipo': 889, 'dataApresentacao'...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2023-08-10T13:04:07,Parecer às Emendas de Plenário proferido pela ...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-151,2026-04-19 18:53:12.134593
2,369205-129,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:21,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,NaN,NaN,Alteração do Regime de Tramitação desta propos...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2017-07-05T12:16:17,Apresentação do Requerimento de Apensação n. 6...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-129,2026-04-19 18:53:12.134593
3,369205-128,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:21,SECAP(SGM),https://dadosabertos.camara.leg.br/api/v2/orga...,100001,NaN,NaN,Realizar o encaminhamento do PL-2131/2007 à CI...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",NaN,NaN,NaN,369205-128,2026-04-19 18:53:12.134593
4,369205-127,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:17,SECAP(SGM),https://dadosabertos.camara.leg.br/api/v2/orga...,100001,NaN,NaN,Realizar o encaminhamento do PL-2131/2007 à CC...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",NaN,NaN,NaN,369205-127,2026-04-19 18:53:12.134593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2481882-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-26,2025-11-26T15:57:14,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80291.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 436, 'dataApresentac...",2025-11-24T18:42:24,"Parecer do Relator, Dep. Rodrigo da Zaeli (PL-...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481882-23,2026-04-19 18:53:12.134593
267,2481884-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-10-22,2025-10-22T15:38:16,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,79840.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 436, 'dataApresentac...",2025-10-20T15:05:53,"Parecer do Relator, Dep. Julio Cesar Ribeiro (...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481884-23,2026-04-19 18:53:12.134593
268,2481886-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-10-22,2025-10-22T15:38:17,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,79840.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-10-20T15:05:30,"Parecer do Relator, Dep. Rodrigo Estacho (PSD-...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481886-23,2026-04-19 18:53:12.134593
269,2481888-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-06,2025-11-06T12:02:33,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80236.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-10-24T15:42:51,"Parecer do Relator, Dep. André Figueiredo (PDT...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481888-23,2026-04-19 18:53:12.134593
270,2481890-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-26,2025-11-26T15:57:15,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80291.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-11-24T17:27:39,"Parecer do Relator, Dep. Gustavo Gayer (PL-GO)...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481890-23,2026-04-19 18:53:12.134593

In [ ]:
df_votacoes_detalhamento['objetosPossiveis'].iloc[5]

array([{'ano': 2017, 'codTipo': 304, 'dataApresentacao': '2017-07-05T11:34', 'ementa': 'Requer que seja apensado o Projeto de Lei nº 249/2015 ao Projeto de Lei nº 2.131/2007.', 'id': 2143693, 'numero': 6817, 'siglaTipo': 'REQ', 'uri': 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2143693'}],
      dtype=object)

In [ ]:
df_votacoes_detalhamento['source_id'].iloc[5]

'369205-126'

In [ ]:
df_votacoes_detalhamento['proposicoesAfetadas'].iloc[5]

array([{'ano': 2023, 'codTipo': 139, 'dataApresentacao': '2007-09-26T12:37', 'ementa': 'Torna obrigatória a homologação em cartório de todo contrato de empréstimo consignado a ser efetuado por aposentado ou pensionista do INSS.  NOVA EMENTA: Altera as Leis nºs 10.820, de 17 de dezembro de 2003, e 14.509, de 27 de dezembro de 2022, para dispor sobre a concessão de crédito consignado sem autorização do beneficiário, e a Lei nº 10.741, de 1º de outubro de 2003 (Estatuto da Pessoa Idosa), para caracterizar como prática discriminatória a conduta que especifica.', 'id': 369205, 'numero': 4089, 'siglaTipo': 'PL', 'uri': 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/369205'}],
      dtype=object)

In [ ]:
df_votacoes_detalhamento['proposicoesAfetadas'].apply(len).value_counts()

proposicoesAfetadas
1    269
2      2
Name: count, dtype: int64

In [ ]:
df_votacoes_orientacao = dfs_bronze['votacoes_orientacao']

In [ ]:
df_votacoes_orientacao.sample(5)

,orientacaoVoto,codTipoLideranca,siglaPartidoBloco,codPartidoBloco,uriPartidoBloco,source_id,data_extracao
274,Não,B,Governo,NaN,NaN,1548579-122,2026-04-19 18:59:52.938521
154,Não,B,Fdr PT-PCdoB-PV,NaN,NaN,2345493-50,2026-04-19 18:59:52.938521
116,Sim,P,NOVO,37901.0,https://dadosabertos.camara.leg.br/api/v2/part...,2115253-116,2026-04-19 18:59:52.938521
269,Sim,B,Bl MdbPsdRepPode,NaN,NaN,1548579-126,2026-04-19 18:59:52.938521
285,Sim,B,Fdr PSOL-REDE,NaN,NaN,1548579-114,2026-04-19 18:59:52.938521

In [18]:
gold = DataLoader('gold')
silver = DataLoader('silver')

📍 Caminho resolvido: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/gold
📍 Caminho resolvido: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver

In [19]:
dfs_gold = gold.carregar_parquets()

📂 Lendo dados da camada gold: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/gold

✅ bridge_proposicao_autor: 343 linhas, 3 colunas
✅ bridge_proposicao_tema: 141 linhas, 4 colunas
✅ dim_autor: 252 linhas, 5 colunas
✅ dim_deputado: 395 linhas, 8 colunas
✅ dim_mandato: 395 linhas, 7 colunas
✅ dim_partido: 32 linhas, 3 colunas
✅ dim_partido_bloco: 40 linhas, 3 colunas
✅ dim_periodo: 327 linhas, 7 colunas
✅ dim_proposicao: 135 linhas, 9 colunas
✅ dim_tema: 26 linhas, 3 colunas
✅ fato_orientacao: 1883 linhas, 4 colunas
✅ fato_votacao: 819 linhas, 8 colunas
✅ fato_voto_deputado: 41678 linhas, 6 colunas

🎯 Carregamento finalizado.

In [20]:
dfs_silver = silver.carregar_parquets()

📂 Lendo dados da camada silver: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver

✅ dim_s_deputados: 513 linhas, 8 colunas
✅ dim_s_frente: 100 linhas, 4 colunas
✅ dim_s_partido: 15 linhas, 4 colunas
✅ dim_s_proposicao: 60 linhas, 7 colunas
✅ dim_s_tema: 21 linhas, 3 colunas
✅ dim_s_tiposAutor: 58 linhas, 5 colunas
✅ silver_autores: 343 linhas, 10 colunas
✅ silver_deputado: 1000 linhas, 17 colunas
✅ silver_frenteDeputado: 271053 linhas, 5 colunas
✅ silver_orientacao: 1883 linhas, 8 colunas
✅ silver_proposica: 60 linhas, 22 colunas
✅ silver_proposicao: 135 linhas, 22 colunas
✅ silver_temasProposicao: 141 linhas, 6 colunas
✅ silver_tipos_autores: 58 linhas, 3 colunas
✅ silver_votacao_detalhamento: 819 linhas, 24 colunas
✅ silver_votacao_proposicao: 819 linhas, 9 colunas
✅ silver_votos_deputados: 41678 linhas, 5 colunas

🎯 Carregamento finalizado.

In [21]:
df_proposicao = dfs_silver['silver_proposicao']

In [ ]:
df_proposicao.info()

<class 'pandas.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_Proposicao       135 non-null    Int64
 1   nom_TipoProposicao  135 non-null    string
 2   cod_Tipo            135 non-null    Int64
 3   num_NumeroProp      135 non-null    Int64
 4   num_Ano             135 non-null    Int64
 5   nom_Ementa          135 non-null    string
 6   dat_Apresentacao    135 non-null    datetime64[us]
 7   uri_Autor           135 non-null    string
 8   nom_Keywords        105 non-null    string
 9   nom_SiglaOrgao      133 non-null    string
 10  uri_Relator         85 non-null     string
 11  nom_regime          135 non-null    string
 12  nom_TipoTramitacao  133 non-null    string
 13  cod_TipoTramitacao  133 non-null    Int64
 14  cod_TipoSiituacao   101 non-null    string
 15  cod_Situacao        101 non-null    Int64
 16  nom_LinkProposicao  35 non-null     string
 17  nom_TipoAutor       135 non-null    str
 18  id_Autor            135 non-null    Int64
 19  nom_TipoRelator     85 non-null     str
 20  id_Relator          85 non-null     Int64
 21  data_extracao       135 non-null    datetime64[us]
dtypes: Int64(8), datetime64[us](2), str(2), string(10)
memory usage: 109.2 KB

In [25]:
df_temas = dfs_silver['silver_temasProposicao']

In [26]:
df_temas.info()

<class 'pandas.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cod_Tema        141 non-null    Int64
 1   nom_Tema        141 non-null    string
 2   num_Relevancia  141 non-null    Int64
 3   id_proposicao   141 non-null    Int64
 4   dat_Extracao    141 non-null    datetime64[us]
 5   data_extracao   141 non-null    datetime64[us]
dtypes: Int64(3), datetime64[us](2), string(1)
memory usage: 10.5 KB

In [6]:
df_autores = dfs_silver['silver_autores']

In [7]:
df_autores.sample(60)

,uri_Autor,nom_Autor,cod_TipoAutor,nom_TipoAutor,num_OrdemAssinatura,ind_Proponente,id_Proposicao,dat_Extracao,id_Autor,data_extracao
187,https://dadosabertos.camara.leg.br/api/v2/depu...,Joaquim Passarinho,10000,deputados,31,1,2268427,2026-05-01 14:19:06.088189,178910,2026-05-01 14:51:14.844471
77,https://dadosabertos.camara.leg.br/api/v2/depu...,João Grandão,10000,deputados,5,1,257161,2026-05-01 14:19:06.088189,73454,2026-05-01 14:51:14.844471
224,https://dadosabertos.camara.leg.br/api/v2/depu...,Neri Geller,10000,deputados,135,1,2268427,2026-05-01 14:19:06.088189,146307,2026-05-01 14:51:14.844471
72,https://dadosabertos.camara.leg.br/api/v2/depu...,Iara Bernardi,10000,deputados,10,1,257161,2026-05-01 14:19:06.088189,74780,2026-05-01 14:51:14.844471
275,https://dadosabertos.camara.leg.br/api/v2/depu...,Vicentinho,10000,deputados,1,1,2053152,2026-05-01 14:19:06.088189,74283,2026-05-01 14:51:14.844471
228,https://dadosabertos.camara.leg.br/api/v2/depu...,Pastor Eurico,10000,deputados,123,1,2268427,2026-05-01 14:19:06.088189,160642,2026-05-01 14:51:14.844471
341,https://dadosabertos.camara.leg.br/api/v2/orga...,Senado Federal,40000,orgaos,1,1,2599899,2026-05-01 14:19:06.088189,78,2026-05-01 14:51:14.844471
129,https://dadosabertos.camara.leg.br/api/v2/depu...,Capitão Wagner,10000,deputados,117,1,2268427,2026-05-01 14:19:06.088189,204487,2026-05-01 14:51:14.844471
63,https://dadosabertos.camara.leg.br/api/v2/depu...,João H. Campos,10000,deputados,1,1,2236222,2026-05-01 14:19:06.088189,204429,2026-05-01 14:51:14.844471
290,https://dadosabertos.camara.leg.br/api/v2/depu...,Mara Gabrilli,10000,deputados,1,1,2074843,2026-05-01 14:19:06.088189,160565,2026-05-01 14:51:14.844471
142,https://dadosabertos.camara.leg.br/api/v2/depu...,Danrlei de Deus Hinterholz,10000,deputados,90,1,2268427,2026-05-01 14:19:06.088189,160552,2026-05-01 14:51:14.844471
291,https://dadosabertos.camara.leg.br/api/v2/depu...,André Figueiredo,10000,deputados,1,1,2115253,2026-05-01 14:19:06.088189,133439,2026-05-01 14:51:14.844471
115,https://dadosabertos.camara.leg.br/api/v2/depu...,Angela Amin,10000,deputados,122,1,2268427,2026-05-01 14:19:06.088189,73696,2026-05-01 14:51:14.844471
75,https://dadosabertos.camara.leg.br/api/v2/depu...,Ivo José,10000,deputados,14,1,257161,2026-05-01 14:19:06.088189,74153,2026-05-01 14:51:14.844471
152,https://dadosabertos.camara.leg.br/api/v2/depu...,Eros Biondini,10000,deputados,134,1,2268427,2026-05-01 14:19:06.088189,160640,2026-05-01 14:51:14.844471
302,https://dadosabertos.camara.leg.br/api/v2/depu...,Jaime Martins,10000,deputados,1,1,1548579,2026-05-01 14:19:06.088189,74665,2026-05-01 14:51:14.844471
227,https://dadosabertos.camara.leg.br/api/v2/depu...,Otto Alencar Filho,10000,deputados,88,1,2268427,2026-05-01 14:19:06.088189,204573,2026-05-01 14:51:14.844471
324,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481886,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
137,https://dadosabertos.camara.leg.br/api/v2/depu...,Christino Aureo,10000,deputados,118,1,2268427,2026-05-01 14:19:06.088189,204440,2026-05-01 14:51:14.844471
69,https://dadosabertos.camara.leg.br/api/v2/depu...,Rogério Correia,10000,deputados,1,1,2236242,2026-05-01 14:19:06.088189,204480,2026-05-01 14:51:14.844471
198,https://dadosabertos.camara.leg.br/api/v2/depu...,Júnior Mano,10000,deputados,77,1,2268427,2026-05-01 14:19:06.088189,204550,2026-05-01 14:51:14.844471
300,https://dadosabertos.camara.leg.br/api/v2/depu...,José Eduardo Cardozo,10000,deputados,1,1,253500,2026-05-01 14:19:06.088189,74274,2026-05-01 14:51:14.844471
176,https://dadosabertos.camara.leg.br/api/v2/depu...,Hugo Leal,10000,deputados,152,1,2268427,2026-05-01 14:19:06.088189,141450,2026-05-01 14:51:14.844471
62,https://dadosabertos.camara.leg.br/api/v2/orga...,Associação Nacional de Fibromiálgicos e Doença...,70000,orgaos,1,1,2236218,2026-05-01 14:19:06.088189,102223,2026-05-01 14:51:14.844471
91,https://dadosabertos.camara.leg.br/api/v2/depu...,Bebeto,10000,deputados,2,1,1301128,2026-05-01 14:19:06.088189,178834,2026-05-01 14:51:14.844471
109,https://dadosabertos.camara.leg.br/api/v2/depu...,Amaro Neto,10000,deputados,4,1,2268427,2026-05-01 14:19:06.088189,204356,2026-05-01 14:51:14.844471
317,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481877,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
237,https://dadosabertos.camara.leg.br/api/v2/depu...,Raimundo Costa,10000,deputados,29,1,2268427,2026-05-01 14:19:06.088189,204567,2026-05-01 14:51:14.844471
27,https://dadosabertos.camara.leg.br/api/v2/depu...,André Figueiredo,10000,deputados,3,1,549767,2026-05-01 14:19:06.088189,133439,2026-05-01 14:51:14.844471
256,https://dadosabertos.camara.leg.br/api/v2/depu...,Soraya Santos,10000,deputados,35,1,2268427,2026-05-01 14:19:06.088189,178946,2026-05-01 14:51:14.844471
66,https://dadosabertos.camara.leg.br/api/v2/depu...,Ivan Valente,10000,deputados,1,1,2236238,2026-05-01 14:19:06.088189,73531,2026-05-01 14:51:14.844471
337,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2599895,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
172,https://dadosabertos.camara.leg.br/api/v2/depu...,Guilherme Mussi,10000,deputados,160,1,2268427,2026-05-01 14:19:06.088189,160667,2026-05-01 14:51:14.844471
118,https://dadosabertos.camara.leg.br/api/v2/depu...,Arthur Lira,10000,deputados,1,1,2268427,2026-05-01 14:19:06.088189,160541,2026-05-01 14:51:14.844471
101,https://dadosabertos.camara.leg.br/api/v2/depu...,Abílio Santana,10000,deputados,13,1,2268427,2026-05-01 14:19:06.088189,204554,2026-05-01 14:51:14.844471
4,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2167562,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
180,https://dadosabertos.camara.leg.br/api/v2/depu...,Jaqueline Cassol,10000,deputados,16,1,2268427,2026-05-01 14:19:06.088189,108338,2026-05-01 14:51:14.844471
209,https://dadosabertos.camara.leg.br/api/v2/depu...,Luizão Goulart,10000,deputados,12,1,2268427,2026-05-01 14:19:06.088189,204418,2026-05-01 14:51:14.844471
307,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2416820,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
299,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2345501,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
217,https://dadosabertos.camara.leg.br/api/v2/depu...,Margarete Coelho,10000,deputados,96,1,2268427,2026-05-01 14:19:06.088189,204430,2026-05-01 14:51:14.844471
147,https://dadosabertos.camara.leg.br/api/v2/depu...,Dr. Frederico,10000,deputados,15,1,2268427,2026-05-01 14:19:06.088189,204518,2026-05-01 14:51:14.844471
112,https://dadosabertos.camara.leg.br/api/v2/depu...,André Ferreira,10000,deputados,3,1,2268427,2026-05-01 14:19:06.088189,204423,2026-05-01 14:51:14.844471
238,https://dadosabertos.camara.leg.br/api/v2/depu...,Reinhold Stephanes Junior,10000,deputados,18,1,2268427,2026-05-01 14:19:06.088189,205865,2026-05-01 14:51:14.844471
119,https://dadosabertos.camara.leg.br/api/v2/depu...,Átila Lins,10000,deputados,58,1,2268427,2026-05-01 14:19:06.088189,74090,2026-05-01 14:51:14.844471
181,https://dadosabertos.camara.leg.br/api/v2/depu...,Jerônimo Goergen,10000,deputados,46,1,2268427,2026-05-01 14:19:06.088189,160570,2026-05-01 14:51:14.844471
283,https://dadosabertos.camara.leg.br/api/v2/depu...,Aureo Ribeiro,10000,deputados,1,1,2312667,2026-05-01 14:19:06.088189,160512,2026-05-01 14:51:14.844471
192,https://dadosabertos.camara.leg.br/api/v2/depu...,José Nunes,10000,deputados,85,1,2268427,2026-05-01 14:19:06.088189,160619,2026-05-01 14:51:14.844471
261,https://dadosabertos.camara.leg.br/api/v2/depu...,Valdevan Noventa,10000,deputados,71,1,2268427,2026-05-01 14:19:06.088189,204385,2026-05-01 14:51:14.844471
80,https://dadosabertos.camara.leg.br/api/v2/depu...,Luiz Alberto,10000,deputados,13,1,257161,2026-05-01 14:19:06.088189,74133,2026-05-01 14:51:14.844471
111,https://dadosabertos.camara.leg.br/api/v2/depu...,André de Paula,10000,deputados,38,1,2268427,2026-05-01 14:19:06.088189,74471,2026-05-01 14:51:14.844471
186,https://dadosabertos.camara.leg.br/api/v2/depu...,João Roma,10000,deputados,112,1,2268427,2026-05-01 14:19:06.088189,204576,2026-05-01 14:51:14.844471
174,https://dadosabertos.camara.leg.br/api/v2/depu...,Haroldo Cathedral,10000,deputados,67,1,2268427,2026-05-01 14:19:06.088189,204465,2026-05-01 14:51:14.844471
21,https://dadosabertos.camara.leg.br/api/v2/depu...,Erika Kokay,10000,deputados,1,1,512431,2026-05-01 14:19:06.088189,160575,2026-05-01 14:51:14.844471
120,https://dadosabertos.camara.leg.br/api/v2/depu...,Átila Lira,10000,deputados,132,1,2268427,2026-05-01 14:19:06.088189,74459,2026-05-01 14:51:14.844471
16,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,308880,2026-05-01 14:19:06.088189,253,2026-05-01 14:51:14.844471
5,https://dadosabertos.camara.leg.br/api/v2/depu...,Reginaldo Lopes,10000,deputados,1,1,2167563,2026-05-01 14:19:06.088189,74161,2026-05-01 14:51:14.844471
173,https://dadosabertos.camara.leg.br/api/v2/depu...,Gustinho Ribeiro,10000,deputados,163,1,2268427,2026-05-01 14:19:06.088189,204408,2026-05-01 14:51:14.844471
97,https://dadosabertos.camara.leg.br/api/v2/depu...,José Guimarães,10000,deputados,1,1,2268422,2026-05-01 14:19:06.088189,141470,2026-05-01 14:51:14.844471
252,https://dadosabertos.camara.leg.br/api/v2/depu...,Sergio Toledo,10000,deputados,54,1,2268427,2026-05-01 14:19:06.088189,204438,2026-05-01 14:51:14.844471

In [ ]:
df_deputados = dfs_silver['silver_deputado']

In [ ]:
df_deputados.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_Mandato           1000 non-null   Int64
 1   nom_NomeCivil        1000 non-null   string
 2   nom_Sexo             1000 non-null   string
 3   dat_DataNasc         1000 non-null   datetime64[us]
 4   dat_DataFalecimento  6 non-null      datetime64[us]
 5   nom_UFNasc           999 non-null    string
 6   nom_MunicipioNasci   1000 non-null   string
 7   nom_Escolaridade     986 non-null    string
 8   nom_SiglaPartido     1000 non-null   string
 9   nom_UFRepresenta     1000 non-null   string
 10  id_legislatura       1000 non-null   Int64
 11  nom_Email            0 non-null      string
 12  nom_NomeEleitoral    1000 non-null   string
 13  nom_Situacao         999 non-null    string
 14  nom_CondEleitoral    1000 non-null   string
 15  id_Deputado          1000 non-null   Int64
 16  data_extracao        1000 non-null   datetime64[us]
dtypes: Int64(3), datetime64[us](3), string(11)
memory usage: 224.0 KB

In [ ]:
df_autores.info()

<class 'pandas.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uri_Autor            343 non-null    string
 1   nom_Autor            343 non-null    string
 2   cod_TipoAutor        343 non-null    Int64
 3   nom_TipoAutor        343 non-null    str
 4   num_OrdemAssinatura  343 non-null    Int64
 5   ind_Proponente       343 non-null    string
 6   id_Proposicao        343 non-null    Int64
 7   dat_Extracao         343 non-null    datetime64[us]
 8   id_Autor             343 non-null    Int64
 9   data_extracao        343 non-null    datetime64[us]
dtypes: Int64(4), datetime64[us](2), str(1), string(3)
memory usage: 55.5 KB

In [ ]:
df_temas.info()

<class 'pandas.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cod_Tema        141 non-null    Int64
 1   nom_Tema        141 non-null    string
 2   num_Relevancia  141 non-null    Int64
 3   id_proposicao   141 non-null    Int64
 4   dat_Extracao    141 non-null    datetime64[us]
 5   data_extracao   141 non-null    datetime64[us]
dtypes: Int64(3), datetime64[us](2), string(1)
memory usage: 10.5 KB

In [ ]:
dim_deputado = dfs_gold['dim_deputado']

In [ ]:
dim_deputado.dtypes

id_deputado                 Int64
nome                       string
sexo                       string
dat_nasc           datetime64[us]
dat_falecimento    datetime64[us]
uf_nasc                    string
municipio_nasc             string
data_extracao      datetime64[us]
dtype: object

In [ ]:
df_tipo_autor = dfs_silver['silver_tipos_autores']

In [ ]:
df_tipo_autor.head()

   id_Autor                      nom_NomeAutor              data_extracao
0         1                  COMISSÃO DIRETORA 2026-05-01 14:53:14.020277
1         2                COMISSÃO PERMANENTE 2026-05-01 14:53:14.020277
2         3                  COMISSÃO ESPECIAL 2026-05-01 14:53:14.020277
3         4  COMISSÃO PARLAMENTAR DE INQUÉRITO 2026-05-01 14:53:14.020277
4         5                   COMISSÃO EXTERNA 2026-05-01 14:53:14.020277

In [ ]:
df_tipo_autor[df_tipo_autor['id_Autor']==10000]

    id_Autor nom_NomeAutor              data_extracao
36     10000   Deputado(a) 2026-05-01 14:53:14.020277

In [ ]:
df_analise = analisar_dfs(dfs_silver)

In [ ]:
df_analise.head()

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
0,dim_s_deputados,id_deputado,int64,0,0.000000,513,513
1,dim_s_deputados,nom_Nome,str,0,0.000000,513,513
2,dim_s_deputados,nom_Sexo,str,0,0.000000,2,513
3,dim_s_deputados,dat_DataNascimento,datetime64[us],0,0.000000,502,513
4,dim_s_deputados,nom_UF,str,1,0.001949,27,513

In [ ]:
df_voto_proposicao = dfs_silver['silver_votacao_proposicao']

In [ ]:
df_voto_proposicao.info()

<class 'pandas.DataFrame'>
RangeIndex: 819 entries, 0 to 818
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_Votacao        819 non-null    string
 1   dat_DataVotacao   819 non-null    datetime64[us]
 2   dat_DataRegistro  819 non-null    datetime64[us]
 3   uri_Orgao         819 non-null    string
 4   nom_Descricao     819 non-null    string
 5   ind_Aprovado      797 non-null    string
 6   id_Proposicao     819 non-null    Int64
 7   id_Orgao          819 non-null    Int64
 8   data_extracao     819 non-null    datetime64[us]
dtypes: Int64(2), datetime64[us](3), string(4)
memory usage: 164.2 KB

In [ ]:
df_voto_detalhamento = dfs_silver['silver_votacao_detalhamento']
df_voto_detalhamento.info()

<class 'pandas.DataFrame'>
RangeIndex: 819 entries, 0 to 818
Data columns (total 24 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   id                                                819 non-null    str
 1   uri                                               819 non-null    str
 2   data                                              819 non-null    str
 3   dataHoraRegistro                                  819 non-null    str
 4   siglaOrgao                                        819 non-null    str
 5   uriOrgao                                          819 non-null    str
 6   idOrgao                                           819 non-null    int64
 7   uriEvento                                         732 non-null    str
 8   idEvento                                          732 non-null    float64
 9   descricao                                         819 non-null    str
 10  aprovacao                                         797 non-null    float64
 11  descUltimaAberturaVotacao                         193 non-null    str
 12  dataHoraUltimaAberturaVotacao                     193 non-null    str
 13  efeitosRegistrados                                819 non-null    object
 14  objetosPossiveis                                  819 non-null    object
 15  ultimaApresentacaoProposicao.dataHoraRegistro     694 non-null    str
 16  ultimaApresentacaoProposicao.descricao            717 non-null    str
 17  ultimaApresentacaoProposicao.uriProposicaoCitada  412 non-null    str
 18  source_id                                         819 non-null    str
 19  data_extracao                                     819 non-null    datetime64[us]
 20  id_Proposicao                                     0 non-null      object
 21  nom_SiglaTipoProposicao                           0 non-null      object
 22  num_Proposicao                                    0 non-null      object
 23  num_AnoProposicao                                 0 non-null      object
dtypes: datetime64[us](1), float64(2), int64(1), object(6), str(14)
memory usage: 675.3+ KB

In [ ]:
df_filtrado.head()

Empty DataFrame
Columns: [tabela, coluna, tipo, nulos, %_nulos, unicos, total_linhas, match]
Index: []

In [ ]:
df_votos_deputados = dfs_silver['silver_votos_deputados']

df_votos_deputados.info()

<class 'pandas.DataFrame'>
RangeIndex: 41678 entries, 0 to 41677
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nom_Voto          41678 non-null  string
 1   dat_DataRegistro  41678 non-null  datetime64[us]
 2   id_Deputado       41678 non-null  Int64
 3   id_Votacao        41678 non-null  string
 4   data_extracao     41678 non-null  datetime64[us]
dtypes: Int64(1), datetime64[us](2), string(2)
memory usage: 2.2 MB

In [ ]:
df_orientacao = dfs_silver['silver_orientacao']

df_orientacao.info()

<class 'pandas.DataFrame'>
RangeIndex: 1883 entries, 0 to 1882
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   nom_OrientacaoVoto     1883 non-null   string
 1   id_TipoLideranca       0 non-null      Int64
 2   nom_SiglaPartidoBloco  1883 non-null   string
 3   id_PartidoBloco        1268 non-null   Int64
 4   des_UriPartidoBloco    1268 non-null   string
 5   id_Votacao             1883 non-null   string
 6   dat_DataExtracao       1883 non-null   datetime64[us]
 7   data_extracao          1883 non-null   datetime64[us]
dtypes: Int64(2), datetime64[us](2), string(4)
memory usage: 228.4 KB

In [ ]:
df_orientacao = dfs_silver['silver_orientacao']

df_orientacao.info()

<class 'pandas.DataFrame'>
RangeIndex: 1883 entries, 0 to 1882
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   nom_OrientacaoVoto     1883 non-null   string
 1   id_TipoLideranca       0 non-null      Int64
 2   nom_SiglaPartidoBloco  1883 non-null   string
 3   id_PartidoBloco        1268 non-null   Int64
 4   des_UriPartidoBloco    1268 non-null   string
 5   id_Votacao             1883 non-null   string
 6   dat_DataExtracao       1883 non-null   datetime64[us]
 7   data_extracao          1883 non-null   datetime64[us]
dtypes: Int64(2), datetime64[us](2), string(4)
memory usage: 228.4 KB

In [ ]:
df_proposicao = dfs_silver['silver_proposicao']

In [ ]:
df_proposicao.info()

<class 'pandas.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_Proposicao       135 non-null    Int64
 1   nom_TipoProposicao  135 non-null    string
 2   cod_Tipo            135 non-null    Int64
 3   num_NumeroProp      135 non-null    Int64
 4   num_Ano             135 non-null    Int64
 5   nom_Ementa          135 non-null    string
 6   dat_Apresentacao    135 non-null    datetime64[us]
 7   uri_Autor           135 non-null    string
 8   nom_Keywords        105 non-null    string
 9   nom_SiglaOrgao      133 non-null    string
 10  uri_Relator         85 non-null     string
 11  nom_regime          135 non-null    string
 12  nom_TipoTramitacao  133 non-null    string
 13  cod_TipoTramitacao  133 non-null    Int64
 14  cod_TipoSiituacao   101 non-null    string
 15  cod_Situacao        101 non-null    Int64
 16  nom_LinkProposicao  35 non-null     string
 17  nom_TipoAutor       135 non-null    str
 18  id_Autor            135 non-null    Int64
 19  nom_TipoRelator     85 non-null     str
 20  id_Relator          85 non-null     Int64
 21  data_extracao       135 non-null    datetime64[us]
dtypes: Int64(8), datetime64[us](2), str(2), string(10)
memory usage: 109.2 KB

In [ ]:
dim_bloco_partido = dfs_gold['dim_partido_bloco']

In [ ]:
dim_bloco_partido.info(0)

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nom_sigla      40 non-null     string
 1   id_partido     40 non-null     str
 2   data_extracao  40 non-null     datetime64[us]
dtypes: datetime64[us](1), str(1), string(1)
memory usage: 2.6 KB

In [ ]:
<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   id_partido_bloco  28 non-null     Int64         
 1   nom_sigla         41 non-null     string        
 2   data_extracao     41 non-null     datetime64[us]
dtypes: Int64(1), datetime64[us](1), string(1)
memory usage: 1.4 KB

AttributeError: 'Series' object has no attribute 'isunique'

In [ ]:
df_periodo = dfs_gold['dim_periodo']

In [ ]:
df_periodo.info()

<class 'pandas.DataFrame'>
RangeIndex: 19806 entries, 0 to 19805
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           19806 non-null  datetime64[us]
 1   ano            19806 non-null  int32
 2   mes            19806 non-null  int32
 3   dia            19806 non-null  int32
 4   trimestre      19806 non-null  int32
 5   data_extracao  19806 non-null  datetime64[us]
dtypes: datetime64[us](2), int32(4)
memory usage: 619.1 KB

In [ ]:
df_autor = dfs_Silved

NameError: name 'df_autor' is not defined

In [4]:
# Verifica merge entre silver_autores e silver_deputados
df_autores = dfs_silver['silver_autores']
df_deputados = dfs_silver['silver_deputado']

print("Colunas em silver_autores:")
print(df_autores.columns.tolist())
print("\nColunas em silver_deputado:")
print(df_deputados.columns.tolist())

# Tenta merge por nome (normalizando)
from unidecode import unidecode

df_autores['nome_clean'] = df_autores['nom_Autor'].str.upper().str.strip().apply(lambda x: unidecode(x) if isinstance(x, str) else x)
df_deputados['nome_clean'] = df_deputados['nom_NomeCivil'].str.upper().str.strip().apply(lambda x: unidecode(x) if isinstance(x, str) else x)

# Merge
merge_result = df_autores.merge(
    df_deputados[['id_Deputado', 'nome_clean']],
    on='nome_clean',
    how='left'
)

print(f"\nTotal de autores: {len(df_autores)}")
print(f"Autores com match em deputados: {merge_result['id_Deputado'].notna().sum()}")
print(f"Autores sem match: {merge_result['id_Deputado'].isna().sum()}")

# Mostra exemplos
print("\nExemplos com match:")
print(merge_result[merge_result['id_Deputado'].notna()][['nom_Autor', 'id_Deputado']].head())

Colunas em silver_autores:
['uri_Autor', 'nom_Autor', 'cod_TipoAutor', 'nom_TipoAutor', 'num_OrdemAssinatura', 'ind_Proponente', 'id_Proposicao', 'dat_Extracao', 'id_Autor', 'data_extracao']

Colunas em silver_deputado:
['id_Mandato', 'nom_NomeCivil', 'nom_Sexo', 'dat_DataNasc', 'dat_DataFalecimento', 'nom_UFNasc', 'nom_MunicipioNasci', 'nom_Escolaridade', 'nom_SiglaPartido', 'nom_UFRepresenta', 'id_legislatura', 'nom_Email', 'nom_NomeEleitoral', 'nom_Situacao', 'nom_CondEleitoral', 'id_Deputado', 'data_extracao']

Total de autores: 343
Autores com match em deputados: 24
Autores sem match: 338

Exemplos com match:
                     nom_Autor  id_Deputado
136  Christiane de Souza Yared       178928
137  Christiane de Souza Yared       178928
138  Christiane de Souza Yared       178928
139  Christiane de Souza Yared       178928
140  Christiane de Souza Yared       178928

In [5]:
dim_periodo = dfs_gold['dim_periodo']
dim_proposica= dfs_gold['dim_proposicao']

NameError: name 'dfs_gold' is not defined

In [7]:
dim_proposicao = dfs_gold['dim_proposicao']
dim_periodo = dfs_gold['dim_periodo']

# identifica possíveis colunas de data na proposição
date_cols = [c for c in dim_proposicao.columns if c.lower().startswith('dat_')]
print("Colunas de data em silver_proposicao:", date_cols)

periodo_dates = set(pd.to_datetime(dim_periodo['data'], errors='coerce').dt.date.dropna())

for col in date_cols:
    proposicao_dates = set(
        pd.to_datetime(dim_proposicao[col], errors='coerce').dt.date.dropna()
    )
    faltantes = proposicao_dates - periodo_dates
    print(f"\n{col}:")
    print("  total datas únicas na proposição:", len(proposicao_dates))
    print("  faltantes em dim_periodo:", len(faltantes))
    if faltantes:
        print("  exemplos:", sorted(faltantes)[:20])

Colunas de data em silver_proposicao: ['dat_apresentacao']

dat_apresentacao:
  total datas únicas na proposição: 84
  faltantes em dim_periodo: 78
  exemplos: [datetime.date(2004, 5, 13), datetime.date(2004, 6, 8), datetime.date(2004, 6, 23), datetime.date(2005, 10, 11), datetime.date(2005, 12, 6), datetime.date(2006, 3, 21), datetime.date(2007, 9, 26), datetime.date(2009, 3, 24), datetime.date(2009, 11, 11), datetime.date(2010, 10, 6), datetime.date(2011, 2, 23), datetime.date(2011, 4, 13), datetime.date(2011, 5, 11), datetime.date(2011, 6, 22), datetime.date(2011, 7, 13), datetime.date(2012, 3, 21), datetime.date(2012, 4, 3), datetime.date(2012, 4, 11), datetime.date(2012, 6, 27), datetime.date(2012, 11, 8)]

In [8]:
df_deputados = dfs_silver['silver_deputado']
df_deputados.columns

Index(['id_Mandato', 'nom_NomeCivil', 'nom_Sexo', 'dat_DataNasc',
       'dat_DataFalecimento', 'nom_UFNasc', 'nom_MunicipioNasci',
       'nom_Escolaridade', 'nom_SiglaPartido', 'nom_UFRepresenta',
       'id_legislatura', 'nom_Email', 'nom_NomeEleitoral', 'nom_Situacao',
       'nom_CondEleitoral', 'id_Deputado', 'data_extracao', 'nome_clean'],
      dtype='str')

In [8]:
df_tipos_Autores = dfs_silver['silver_tipos_autores']
df_tipos_Autores.columns

Index(['id_Autor', 'nom_NomeAutor', 'data_extracao'], dtype='str')

In [10]:
df_tipos_Autores.sample()

    id_Autor     nom_NomeAutor              data_extracao
19        26  Plenário Virtual 2026-05-01 14:53:14.020277

In [9]:
df_autores = dfs_silver['silver_autores']

df_autores.info()

<class 'pandas.DataFrame'>
RangeIndex: 343 entries, 0 to 342
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uri_Autor            343 non-null    string
 1   nom_Autor            343 non-null    string
 2   cod_TipoAutor        343 non-null    Int64
 3   nom_TipoAutor        343 non-null    str
 4   num_OrdemAssinatura  343 non-null    Int64
 5   ind_Proponente       343 non-null    string
 6   id_Proposicao        343 non-null    Int64
 7   dat_Extracao         343 non-null    datetime64[us]
 8   id_Autor             343 non-null    Int64
 9   data_extracao        343 non-null    datetime64[us]
dtypes: Int64(4), datetime64[us](2), str(1), string(3)
memory usage: 55.5 KB