In [1]:
import sys
import os
from datetime import datetime
import pandas as pd
sys.path.append(os.path.abspath("../src"))

In [2]:
from camara_deputados.extraction.api_client import CamaraAPIClient
from camara_deputados.extraction.base_extractor import BaseExtractor
from camara_deputados.extraction.loader import DataLoader

In [5]:
#instâncias 

api_client = CamaraAPIClient()
extractor = BaseExtractor(api_client)
loader = DataLoader()

In [ ]:
df_deputados = extractor.extract('deputados', desc='Lista de Deputados')

🚀 Iniciando extração: Lista de Deputados
🌐 GET deputados
⏱ Tempo: 2.94s | 📦 Registros: 513
📦 Registros extraídos: 513

,id,uri,nome,siglaPartido,uriPartido,siglaUf,idLegislatura,urlFoto,email
0,204379,https://dadosabertos.camara.leg.br/api/v2/depu...,Acácio Favacho,MDB,https://dadosabertos.camara.leg.br/api/v2/part...,AP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.acaciofavacho@camara.leg.br
1,220714,https://dadosabertos.camara.leg.br/api/v2/depu...,Adail Filho,MDB,https://dadosabertos.camara.leg.br/api/v2/part...,AM,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adailfilho@camara.leg.br
2,221328,https://dadosabertos.camara.leg.br/api/v2/depu...,Adilson Barroso,PL,https://dadosabertos.camara.leg.br/api/v2/part...,SP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adilsonbarroso@camara.leg.br
3,204560,https://dadosabertos.camara.leg.br/api/v2/depu...,Adolfo Viana,PSDB,https://dadosabertos.camara.leg.br/api/v2/part...,BA,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adolfoviana@camara.leg.br
4,204528,https://dadosabertos.camara.leg.br/api/v2/depu...,Adriana Ventura,NOVO,https://dadosabertos.camara.leg.br/api/v2/part...,SP,57,https://www.camara.leg.br/internet/deputado/ba...,dep.adrianaventura@camara.leg.br

In [ ]:
#salva na bronze deputados lista
loader.save_bronze(
    df=df_deputados,
    dataset='deputados_lista',
    layer='bronze'
)

In [8]:
# Lê o arquivo parquet e salva em dataframe 
dataset = 'deputados_lista'
path = f"data/bronze/{dataset}/{dataset}.parquet"
df_deputados= pd.read_parquet(path)

In [18]:
ids_deputados = df_deputados['id']

In [19]:
# extração do detalhamento do deputado

df_deputadosDetalhamento = extractor. extract_by_ids(ids=ids_deputados,
                                                     endpoint_template='deputados/{id}',
                                                     desc='Deputados Detalhamento')

df_deputadosDetalhamento['data_extracao'] = datetime.now()

Deputados Detalhamento:   0%|          | 2/513 [00:00<01:38,  5.18it/s]

🌐 GET deputados/204379
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220714
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   1%|          | 4/513 [00:00<01:34,  5.39it/s]

🌐 GET deputados/221328
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204560
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   1%|          | 6/513 [00:01<01:32,  5.48it/s]

🌐 GET deputados/204528
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/121948
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:   2%|▏         | 8/513 [00:01<01:26,  5.83it/s]

🌐 GET deputados/74646
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/160508
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:   2%|▏         | 10/513 [00:01<01:25,  5.91it/s]

🌐 GET deputados/136811
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/178835
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:   2%|▏         | 12/513 [00:02<01:24,  5.90it/s]

🌐 GET deputados/160527
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204495
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:   3%|▎         | 13/513 [00:02<01:24,  5.90it/s]

🌐 GET deputados/204549
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/73579
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:   3%|▎         | 16/513 [00:02<01:32,  5.34it/s]

🌐 GET deputados/220538
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/160559
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   3%|▎         | 17/513 [00:03<01:36,  5.12it/s]

🌐 GET deputados/204501
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178972
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:   4%|▍         | 20/513 [00:03<01:29,  5.51it/s]

🌐 GET deputados/220542
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/160545
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:   4%|▍         | 22/513 [00:03<01:29,  5.49it/s]

🌐 GET deputados/220554
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/221148
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:   5%|▍         | 24/513 [00:04<01:28,  5.56it/s]

🌐 GET deputados/220576
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/74057
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:   5%|▍         | 25/513 [00:04<01:27,  5.57it/s]

🌐 GET deputados/178927
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:   5%|▌         | 27/513 [00:04<01:31,  5.34it/s]

🌐 GET deputados/204353
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178937
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:   6%|▌         | 29/513 [00:05<01:31,  5.29it/s]

🌐 GET deputados/178881
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220707
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:   6%|▌         | 31/513 [00:05<01:28,  5.43it/s]

🌐 GET deputados/204356
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220715
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:   6%|▋         | 33/513 [00:06<01:28,  5.43it/s]

🌐 GET deputados/107970
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220556
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   7%|▋         | 34/513 [00:06<01:25,  5.59it/s]

🌐 GET deputados/220632
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:   7%|▋         | 36/513 [00:06<01:34,  5.06it/s]

🌐 GET deputados/178831
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET deputados/220657
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:   7%|▋         | 38/513 [00:06<01:28,  5.38it/s]

🌐 GET deputados/204423
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/133439
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:   8%|▊         | 39/513 [00:07<01:24,  5.61it/s]

🌐 GET deputados/178882
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:   8%|▊         | 41/513 [00:07<01:30,  5.24it/s]

🌐 GET deputados/204515
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220676
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   8%|▊         | 42/513 [00:07<01:31,  5.16it/s]

🌐 GET deputados/123756
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:   9%|▊         | 44/513 [00:08<01:33,  5.02it/s]

🌐 GET deputados/220544
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/160553
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   9%|▉         | 46/513 [00:08<01:32,  5.07it/s]

🌐 GET deputados/220638
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220675
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:   9%|▉         | 48/513 [00:08<01:26,  5.36it/s]

🌐 GET deputados/220549
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/73433
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  10%|▉         | 49/513 [00:09<01:24,  5.47it/s]

🌐 GET deputados/141391
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  10%|▉         | 51/513 [00:09<01:35,  4.84it/s]

🌐 GET deputados/160541
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET deputados/160600
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  10%|█         | 53/513 [00:09<01:31,  5.05it/s]

🌐 GET deputados/74090
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/123086
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  11%|█         | 55/513 [00:10<01:25,  5.37it/s]

🌐 GET deputados/160665
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/160512
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  11%|█         | 57/513 [00:10<01:21,  5.62it/s]

🌐 GET deputados/69871
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178975
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  11%|█▏        | 58/513 [00:10<01:22,  5.52it/s]

🌐 GET deputados/220605
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220612
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  12%|█▏        | 61/513 [00:11<01:22,  5.49it/s]

🌐 GET deputados/73701
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/109429
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  12%|█▏        | 62/513 [00:11<01:22,  5.44it/s]

🌐 GET deputados/204358
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  12%|█▏        | 64/513 [00:11<01:23,  5.38it/s]

🌐 GET deputados/220698
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/220683
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  13%|█▎        | 66/513 [00:12<01:26,  5.18it/s]

🌐 GET deputados/204374
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/204388
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  13%|█▎        | 68/513 [00:12<01:22,  5.41it/s]

🌐 GET deputados/160538
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/210989
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  13%|█▎        | 69/513 [00:12<01:22,  5.39it/s]

🌐 GET deputados/220635
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  14%|█▎        | 70/513 [00:13<02:03,  3.58it/s]

🌐 GET deputados/220574
⏱ Tempo: 0.49s | 📦 Registros: 1

Deputados Detalhamento:  14%|█▍        | 71/513 [00:13<02:09,  3.40it/s]

🌐 GET deputados/220548
⏱ Tempo: 0.31s | 📦 Registros: 1

Deputados Detalhamento:  14%|█▍        | 72/513 [00:14<02:08,  3.43it/s]

🌐 GET deputados/204572
⏱ Tempo: 0.28s | 📦 Registros: 1

Deputados Detalhamento:  14%|█▍        | 74/513 [00:14<01:47,  4.08it/s]

🌐 GET deputados/220690
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178829
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  15%|█▍        | 76/513 [00:14<01:32,  4.71it/s]

🌐 GET deputados/213762
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204361
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  15%|█▌        | 78/513 [00:15<01:21,  5.34it/s]

🌐 GET deputados/178962
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178993
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  15%|█▌        | 79/513 [00:15<01:23,  5.19it/s]

🌐 GET deputados/204460
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/74262
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  16%|█▌        | 82/513 [00:15<01:22,  5.22it/s]

🌐 GET deputados/204426
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/141398
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  16%|█▌        | 83/513 [00:16<01:22,  5.24it/s]

🌐 GET deputados/220704
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  17%|█▋        | 85/513 [00:20<07:17,  1.02s/it]

🌐 GET deputados/204369
⏱ Tempo: 4.15s | 📦 Registros: 1
🌐 GET deputados/220699
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  17%|█▋        | 86/513 [00:20<05:32,  1.28it/s]

🌐 GET deputados/206018
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178876
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  17%|█▋        | 89/513 [00:21<02:42,  2.61it/s]

🌐 GET deputados/204488
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/73441
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  18%|█▊        | 90/513 [00:21<02:20,  3.01it/s]

🌐 GET deputados/204496
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  18%|█▊        | 92/513 [00:21<01:52,  3.74it/s]

🌐 GET deputados/204504
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/205476
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  18%|█▊        | 94/513 [00:22<01:36,  4.36it/s]

🌐 GET deputados/74171
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/204462
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  19%|█▊        | 96/513 [00:22<01:26,  4.83it/s]

🌐 GET deputados/220665
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/74537
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  19%|█▉        | 97/513 [00:22<01:34,  4.40it/s]

🌐 GET deputados/141408
⏱ Tempo: 0.26s | 📦 Registros: 1
🌐 GET deputados/88256
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  19%|█▉        | 100/513 [00:23<01:22,  5.00it/s]

🌐 GET deputados/98148
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220594
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  20%|█▉        | 102/513 [00:23<01:17,  5.30it/s]

🌐 GET deputados/204378
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220595
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  20%|██        | 104/513 [00:24<01:16,  5.37it/s]

🌐 GET deputados/220666
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220590
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  20%|██        | 105/513 [00:24<01:18,  5.21it/s]

🌐 GET deputados/220608
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  21%|██        | 106/513 [00:24<01:20,  5.05it/s]

🌐 GET deputados/204355
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  21%|██        | 108/513 [00:24<01:22,  4.91it/s]

🌐 GET deputados/141411
⏱ Tempo: 0.26s | 📦 Registros: 1
🌐 GET deputados/220555
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  21%|██▏       | 110/513 [00:25<01:19,  5.08it/s]

🌐 GET deputados/220692
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/74467
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  22%|██▏       | 112/513 [00:25<01:13,  5.46it/s]

🌐 GET deputados/220629
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220603
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  22%|██▏       | 114/513 [00:26<01:13,  5.40it/s]

🌐 GET deputados/220571
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/74060
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  23%|██▎       | 116/513 [00:26<01:11,  5.53it/s]

🌐 GET deputados/220582
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204367
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  23%|██▎       | 118/513 [00:26<01:09,  5.69it/s]

🌐 GET deputados/204409
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204459
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  23%|██▎       | 120/513 [00:27<01:07,  5.83it/s]

🌐 GET deputados/220557
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/62881
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  24%|██▍       | 122/513 [00:27<01:08,  5.67it/s]

🌐 GET deputados/160552
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204511
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  24%|██▍       | 124/513 [00:27<01:08,  5.67it/s]

🌐 GET deputados/220539
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220565
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  25%|██▍       | 126/513 [00:28<01:09,  5.58it/s]

🌐 GET deputados/220625
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220561
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  25%|██▍       | 128/513 [00:28<01:07,  5.71it/s]

🌐 GET deputados/220642
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220673
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  25%|██▌       | 130/513 [00:28<01:10,  5.47it/s]

🌐 GET deputados/220649
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/178908
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  26%|██▌       | 131/513 [00:29<01:08,  5.60it/s]

🌐 GET deputados/220583
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  26%|██▌       | 132/513 [00:29<01:14,  5.11it/s]

🌐 GET deputados/204512
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET deputados/220701
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  26%|██▋       | 135/513 [00:29<01:12,  5.22it/s]

🌐 GET deputados/220652
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220654
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  27%|██▋       | 137/513 [00:30<01:12,  5.22it/s]

🌐 GET deputados/220553
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/160588
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  27%|██▋       | 139/513 [00:30<01:08,  5.43it/s]

🌐 GET deputados/220691
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/178929
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  27%|██▋       | 141/513 [00:30<01:07,  5.49it/s]

🌐 GET deputados/73768
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220671
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  28%|██▊       | 142/513 [00:31<01:05,  5.70it/s]

🌐 GET deputados/160599
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220602
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  28%|██▊       | 144/513 [00:31<01:10,  5.26it/s]

🌐 GET deputados/143632
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/160758
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  29%|██▊       | 147/513 [00:32<01:10,  5.23it/s]

🌐 GET deputados/220573
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204450
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  29%|██▉       | 149/513 [00:32<01:09,  5.24it/s]

🌐 GET deputados/227991
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220614
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  29%|██▉       | 151/513 [00:32<01:06,  5.46it/s]

🌐 GET deputados/220610
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220688
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  30%|██▉       | 153/513 [00:33<01:04,  5.61it/s]

🌐 GET deputados/204518
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220570
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  30%|███       | 155/513 [00:33<01:02,  5.75it/s]

🌐 GET deputados/204481
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204351
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  31%|███       | 157/513 [00:33<01:04,  5.51it/s]

🌐 GET deputados/220528
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204412
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  31%|███       | 159/513 [00:34<01:03,  5.55it/s]

🌐 GET deputados/220674
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220686
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  31%|███▏      | 161/513 [00:34<01:02,  5.62it/s]

🌐 GET deputados/220540
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220623
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  32%|███▏      | 163/513 [00:34<01:00,  5.77it/s]

🌐 GET deputados/204541
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/141421
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  32%|███▏      | 165/513 [00:35<00:58,  5.93it/s]

🌐 GET deputados/220589
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/74075
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  33%|███▎      | 167/513 [00:35<00:59,  5.83it/s]

🌐 GET deputados/204364
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/178854
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  33%|███▎      | 169/513 [00:36<01:00,  5.67it/s]

🌐 GET deputados/198783
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/161550
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  33%|███▎      | 171/513 [00:36<01:03,  5.38it/s]

🌐 GET deputados/230765
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220663
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  34%|███▎      | 173/513 [00:36<01:04,  5.31it/s]

🌐 GET deputados/220645
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/160575
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  34%|███▍      | 175/513 [00:37<00:59,  5.68it/s]

🌐 GET deputados/160640
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/74454
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  35%|███▍      | 177/513 [00:37<01:00,  5.53it/s]

🌐 GET deputados/178871
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/178905
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  35%|███▍      | 179/513 [00:37<00:57,  5.76it/s]

🌐 GET deputados/220681
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/171623
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  35%|███▌      | 180/513 [00:38<00:59,  5.61it/s]

🌐 GET deputados/204368
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  35%|███▌      | 182/513 [00:38<01:03,  5.21it/s]

🌐 GET deputados/220653
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220712
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  36%|███▌      | 184/513 [00:38<01:00,  5.42it/s]

🌐 GET deputados/66828
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220646
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  36%|███▌      | 185/513 [00:38<01:01,  5.35it/s]

🌐 GET deputados/72442
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/204398
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  37%|███▋      | 188/513 [00:39<00:59,  5.46it/s]

🌐 GET deputados/160666
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204407
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  37%|███▋      | 190/513 [00:39<00:58,  5.50it/s]

🌐 GET deputados/220656
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/141431
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  37%|███▋      | 192/513 [00:40<00:57,  5.59it/s]

🌐 GET deputados/204445
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/92699
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  38%|███▊      | 193/513 [00:40<01:07,  4.71it/s]

🌐 GET deputados/204427
⏱ Tempo: 0.28s | 📦 Registros: 1

Deputados Detalhamento:  38%|███▊      | 195/513 [00:40<01:07,  4.73it/s]

🌐 GET deputados/204411
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET deputados/220545
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  38%|███▊      | 197/513 [00:41<01:00,  5.24it/s]

🌐 GET deputados/160598
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/191923
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  39%|███▉      | 199/513 [00:42<02:05,  2.50it/s]

🌐 GET deputados/220700
⏱ Tempo: 1.21s | 📦 Registros: 1
🌐 GET deputados/220551
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  39%|███▉      | 200/513 [00:42<01:46,  2.95it/s]

🌐 GET deputados/204494
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220534
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  40%|███▉      | 203/513 [00:43<01:10,  4.37it/s]

🌐 GET deputados/224117
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/220708
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  40%|███▉      | 205/513 [00:43<01:02,  4.91it/s]

🌐 GET deputados/204473
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220611
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  40%|████      | 207/513 [00:44<00:57,  5.31it/s]

🌐 GET deputados/178966
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220702
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  41%|████      | 209/513 [00:44<00:56,  5.42it/s]

🌐 GET deputados/74374
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204394
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  41%|████      | 211/513 [00:44<00:55,  5.41it/s]

🌐 GET deputados/74383
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204491
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  42%|████▏     | 213/513 [00:45<00:54,  5.51it/s]

🌐 GET deputados/74270
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220529
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  42%|████▏     | 215/513 [00:45<00:51,  5.77it/s]

🌐 GET deputados/204365
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/220526
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  42%|████▏     | 217/513 [00:45<00:50,  5.91it/s]

🌐 GET deputados/160673
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204419
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  43%|████▎     | 219/513 [00:46<00:49,  5.98it/s]

🌐 GET deputados/107283
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/129618
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  43%|████▎     | 221/513 [00:46<00:52,  5.60it/s]

🌐 GET deputados/198197
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/204531
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  43%|████▎     | 223/513 [00:46<00:48,  5.94it/s]

🌐 GET deputados/220664
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/220568
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  44%|████▍     | 225/513 [00:47<00:48,  5.92it/s]

🌐 GET deputados/204408
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204456
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  44%|████▍     | 226/513 [00:47<00:49,  5.85it/s]

🌐 GET deputados/178964
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  44%|████▍     | 227/513 [00:47<00:53,  5.33it/s]

🌐 GET deputados/178873
⏱ Tempo: 0.22s | 📦 Registros: 1

Deputados Detalhamento:  44%|████▍     | 228/513 [00:47<00:58,  4.88it/s]

🌐 GET deputados/220537
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET deputados/204444
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  45%|████▍     | 230/513 [00:48<00:56,  4.98it/s]

🌐 GET deputados/234788
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  45%|████▌     | 232/513 [00:48<00:57,  4.92it/s]

🌐 GET deputados/220672
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/204539
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  45%|████▌     | 233/513 [00:48<00:55,  5.01it/s]

🌐 GET deputados/178884
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  46%|████▌     | 235/513 [00:49<00:53,  5.17it/s]

🌐 GET deputados/141450
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/160674
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  46%|████▌     | 236/513 [00:49<00:51,  5.38it/s]

🌐 GET deputados/220563
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  46%|████▋     | 238/513 [00:49<00:52,  5.29it/s]

🌐 GET deputados/204533
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/204508
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  47%|████▋     | 240/513 [00:50<00:50,  5.37it/s]

🌐 GET deputados/235620
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/74295
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  47%|████▋     | 242/513 [00:50<00:47,  5.70it/s]

🌐 GET deputados/98615
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204436
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  48%|████▊     | 244/513 [00:50<00:50,  5.36it/s]

🌐 GET deputados/220696
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220670
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  48%|████▊     | 246/513 [00:51<00:48,  5.50it/s]

🌐 GET deputados/220527
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/220697
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  48%|████▊     | 247/513 [00:51<00:48,  5.51it/s]

🌐 GET deputados/74848
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  49%|████▊     | 249/513 [00:51<00:48,  5.45it/s]

🌐 GET deputados/220567
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/74273
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  49%|████▊     | 250/513 [00:52<00:47,  5.58it/s]

🌐 GET deputados/141456
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  49%|████▉     | 252/513 [00:55<04:39,  1.07s/it]

🌐 GET deputados/235869
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET deputados/141458
⏱ Tempo: 3.12s | 📦 Registros: 1

Deputados Detalhamento:  50%|████▉     | 254/513 [00:55<02:41,  1.61it/s]

🌐 GET deputados/230957
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/178970
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  50%|████▉     | 256/513 [00:56<01:39,  2.58it/s]

🌐 GET deputados/141459
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/178910
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  50%|█████     | 257/513 [00:56<01:26,  2.97it/s]

🌐 GET deputados/160548
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  50%|█████     | 258/513 [00:56<01:17,  3.29it/s]

🌐 GET deputados/235800
⏱ Tempo: 0.22s | 📦 Registros: 1

Deputados Detalhamento:  50%|█████     | 259/513 [00:56<01:11,  3.55it/s]

🌐 GET deputados/205550
⏱ Tempo: 0.22s | 📦 Registros: 1

Deputados Detalhamento:  51%|█████     | 261/513 [00:57<00:59,  4.24it/s]

🌐 GET deputados/214694
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178857
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  51%|█████▏    | 263/513 [00:57<00:51,  4.84it/s]

🌐 GET deputados/141464
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204472
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  52%|█████▏    | 265/513 [00:57<00:48,  5.16it/s]

🌐 GET deputados/204391
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/74079
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  52%|█████▏    | 267/513 [00:58<00:45,  5.40it/s]

🌐 GET deputados/74554
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/209189
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  52%|█████▏    | 269/513 [00:58<00:43,  5.55it/s]

🌐 GET deputados/220578
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/215043
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  53%|█████▎    | 271/513 [00:58<00:44,  5.48it/s]

🌐 GET deputados/204474
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220559
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  53%|█████▎    | 273/513 [00:59<00:44,  5.44it/s]

🌐 GET deputados/220640
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/66385
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  54%|█████▎    | 275/513 [00:59<00:41,  5.74it/s]

🌐 GET deputados/74317
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204372
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  54%|█████▍    | 277/513 [01:00<00:43,  5.38it/s]

🌐 GET deputados/74253
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/204457
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  54%|█████▍    | 279/513 [01:00<00:41,  5.65it/s]

🌐 GET deputados/204520
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204497
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  55%|█████▍    | 281/513 [01:00<00:40,  5.79it/s]

🌐 GET deputados/204574
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204550
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  55%|█████▌    | 283/513 [01:01<00:43,  5.30it/s]

🌐 GET deputados/178886
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220677
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  56%|█████▌    | 285/513 [01:01<00:42,  5.41it/s]

🌐 GET deputados/162067
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204536
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  56%|█████▌    | 287/513 [01:01<00:39,  5.72it/s]

🌐 GET deputados/98057
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/74856
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  56%|█████▋    | 289/513 [01:02<00:40,  5.57it/s]

🌐 GET deputados/178832
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220566
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  57%|█████▋    | 291/513 [01:02<00:39,  5.58it/s]

🌐 GET deputados/80815
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/74156
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  57%|█████▋    | 293/513 [01:02<00:39,  5.51it/s]

🌐 GET deputados/92102
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/139285
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  58%|█████▊    | 295/513 [01:03<00:39,  5.52it/s]

🌐 GET deputados/74585
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/74858
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  58%|█████▊    | 297/513 [01:03<00:39,  5.44it/s]

🌐 GET deputados/220662
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204404
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  58%|█████▊    | 299/513 [01:04<00:38,  5.57it/s]

🌐 GET deputados/220581
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/74478
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  58%|█████▊    | 300/513 [01:04<00:38,  5.58it/s]

🌐 GET deputados/178931
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  59%|█████▉    | 302/513 [01:04<00:40,  5.25it/s]

🌐 GET deputados/220616
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET deputados/178954
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  59%|█████▉    | 303/513 [01:04<00:41,  5.09it/s]

🌐 GET deputados/204410
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/141485
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  60%|█████▉    | 306/513 [01:05<00:39,  5.28it/s]

🌐 GET deputados/73778
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204485
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  60%|██████    | 308/513 [01:05<00:36,  5.60it/s]

🌐 GET deputados/74041
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/141487
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  60%|██████    | 310/513 [01:06<00:36,  5.57it/s]

🌐 GET deputados/220658
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204455
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  61%|██████    | 312/513 [01:06<00:35,  5.59it/s]

🌐 GET deputados/162332
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204526
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  61%|██████    | 314/513 [01:06<00:36,  5.43it/s]

🌐 GET deputados/74784
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/178866
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  61%|██████▏   | 315/513 [01:06<00:35,  5.61it/s]

🌐 GET deputados/220669
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  62%|██████▏   | 316/513 [01:07<00:41,  4.76it/s]

🌐 GET deputados/166402
⏱ Tempo: 0.28s | 📦 Registros: 1

Deputados Detalhamento:  62%|██████▏   | 317/513 [01:07<00:46,  4.22it/s]

🌐 GET deputados/220648
⏱ Tempo: 0.28s | 📦 Registros: 1

Deputados Detalhamento:  62%|██████▏   | 318/513 [01:07<00:57,  3.40it/s]

🌐 GET deputados/156190
⏱ Tempo: 0.42s | 📦 Registros: 1

Deputados Detalhamento:  62%|██████▏   | 319/513 [01:08<01:08,  2.82it/s]

🌐 GET deputados/179000
⏱ Tempo: 0.49s | 📦 Registros: 1

Deputados Detalhamento:  62%|██████▏   | 320/513 [01:08<01:05,  2.96it/s]

🌐 GET deputados/220599
⏱ Tempo: 0.29s | 📦 Registros: 1

Deputados Detalhamento:  63%|██████▎   | 321/513 [01:08<00:58,  3.31it/s]

🌐 GET deputados/133810
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  63%|██████▎   | 323/513 [01:09<00:48,  3.94it/s]

🌐 GET deputados/204558
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET deputados/160161
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  63%|██████▎   | 325/513 [01:09<00:41,  4.57it/s]

🌐 GET deputados/178983
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/179001
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  64%|██████▎   | 327/513 [01:10<00:37,  4.95it/s]

🌐 GET deputados/220687
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/81055
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  64%|██████▍   | 329/513 [01:10<00:35,  5.25it/s]

🌐 GET deputados/150418
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/160535
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  65%|██████▍   | 331/513 [01:10<00:32,  5.52it/s]

🌐 GET deputados/204431
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204506
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  65%|██████▍   | 333/513 [01:11<00:31,  5.65it/s]

🌐 GET deputados/220547
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/178943
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  65%|██████▌   | 334/513 [01:11<00:31,  5.65it/s]

🌐 GET deputados/220604
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220668
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  66%|██████▌   | 337/513 [01:11<00:31,  5.64it/s]

🌐 GET deputados/74398
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204540
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  66%|██████▌   | 338/513 [01:12<00:34,  5.13it/s]

🌐 GET deputados/220637
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET deputados/220655
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  66%|██████▋   | 340/513 [01:12<00:35,  4.90it/s]

🌐 GET deputados/74158
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178858
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  67%|██████▋   | 342/513 [01:12<00:33,  5.03it/s]

🌐 GET deputados/220572
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/178843
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  67%|██████▋   | 344/513 [01:13<00:34,  4.87it/s]

🌐 GET deputados/220661
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  67%|██████▋   | 345/513 [01:13<00:37,  4.53it/s]

🌐 GET deputados/220609
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET deputados/220628
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  68%|██████▊   | 347/513 [01:14<00:33,  5.01it/s]

🌐 GET deputados/220550
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220647
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  68%|██████▊   | 349/513 [01:14<00:31,  5.15it/s]

🌐 GET deputados/204486
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  68%|██████▊   | 351/513 [01:14<00:30,  5.25it/s]

🌐 GET deputados/220607
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220591
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  69%|██████▉   | 353/513 [01:15<00:29,  5.40it/s]

🌐 GET deputados/74428
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/188097
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  69%|██████▉   | 354/513 [01:15<00:28,  5.53it/s]

🌐 GET deputados/220585
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220530
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  70%|██████▉   | 357/513 [01:15<00:29,  5.21it/s]

🌐 GET deputados/171786
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178985
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  70%|██████▉   | 359/513 [01:16<00:29,  5.30it/s]

🌐 GET deputados/154178
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/178895
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  70%|███████   | 361/513 [01:16<00:28,  5.29it/s]

🌐 GET deputados/160561
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/178997
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  71%|███████   | 363/513 [01:17<00:28,  5.21it/s]

🌐 GET deputados/220617
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220584
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  71%|███████   | 365/513 [01:17<00:28,  5.27it/s]

🌐 GET deputados/204453
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204449
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  72%|███████▏  | 367/513 [01:17<00:28,  5.11it/s]

🌐 GET deputados/220622
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220703
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  72%|███████▏  | 369/513 [01:18<00:27,  5.29it/s]

🌐 GET deputados/178896
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204479
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  72%|███████▏  | 371/513 [01:18<00:29,  4.83it/s]

🌐 GET deputados/209787
⏱ Tempo: 0.28s | 📦 Registros: 1
🌐 GET deputados/178986
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  73%|███████▎  | 373/513 [01:19<00:27,  5.09it/s]

🌐 GET deputados/74159
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204498
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  73%|███████▎  | 374/513 [01:19<00:26,  5.28it/s]

🌐 GET deputados/178987
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  73%|███████▎  | 376/513 [01:19<00:25,  5.38it/s]

🌐 GET deputados/73692
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/204441
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  73%|███████▎  | 377/513 [01:19<00:25,  5.28it/s]

🌐 GET deputados/220706
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/160556
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  74%|███████▍  | 380/513 [01:20<00:24,  5.43it/s]

🌐 GET deputados/180214
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/160642
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  74%|███████▍  | 381/513 [01:20<00:24,  5.47it/s]

🌐 GET deputados/204570
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  75%|███████▍  | 383/513 [01:20<00:24,  5.37it/s]

🌐 GET deputados/220615
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET deputados/204553
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  75%|███████▌  | 385/513 [01:21<00:23,  5.51it/s]

🌐 GET deputados/74160
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/171617
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  75%|███████▌  | 387/513 [01:21<00:22,  5.57it/s]

🌐 GET deputados/141518
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/141516
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  76%|███████▌  | 389/513 [01:22<00:22,  5.48it/s]

🌐 GET deputados/220650
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/178860
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  76%|███████▌  | 390/513 [01:22<00:22,  5.43it/s]

🌐 GET deputados/160517
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  76%|███████▌  | 391/513 [01:22<00:24,  4.96it/s]

🌐 GET deputados/160558
⏱ Tempo: 0.24s | 📦 Registros: 1

Deputados Detalhamento:  76%|███████▋  | 392/513 [01:22<00:25,  4.83it/s]

🌐 GET deputados/204492
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/233592
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  77%|███████▋  | 394/513 [01:23<00:24,  4.94it/s]

🌐 GET deputados/220685
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  77%|███████▋  | 396/513 [01:23<00:23,  4.91it/s]

🌐 GET deputados/74574
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/128760
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  78%|███████▊  | 398/513 [01:23<00:22,  5.22it/s]

🌐 GET deputados/74400
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/141488
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  78%|███████▊  | 400/513 [01:24<00:20,  5.42it/s]

🌐 GET deputados/220630
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220667
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  78%|███████▊  | 402/513 [01:25<00:43,  2.56it/s]

🌐 GET deputados/122974
⏱ Tempo: 1.17s | 📦 Registros: 1
🌐 GET deputados/204395
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  79%|███████▉  | 404/513 [01:25<00:30,  3.55it/s]

🌐 GET deputados/122158
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/160604
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  79%|███████▉  | 406/513 [01:26<00:24,  4.39it/s]

🌐 GET deputados/204406
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/161440
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  80%|███████▉  | 408/513 [01:26<00:21,  4.88it/s]

🌐 GET deputados/204524
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/73486
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  80%|███████▉  | 410/513 [01:26<00:20,  5.07it/s]

🌐 GET deputados/160601
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220533
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  80%|████████  | 412/513 [01:27<00:18,  5.38it/s]

🌐 GET deputados/204390
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/221338
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  81%|████████  | 414/513 [01:30<01:18,  1.26it/s]

🌐 GET deputados/160641
⏱ Tempo: 3.12s | 📦 Registros: 1
🌐 GET deputados/220586
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  81%|████████  | 416/513 [01:31<00:49,  1.97it/s]

🌐 GET deputados/233594
⏱ Tempo: 0.28s | 📦 Registros: 1
🌐 GET deputados/220532
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  81%|████████▏ | 418/513 [01:31<00:31,  3.02it/s]

🌐 GET deputados/220626
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204567
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  82%|████████▏ | 420/513 [01:31<00:24,  3.80it/s]

🌐 GET deputados/74084
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/74161
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  82%|████████▏ | 422/513 [01:32<00:20,  4.52it/s]

🌐 GET deputados/220606
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178989
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  83%|████████▎ | 424/513 [01:32<00:17,  5.04it/s]

🌐 GET deputados/153423
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/73801
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  83%|████████▎ | 426/513 [01:32<00:16,  5.37it/s]

🌐 GET deputados/175765
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/235088
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  83%|████████▎ | 428/513 [01:33<00:15,  5.48it/s]

🌐 GET deputados/221329
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/220543
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  84%|████████▍ | 430/513 [01:33<00:15,  5.20it/s]

🌐 GET deputados/73788
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/204362
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  84%|████████▍ | 432/513 [01:33<00:14,  5.50it/s]

🌐 GET deputados/220694
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220633
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  84%|████████▍ | 433/513 [01:34<00:14,  5.39it/s]

🌐 GET deputados/204489
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220693
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  85%|████████▍ | 436/513 [01:34<00:14,  5.46it/s]

🌐 GET deputados/220588
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220613
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  85%|████████▌ | 438/513 [01:35<00:14,  5.28it/s]

🌐 GET deputados/220624
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220546
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  86%|████████▌ | 440/513 [01:35<00:13,  5.38it/s]

🌐 GET deputados/230767
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/141531
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  86%|████████▌ | 442/513 [01:35<00:13,  5.29it/s]

🌐 GET deputados/220641
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/141533
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  87%|████████▋ | 444/513 [01:36<00:12,  5.35it/s]

🌐 GET deputados/165470
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220695
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  87%|████████▋ | 446/513 [01:36<00:12,  5.29it/s]

🌐 GET deputados/204480
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/160629
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  87%|████████▋ | 448/513 [01:36<00:12,  5.39it/s]

🌐 GET deputados/204525
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178945
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  88%|████████▊ | 450/513 [01:37<00:11,  5.61it/s]

🌐 GET deputados/220644
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220620
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  88%|████████▊ | 452/513 [01:37<00:11,  5.35it/s]

🌐 GET deputados/74371
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/178887
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  88%|████████▊ | 454/513 [01:38<00:11,  5.34it/s]

🌐 GET deputados/73604
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/160635
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  89%|████████▉ | 456/513 [01:38<00:10,  5.34it/s]

🌐 GET deputados/204535
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/220631
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  89%|████████▉ | 457/513 [01:38<00:10,  5.52it/s]

🌐 GET deputados/204416
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  89%|████████▉ | 458/513 [01:38<00:11,  4.74it/s]

🌐 GET deputados/160621
⏱ Tempo: 0.28s | 📦 Registros: 1

Deputados Detalhamento:  90%|████████▉ | 460/513 [01:39<00:10,  4.83it/s]

🌐 GET deputados/204387
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET deputados/220621
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  90%|████████▉ | 461/513 [01:39<00:10,  4.96it/s]

🌐 GET deputados/220618
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  90%|█████████ | 462/513 [01:39<00:10,  4.90it/s]

🌐 GET deputados/220713
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  90%|█████████ | 463/513 [01:39<00:10,  4.80it/s]

🌐 GET deputados/226837
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  90%|█████████ | 464/513 [01:40<00:10,  4.49it/s]

🌐 GET deputados/73808
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET deputados/178933
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  91%|█████████ | 467/513 [01:40<00:09,  5.01it/s]

🌐 GET deputados/235776
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/204557
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  91%|█████████ | 468/513 [01:40<00:08,  5.18it/s]

🌐 GET deputados/204360
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  92%|█████████▏| 470/513 [01:41<00:09,  4.66it/s]

🌐 GET deputados/227310
⏱ Tempo: 0.31s | 📦 Registros: 1
🌐 GET deputados/204425
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  92%|█████████▏| 472/513 [01:41<00:08,  4.97it/s]

🌐 GET deputados/220569
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET deputados/220651
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  92%|█████████▏| 474/513 [01:42<00:06,  5.66it/s]

🌐 GET deputados/104552
⏱ Tempo: 0.14s | 📦 Registros: 1
🌐 GET deputados/220643
⏱ Tempo: 0.15s | 📦 Registros: 1

Deputados Detalhamento:  93%|█████████▎| 476/513 [01:42<00:06,  5.60it/s]

🌐 GET deputados/178946
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178947
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  93%|█████████▎| 477/513 [01:42<00:06,  5.58it/s]

🌐 GET deputados/92776
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204534
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  94%|█████████▎| 480/513 [01:43<00:05,  5.68it/s]

🌐 GET deputados/220682
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/204464
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  94%|█████████▍| 482/513 [01:43<00:05,  5.34it/s]

🌐 GET deputados/220598
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220560
⏱ Tempo: 0.20s | 📦 Registros: 1

Deputados Detalhamento:  94%|█████████▍| 483/513 [01:43<00:05,  5.06it/s]

🌐 GET deputados/220597
⏱ Tempo: 0.21s | 📦 Registros: 1

Deputados Detalhamento:  95%|█████████▍| 485/513 [01:44<00:05,  4.88it/s]

🌐 GET deputados/143084
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET deputados/220684
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  95%|█████████▍| 487/513 [01:44<00:05,  5.15it/s]

🌐 GET deputados/160976
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/178934
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  95%|█████████▌| 489/513 [01:45<00:04,  5.32it/s]

🌐 GET deputados/157130
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/160610
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  96%|█████████▌| 491/513 [01:45<00:04,  5.29it/s]

🌐 GET deputados/74376
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/234673
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  96%|█████████▌| 493/513 [01:45<00:03,  5.55it/s]

🌐 GET deputados/235712
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204396
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  96%|█████████▋| 495/513 [01:46<00:03,  4.83it/s]

🌐 GET deputados/137070
⏱ Tempo: 0.28s | 📦 Registros: 1
🌐 GET deputados/141555
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  97%|█████████▋| 497/513 [01:46<00:02,  5.40it/s]

🌐 GET deputados/160591
⏱ Tempo: 0.15s | 📦 Registros: 1
🌐 GET deputados/178992
⏱ Tempo: 0.16s | 📦 Registros: 1

Deputados Detalhamento:  97%|█████████▋| 499/513 [01:46<00:02,  5.36it/s]

🌐 GET deputados/91228
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET deputados/160569
⏱ Tempo: 0.19s | 📦 Registros: 1

Deputados Detalhamento:  98%|█████████▊| 501/513 [01:47<00:02,  5.37it/s]

🌐 GET deputados/160518
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/74043
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  98%|█████████▊| 503/513 [01:47<00:01,  5.55it/s]

🌐 GET deputados/224333
⏱ Tempo: 0.16s | 📦 Registros: 1
🌐 GET deputados/74044
⏱ Tempo: 0.17s | 📦 Registros: 1

Deputados Detalhamento:  98%|█████████▊| 505/513 [01:49<00:03,  2.48it/s]

🌐 GET deputados/220564
⏱ Tempo: 1.23s | 📦 Registros: 1
🌐 GET deputados/230768
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  99%|█████████▉| 507/513 [01:49<00:01,  3.42it/s]

🌐 GET deputados/220536
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/204559
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento:  99%|█████████▉| 509/513 [01:49<00:00,  4.22it/s]

🌐 GET deputados/160632
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220558
⏱ Tempo: 0.18s | 📦 Registros: 1

Deputados Detalhamento: 100%|█████████▉| 511/513 [01:50<00:00,  4.90it/s]

🌐 GET deputados/204517
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/160592
⏱ Tempo: 0.14s | 📦 Registros: 1

Deputados Detalhamento: 100%|██████████| 513/513 [01:50<00:00,  4.64it/s]

🌐 GET deputados/220592
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET deputados/220552
⏱ Tempo: 0.18s | 📦 Registros: 1

In [20]:
loader.save_bronze(
    df_deputadosDetalhamento,
    dataset='deputados_detalhamento',
    layer='bronze'
    )

💾 Salvo em: data/bronze/deputados_detalhamento/deputados_detalhamento.parquet

In [21]:
dataset='deputados_detalhamento'
path = f"data/bronze/{dataset}/{dataset}.parquet"

df_deputadosDetalhamento = pd.read_parquet(path)

In [23]:
# Extração de frentes dos deputados

df_deputadosFrentes = extractor.extract_by_ids(
    ids=ids_deputados, 
    endpoint_template='deputados/{id}/frentes',
    desc='Frentes dos deputados')

Frentes dos deputados:   0%|          | 1/513 [00:00<01:31,  5.59it/s]

🌐 GET deputados/204379/frentes
⏱ Tempo: 0.17s | 📦 Registros: 207

Frentes dos deputados:   1%|          | 3/513 [00:00<01:41,  5.01it/s]

🌐 GET deputados/220714/frentes
⏱ Tempo: 0.22s | 📦 Registros: 182
🌐 GET deputados/221328/frentes
⏱ Tempo: 0.19s | 📦 Registros: 101

Frentes dos deputados:   1%|          | 4/513 [00:00<01:44,  4.85it/s]

🌐 GET deputados/204560/frentes
⏱ Tempo: 0.21s | 📦 Registros: 230
🌐 GET deputados/204528/frentes
⏱ Tempo: 0.20s | 📦 Registros: 272

Frentes dos deputados:   1%|          | 6/513 [00:01<01:43,  4.89it/s]

🌐 GET deputados/121948/frentes
⏱ Tempo: 0.20s | 📦 Registros: 289

Frentes dos deputados:   1%|▏         | 7/513 [00:01<01:45,  4.82it/s]

🌐 GET deputados/74646/frentes
⏱ Tempo: 0.21s | 📦 Registros: 54

Frentes dos deputados:   2%|▏         | 8/513 [00:01<01:48,  4.66it/s]

🌐 GET deputados/160508/frentes
⏱ Tempo: 0.23s | 📦 Registros: 301
🌐 GET deputados/136811/frentes
⏱ Tempo: 0.21s | 📦 Registros: 667

Frentes dos deputados:   2%|▏         | 11/513 [00:02<01:39,  5.03it/s]

🌐 GET deputados/178835/frentes
⏱ Tempo: 0.17s | 📦 Registros: 303
🌐 GET deputados/160527/frentes
⏱ Tempo: 0.19s | 📦 Registros: 387

Frentes dos deputados:   3%|▎         | 13/513 [00:02<01:40,  4.96it/s]

🌐 GET deputados/204495/frentes
⏱ Tempo: 0.21s | 📦 Registros: 358
🌐 GET deputados/204549/frentes
⏱ Tempo: 0.19s | 📦 Registros: 122

Frentes dos deputados:   3%|▎         | 15/513 [00:03<01:43,  4.82it/s]

🌐 GET deputados/73579/frentes
⏱ Tempo: 0.23s | 📦 Registros: 443
🌐 GET deputados/220538/frentes
⏱ Tempo: 0.19s | 📦 Registros: 201

Frentes dos deputados:   3%|▎         | 17/513 [00:03<01:42,  4.86it/s]

🌐 GET deputados/160559/frentes
⏱ Tempo: 0.22s | 📦 Registros: 580
🌐 GET deputados/204501/frentes
⏱ Tempo: 0.19s | 📦 Registros: 306

Frentes dos deputados:   4%|▎         | 19/513 [00:03<01:34,  5.22it/s]

🌐 GET deputados/178972/frentes
⏱ Tempo: 0.19s | 📦 Registros: 338
🌐 GET deputados/220542/frentes
⏱ Tempo: 0.16s | 📦 Registros: 165

Frentes dos deputados:   4%|▍         | 20/513 [00:04<01:43,  4.77it/s]

🌐 GET deputados/160545/frentes
⏱ Tempo: 0.24s | 📦 Registros: 528

Frentes dos deputados:   4%|▍         | 21/513 [00:04<01:44,  4.73it/s]

🌐 GET deputados/220554/frentes
⏱ Tempo: 0.21s | 📦 Registros: 173

Frentes dos deputados:   4%|▍         | 22/513 [00:04<01:45,  4.63it/s]

🌐 GET deputados/221148/frentes
⏱ Tempo: 0.22s | 📦 Registros: 134

Frentes dos deputados:   4%|▍         | 23/513 [00:04<01:44,  4.69it/s]

🌐 GET deputados/220576/frentes
⏱ Tempo: 0.20s | 📦 Registros: 92

Frentes dos deputados:   5%|▍         | 24/513 [00:05<01:54,  4.26it/s]

🌐 GET deputados/74057/frentes
⏱ Tempo: 0.28s | 📦 Registros: 603

Frentes dos deputados:   5%|▌         | 26/513 [00:05<01:43,  4.69it/s]

🌐 GET deputados/178927/frentes
⏱ Tempo: 0.22s | 📦 Registros: 575
🌐 GET deputados/204353/frentes
⏱ Tempo: 0.17s | 📦 Registros: 125

Frentes dos deputados:   5%|▌         | 27/513 [00:05<01:43,  4.67it/s]

🌐 GET deputados/178937/frentes
⏱ Tempo: 0.21s | 📦 Registros: 384

Frentes dos deputados:   6%|▌         | 29/513 [00:06<01:40,  4.84it/s]

🌐 GET deputados/178881/frentes
⏱ Tempo: 0.23s | 📦 Registros: 502
🌐 GET deputados/220707/frentes
⏱ Tempo: 0.17s | 📦 Registros: 214

Frentes dos deputados:   6%|▌         | 31/513 [00:06<01:34,  5.09it/s]

🌐 GET deputados/204356/frentes
⏱ Tempo: 0.18s | 📦 Registros: 264
🌐 GET deputados/220715/frentes
⏱ Tempo: 0.19s | 📦 Registros: 138

Frentes dos deputados:   6%|▋         | 33/513 [00:06<01:32,  5.18it/s]

🌐 GET deputados/107970/frentes
⏱ Tempo: 0.18s | 📦 Registros: 112
🌐 GET deputados/220556/frentes
⏱ Tempo: 0.18s | 📦 Registros: 114

Frentes dos deputados:   7%|▋         | 34/513 [00:07<01:32,  5.17it/s]

🌐 GET deputados/220632/frentes
⏱ Tempo: 0.19s | 📦 Registros: 106

Frentes dos deputados:   7%|▋         | 36/513 [00:07<01:37,  4.87it/s]

🌐 GET deputados/178831/frentes
⏱ Tempo: 0.29s | 📦 Registros: 502
🌐 GET deputados/220657/frentes
⏱ Tempo: 0.16s | 📦 Registros: 69

Frentes dos deputados:   7%|▋         | 37/513 [00:07<01:35,  4.99it/s]

🌐 GET deputados/204423/frentes
⏱ Tempo: 0.19s | 📦 Registros: 345
🌐 GET deputados/133439/frentes
⏱ Tempo: 0.21s | 📦 Registros: 660

Frentes dos deputados:   8%|▊         | 39/513 [00:08<01:36,  4.90it/s]

🌐 GET deputados/178882/frentes
⏱ Tempo: 0.20s | 📦 Registros: 186
🌐 GET deputados/204515/frentes
⏱ Tempo: 0.20s | 📦 Registros: 283

Frentes dos deputados:   8%|▊         | 42/513 [00:08<01:33,  5.04it/s]

🌐 GET deputados/220676/frentes
⏱ Tempo: 0.21s | 📦 Registros: 179
🌐 GET deputados/123756/frentes
⏱ Tempo: 0.17s | 📦 Registros: 204

Frentes dos deputados:   8%|▊         | 43/513 [00:08<01:37,  4.81it/s]

🌐 GET deputados/220544/frentes
⏱ Tempo: 0.22s | 📦 Registros: 42

Frentes dos deputados:   9%|▊         | 44/513 [00:09<01:44,  4.50it/s]

🌐 GET deputados/160553/frentes
⏱ Tempo: 0.25s | 📦 Registros: 457

Frentes dos deputados:   9%|▉         | 46/513 [00:09<01:37,  4.79it/s]

🌐 GET deputados/220638/frentes
⏱ Tempo: 0.22s | 📦 Registros: 123
🌐 GET deputados/220675/frentes
⏱ Tempo: 0.17s | 📦 Registros: 53

Frentes dos deputados:   9%|▉         | 48/513 [00:12<08:23,  1.08s/it]

🌐 GET deputados/220549/frentes
⏱ Tempo: 0.21s | 📦 Registros: 168
🌐 GET deputados/73433/frentes
⏱ Tempo: 3.12s | 📦 Registros: 177

Frentes dos deputados:  10%|▉         | 50/513 [00:13<04:51,  1.59it/s]

🌐 GET deputados/141391/frentes
⏱ Tempo: 0.20s | 📦 Registros: 380
🌐 GET deputados/160541/frentes
⏱ Tempo: 0.18s | 📦 Registros: 286

Frentes dos deputados:  10%|█         | 52/513 [00:13<03:10,  2.41it/s]

🌐 GET deputados/160600/frentes
⏱ Tempo: 0.24s | 📦 Registros: 621
🌐 GET deputados/74090/frentes
⏱ Tempo: 0.17s | 📦 Registros: 343

Frentes dos deputados:  10%|█         | 53/513 [00:13<02:39,  2.88it/s]

🌐 GET deputados/123086/frentes
⏱ Tempo: 0.18s | 📦 Registros: 48

Frentes dos deputados:  11%|█         | 54/513 [00:14<02:25,  3.15it/s]

🌐 GET deputados/160665/frentes
⏱ Tempo: 0.24s | 📦 Registros: 701

Frentes dos deputados:  11%|█         | 55/513 [00:14<02:14,  3.40it/s]

🌐 GET deputados/160512/frentes
⏱ Tempo: 0.24s | 📦 Registros: 775

Frentes dos deputados:  11%|█         | 57/513 [00:14<01:53,  4.02it/s]

🌐 GET deputados/69871/frentes
⏱ Tempo: 0.22s | 📦 Registros: 593
🌐 GET deputados/178975/frentes
⏱ Tempo: 0.18s | 📦 Registros: 159

Frentes dos deputados:  12%|█▏        | 59/513 [00:15<01:36,  4.69it/s]

🌐 GET deputados/220605/frentes
⏱ Tempo: 0.19s | 📦 Registros: 216
🌐 GET deputados/220612/frentes
⏱ Tempo: 0.17s | 📦 Registros: 188

Frentes dos deputados:  12%|█▏        | 60/513 [00:15<01:32,  4.91it/s]

🌐 GET deputados/73701/frentes
⏱ Tempo: 0.18s | 📦 Registros: 427

Frentes dos deputados:  12%|█▏        | 61/513 [00:15<01:35,  4.72it/s]

🌐 GET deputados/109429/frentes
⏱ Tempo: 0.22s | 📦 Registros: 209

Frentes dos deputados:  12%|█▏        | 62/513 [00:15<01:38,  4.57it/s]

🌐 GET deputados/204358/frentes
⏱ Tempo: 0.23s | 📦 Registros: 112

Frentes dos deputados:  12%|█▏        | 63/513 [00:16<01:42,  4.39it/s]

🌐 GET deputados/220698/frentes
⏱ Tempo: 0.24s | 📦 Registros: 56

Frentes dos deputados:  13%|█▎        | 65/513 [00:16<01:34,  4.77it/s]

🌐 GET deputados/220683/frentes
⏱ Tempo: 0.21s | 📦 Registros: 161
🌐 GET deputados/204374/frentes
⏱ Tempo: 0.17s | 📦 Registros: 251

Frentes dos deputados:  13%|█▎        | 66/513 [00:16<01:32,  4.85it/s]

🌐 GET deputados/204388/frentes
⏱ Tempo: 0.19s | 📦 Registros: 412

Frentes dos deputados:  13%|█▎        | 67/513 [00:16<01:32,  4.82it/s]

🌐 GET deputados/160538/frentes
⏱ Tempo: 0.21s | 📦 Registros: 426
🌐 GET deputados/210989/frentes
⏱ Tempo: 0.20s | 📦 Registros: 188

Frentes dos deputados:  13%|█▎        | 69/513 [00:17<01:28,  5.01it/s]

🌐 GET deputados/220635/frentes
⏱ Tempo: 0.18s | 📦 Registros: 51
🌐 GET deputados/220574/frentes
⏱ Tempo: 0.20s | 📦 Registros: 203

Frentes dos deputados:  14%|█▍        | 71/513 [00:17<01:28,  4.98it/s]

🌐 GET deputados/220548/frentes
⏱ Tempo: 0.19s | 📦 Registros: 192

Frentes dos deputados:  14%|█▍        | 73/513 [00:18<01:29,  4.93it/s]

🌐 GET deputados/204572/frentes
⏱ Tempo: 0.22s | 📦 Registros: 425
🌐 GET deputados/220690/frentes
⏱ Tempo: 0.19s | 📦 Registros: 106

Frentes dos deputados:  15%|█▍        | 75/513 [00:18<01:29,  4.88it/s]

🌐 GET deputados/178829/frentes
⏱ Tempo: 0.25s | 📦 Registros: 427
🌐 GET deputados/213762/frentes
⏱ Tempo: 0.17s | 📦 Registros: 21

Frentes dos deputados:  15%|█▍        | 76/513 [00:18<01:28,  4.95it/s]

🌐 GET deputados/204361/frentes
⏱ Tempo: 0.19s | 📦 Registros: 363

Frentes dos deputados:  15%|█▌        | 77/513 [00:18<01:30,  4.84it/s]

🌐 GET deputados/178962/frentes
⏱ Tempo: 0.21s | 📦 Registros: 495

Frentes dos deputados:  15%|█▌        | 78/513 [00:19<01:32,  4.71it/s]

🌐 GET deputados/178993/frentes
⏱ Tempo: 0.22s | 📦 Registros: 818

Frentes dos deputados:  15%|█▌        | 79/513 [00:19<02:02,  3.54it/s]

🌐 GET deputados/204460/frentes
⏱ Tempo: 0.44s | 📦 Registros: 185

Frentes dos deputados:  16%|█▌        | 81/513 [00:20<01:44,  4.13it/s]

🌐 GET deputados/74262/frentes
⏱ Tempo: 0.23s | 📦 Registros: 98
🌐 GET deputados/204426/frentes
⏱ Tempo: 0.18s | 📦 Registros: 294

Frentes dos deputados:  16%|█▌        | 83/513 [00:20<01:36,  4.45it/s]

🌐 GET deputados/141398/frentes
⏱ Tempo: 0.22s | 📦 Registros: 561
🌐 GET deputados/220704/frentes
⏱ Tempo: 0.19s | 📦 Registros: 157

Frentes dos deputados:  17%|█▋        | 85/513 [00:20<01:30,  4.73it/s]

🌐 GET deputados/204369/frentes
⏱ Tempo: 0.21s | 📦 Registros: 118
🌐 GET deputados/220699/frentes
⏱ Tempo: 0.18s | 📦 Registros: 26

Frentes dos deputados:  17%|█▋        | 86/513 [00:21<01:27,  4.89it/s]

🌐 GET deputados/206018/frentes
⏱ Tempo: 0.18s | 📦 Registros: 116

Frentes dos deputados:  17%|█▋        | 88/513 [00:21<01:33,  4.56it/s]

🌐 GET deputados/178876/frentes
⏱ Tempo: 0.28s | 📦 Registros: 651
🌐 GET deputados/204488/frentes
⏱ Tempo: 0.19s | 📦 Registros: 314

Frentes dos deputados:  17%|█▋        | 89/513 [00:21<01:40,  4.22it/s]

🌐 GET deputados/73441/frentes
⏱ Tempo: 0.27s | 📦 Registros: 506

Frentes dos deputados:  18%|█▊        | 90/513 [00:22<01:45,  4.02it/s]

🌐 GET deputados/204496/frentes
⏱ Tempo: 0.27s | 📦 Registros: 269

Frentes dos deputados:  18%|█▊        | 92/513 [00:22<01:36,  4.35it/s]

🌐 GET deputados/204504/frentes
⏱ Tempo: 0.24s | 📦 Registros: 269
🌐 GET deputados/205476/frentes
⏱ Tempo: 0.18s | 📦 Registros: 234

Frentes dos deputados:  18%|█▊        | 94/513 [00:23<01:54,  3.67it/s]

🌐 GET deputados/74171/frentes
⏱ Tempo: 0.49s | 📦 Registros: 310
🌐 GET deputados/204462/frentes
⏱ Tempo: 0.18s | 📦 Registros: 141

Frentes dos deputados:  19%|█▊        | 95/513 [00:23<01:48,  3.85it/s]

🌐 GET deputados/220665/frentes
⏱ Tempo: 0.22s | 📦 Registros: 50

Frentes dos deputados:  19%|█▊        | 96/513 [00:23<01:44,  3.98it/s]

🌐 GET deputados/74537/frentes
⏱ Tempo: 0.23s | 📦 Registros: 202

Frentes dos deputados:  19%|█▉        | 97/513 [00:23<01:44,  3.97it/s]

🌐 GET deputados/141408/frentes
⏱ Tempo: 0.25s | 📦 Registros: 904

Frentes dos deputados:  19%|█▉        | 98/513 [00:24<01:39,  4.17it/s]

🌐 GET deputados/88256/frentes
⏱ Tempo: 0.20s | 📦 Registros: 100

Frentes dos deputados:  19%|█▉        | 99/513 [00:24<01:37,  4.23it/s]

🌐 GET deputados/98148/frentes
⏱ Tempo: 0.22s | 📦 Registros: 169

Frentes dos deputados:  19%|█▉        | 100/513 [00:24<01:36,  4.29it/s]

🌐 GET deputados/220594/frentes
⏱ Tempo: 0.22s | 📦 Registros: 112
🌐 GET deputados/204378/frentes
⏱ Tempo: 0.20s | 📦 Registros: 293

Frentes dos deputados:  20%|█▉        | 102/513 [00:24<01:27,  4.67it/s]

🌐 GET deputados/220595/frentes
⏱ Tempo: 0.18s | 📦 Registros: 197

Frentes dos deputados:  20%|██        | 103/513 [00:25<01:32,  4.43it/s]

🌐 GET deputados/220666/frentes
⏱ Tempo: 0.25s | 📦 Registros: 152

Frentes dos deputados:  20%|██        | 105/513 [00:25<01:30,  4.53it/s]

🌐 GET deputados/220590/frentes
⏱ Tempo: 0.24s | 📦 Registros: 183
🌐 GET deputados/220608/frentes
⏱ Tempo: 0.19s | 📦 Registros: 211

Frentes dos deputados:  21%|██        | 106/513 [00:25<01:27,  4.64it/s]

🌐 GET deputados/204355/frentes
⏱ Tempo: 0.20s | 📦 Registros: 358

Frentes dos deputados:  21%|██        | 108/513 [00:26<01:24,  4.81it/s]

🌐 GET deputados/141411/frentes
⏱ Tempo: 0.24s | 📦 Registros: 494
🌐 GET deputados/220555/frentes
⏱ Tempo: 0.17s | 📦 Registros: 63

Frentes dos deputados:  21%|██        | 109/513 [00:26<01:23,  4.87it/s]

🌐 GET deputados/220692/frentes
⏱ Tempo: 0.19s | 📦 Registros: 125

Frentes dos deputados:  21%|██▏       | 110/513 [00:26<01:30,  4.46it/s]

🌐 GET deputados/74467/frentes
⏱ Tempo: 0.26s | 📦 Registros: 716
🌐 GET deputados/220629/frentes
⏱ Tempo: 0.20s | 📦 Registros: 70

Frentes dos deputados:  22%|██▏       | 113/513 [00:27<01:28,  4.52it/s]

🌐 GET deputados/220603/frentes
⏱ Tempo: 0.28s | 📦 Registros: 76
🌐 GET deputados/220571/frentes
⏱ Tempo: 0.17s | 📦 Registros: 133

Frentes dos deputados:  22%|██▏       | 115/513 [00:27<01:25,  4.68it/s]

🌐 GET deputados/74060/frentes
⏱ Tempo: 0.25s | 📦 Registros: 825
🌐 GET deputados/220582/frentes
⏱ Tempo: 0.17s | 📦 Registros: 29

Frentes dos deputados:  23%|██▎       | 116/513 [00:28<01:23,  4.77it/s]

🌐 GET deputados/204367/frentes
⏱ Tempo: 0.19s | 📦 Registros: 250

Frentes dos deputados:  23%|██▎       | 118/513 [00:28<01:21,  4.84it/s]

🌐 GET deputados/204409/frentes
⏱ Tempo: 0.22s | 📦 Registros: 141
🌐 GET deputados/204459/frentes
⏱ Tempo: 0.18s | 📦 Registros: 118

Frentes dos deputados:  23%|██▎       | 119/513 [00:28<01:18,  5.01it/s]

🌐 GET deputados/220557/frentes
⏱ Tempo: 0.18s | 📦 Registros: 82

Frentes dos deputados:  24%|██▎       | 121/513 [00:29<01:20,  4.87it/s]

🌐 GET deputados/62881/frentes
⏱ Tempo: 0.24s | 📦 Registros: 549
🌐 GET deputados/160552/frentes
⏱ Tempo: 0.18s | 📦 Registros: 112

Frentes dos deputados:  24%|██▍       | 123/513 [00:29<01:18,  4.98it/s]

🌐 GET deputados/204511/frentes
⏱ Tempo: 0.22s | 📦 Registros: 248
🌐 GET deputados/220539/frentes
⏱ Tempo: 0.17s | 📦 Registros: 222

Frentes dos deputados:  24%|██▍       | 124/513 [00:29<01:17,  5.01it/s]

🌐 GET deputados/220565/frentes
⏱ Tempo: 0.19s | 📦 Registros: 82

Frentes dos deputados:  24%|██▍       | 125/513 [00:29<01:20,  4.83it/s]

🌐 GET deputados/220625/frentes
⏱ Tempo: 0.22s | 📦 Registros: 242

Frentes dos deputados:  25%|██▍       | 127/513 [00:30<01:20,  4.80it/s]

🌐 GET deputados/220561/frentes
⏱ Tempo: 0.24s | 📦 Registros: 77
🌐 GET deputados/220642/frentes
⏱ Tempo: 0.18s | 📦 Registros: 15

Frentes dos deputados:  25%|██▍       | 128/513 [00:30<01:22,  4.68it/s]

🌐 GET deputados/220673/frentes
⏱ Tempo: 0.22s | 📦 Registros: 72

Frentes dos deputados:  25%|██▌       | 129/513 [00:30<01:25,  4.49it/s]

🌐 GET deputados/220649/frentes
⏱ Tempo: 0.24s | 📦 Registros: 85

Frentes dos deputados:  25%|██▌       | 130/513 [00:31<01:26,  4.42it/s]

🌐 GET deputados/178908/frentes
⏱ Tempo: 0.23s | 📦 Registros: 524
🌐 GET deputados/220583/frentes
⏱ Tempo: 0.20s | 📦 Registros: 82

Frentes dos deputados:  26%|██▌       | 133/513 [00:31<01:18,  4.87it/s]

🌐 GET deputados/204512/frentes
⏱ Tempo: 0.18s | 📦 Registros: 233
🌐 GET deputados/220701/frentes
⏱ Tempo: 0.19s | 📦 Registros: 49

Frentes dos deputados:  26%|██▋       | 135/513 [00:32<01:17,  4.86it/s]

🌐 GET deputados/220652/frentes
⏱ Tempo: 0.25s | 📦 Registros: 46
🌐 GET deputados/220654/frentes
⏱ Tempo: 0.16s | 📦 Registros: 105

Frentes dos deputados:  27%|██▋       | 136/513 [00:32<01:16,  4.95it/s]

🌐 GET deputados/220553/frentes
⏱ Tempo: 0.19s | 📦 Registros: 140

Frentes dos deputados:  27%|██▋       | 137/513 [00:32<01:19,  4.76it/s]

🌐 GET deputados/160588/frentes
⏱ Tempo: 0.22s | 📦 Registros: 489

Frentes dos deputados:  27%|██▋       | 138/513 [00:32<01:21,  4.60it/s]

🌐 GET deputados/220691/frentes
⏱ Tempo: 0.23s | 📦 Registros: 192

Frentes dos deputados:  27%|██▋       | 140/513 [00:33<01:18,  4.76it/s]

🌐 GET deputados/178929/frentes
⏱ Tempo: 0.21s | 📦 Registros: 678
🌐 GET deputados/73768/frentes
⏱ Tempo: 0.19s | 📦 Registros: 125

Frentes dos deputados:  27%|██▋       | 141/513 [00:33<01:18,  4.76it/s]

🌐 GET deputados/220671/frentes
⏱ Tempo: 0.20s | 📦 Registros: 27

Frentes dos deputados:  28%|██▊       | 143/513 [00:33<01:14,  4.94it/s]

🌐 GET deputados/160599/frentes
⏱ Tempo: 0.21s | 📦 Registros: 154
🌐 GET deputados/220602/frentes
⏱ Tempo: 0.17s | 📦 Registros: 168

Frentes dos deputados:  28%|██▊       | 144/513 [00:33<01:18,  4.71it/s]

🌐 GET deputados/143632/frentes
⏱ Tempo: 0.23s | 📦 Registros: 550

Frentes dos deputados:  28%|██▊       | 146/513 [00:34<01:17,  4.75it/s]

🌐 GET deputados/160758/frentes
⏱ Tempo: 0.24s | 📦 Registros: 764
🌐 GET deputados/220573/frentes
⏱ Tempo: 0.18s | 📦 Registros: 209

Frentes dos deputados:  29%|██▉       | 148/513 [00:34<01:15,  4.86it/s]

🌐 GET deputados/204450/frentes
⏱ Tempo: 0.20s | 📦 Registros: 129
🌐 GET deputados/227991/frentes
⏱ Tempo: 0.19s | 📦 Registros: 2

Frentes dos deputados:  29%|██▉       | 149/513 [00:34<01:15,  4.80it/s]

🌐 GET deputados/220614/frentes
⏱ Tempo: 0.20s | 📦 Registros: 119

Frentes dos deputados:  29%|██▉       | 150/513 [00:35<01:26,  4.21it/s]

🌐 GET deputados/220610/frentes
⏱ Tempo: 0.30s | 📦 Registros: 228

Frentes dos deputados:  29%|██▉       | 151/513 [00:35<01:24,  4.27it/s]

🌐 GET deputados/220688/frentes
⏱ Tempo: 0.22s | 📦 Registros: 93

Frentes dos deputados:  30%|██▉       | 152/513 [00:35<01:27,  4.10it/s]

🌐 GET deputados/204518/frentes
⏱ Tempo: 0.26s | 📦 Registros: 335

Frentes dos deputados:  30%|███       | 154/513 [00:36<01:20,  4.44it/s]

🌐 GET deputados/220570/frentes
⏱ Tempo: 0.22s | 📦 Registros: 59
🌐 GET deputados/204481/frentes
⏱ Tempo: 0.19s | 📦 Registros: 118

Frentes dos deputados:  30%|███       | 155/513 [00:36<01:22,  4.35it/s]

🌐 GET deputados/204351/frentes
⏱ Tempo: 0.24s | 📦 Registros: 387
🌐 GET deputados/220528/frentes
⏱ Tempo: 0.20s | 📦 Registros: 125

Frentes dos deputados:  31%|███       | 157/513 [00:36<01:16,  4.64it/s]

🌐 GET deputados/204412/frentes
⏱ Tempo: 0.20s | 📦 Registros: 325
🌐 GET deputados/220674/frentes
⏱ Tempo: 0.20s | 📦 Registros: 79

Frentes dos deputados:  31%|███       | 160/513 [00:37<01:10,  4.99it/s]

🌐 GET deputados/220686/frentes
⏱ Tempo: 0.19s | 📦 Registros: 160
🌐 GET deputados/220540/frentes
⏱ Tempo: 0.17s | 📦 Registros: 115

Frentes dos deputados:  31%|███▏      | 161/513 [00:37<01:11,  4.92it/s]

🌐 GET deputados/220623/frentes
⏱ Tempo: 0.20s | 📦 Registros: 77

Frentes dos deputados:  32%|███▏      | 162/513 [00:37<01:13,  4.75it/s]

🌐 GET deputados/204541/frentes
⏱ Tempo: 0.22s | 📦 Registros: 320

Frentes dos deputados:  32%|███▏      | 163/513 [00:38<01:16,  4.60it/s]

🌐 GET deputados/141421/frentes
⏱ Tempo: 0.23s | 📦 Registros: 500

Frentes dos deputados:  32%|███▏      | 164/513 [00:38<01:14,  4.68it/s]

🌐 GET deputados/220589/frentes
⏱ Tempo: 0.20s | 📦 Registros: 209

Frentes dos deputados:  32%|███▏      | 165/513 [00:38<01:14,  4.65it/s]

🌐 GET deputados/74075/frentes
⏱ Tempo: 0.21s | 📦 Registros: 268

Frentes dos deputados:  32%|███▏      | 166/513 [00:38<01:13,  4.69it/s]

🌐 GET deputados/204364/frentes
⏱ Tempo: 0.20s | 📦 Registros: 180

Frentes dos deputados:  33%|███▎      | 168/513 [00:39<01:08,  5.02it/s]

🌐 GET deputados/178854/frentes
⏱ Tempo: 0.20s | 📦 Registros: 137
🌐 GET deputados/198783/frentes
⏱ Tempo: 0.17s | 📦 Registros: 353

Frentes dos deputados:  33%|███▎      | 170/513 [00:39<01:04,  5.28it/s]

🌐 GET deputados/161550/frentes
⏱ Tempo: 0.18s | 📦 Registros: 322
🌐 GET deputados/230765/frentes
⏱ Tempo: 0.18s | 📦 Registros: 11

Frentes dos deputados:  33%|███▎      | 171/513 [00:39<01:03,  5.37it/s]

🌐 GET deputados/220663/frentes
⏱ Tempo: 0.18s | 📦 Registros: 177

Frentes dos deputados:  34%|███▎      | 172/513 [00:39<01:07,  5.04it/s]

🌐 GET deputados/220645/frentes
⏱ Tempo: 0.22s | 📦 Registros: 142
🌐 GET deputados/160575/frentes
⏱ Tempo: 0.20s | 📦 Registros: 640

Frentes dos deputados:  34%|███▍      | 174/513 [00:40<01:14,  4.54it/s]

🌐 GET deputados/160640/frentes
⏱ Tempo: 0.26s | 📦 Registros: 774

Frentes dos deputados:  34%|███▍      | 175/513 [00:40<01:26,  3.91it/s]

🌐 GET deputados/74454/frentes
⏱ Tempo: 0.33s | 📦 Registros: 31

Frentes dos deputados:  34%|███▍      | 176/513 [00:41<01:49,  3.07it/s]

🌐 GET deputados/178871/frentes
⏱ Tempo: 0.48s | 📦 Registros: 701

Frentes dos deputados:  35%|███▍      | 178/513 [00:41<01:28,  3.80it/s]

🌐 GET deputados/178905/frentes
⏱ Tempo: 0.21s | 📦 Registros: 272
🌐 GET deputados/220681/frentes
⏱ Tempo: 0.18s | 📦 Registros: 4

Frentes dos deputados:  35%|███▌      | 180/513 [00:42<01:20,  4.16it/s]

🌐 GET deputados/171623/frentes
⏱ Tempo: 0.25s | 📦 Registros: 397
🌐 GET deputados/204368/frentes
⏱ Tempo: 0.19s | 📦 Registros: 132

Frentes dos deputados:  35%|███▌      | 182/513 [00:42<01:13,  4.52it/s]

🌐 GET deputados/220653/frentes
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET deputados/220712/frentes
⏱ Tempo: 0.20s | 📦 Registros: 193

Frentes dos deputados:  36%|███▌      | 184/513 [00:42<01:08,  4.84it/s]

🌐 GET deputados/66828/frentes
⏱ Tempo: 0.19s | 📦 Registros: 570
🌐 GET deputados/220646/frentes
⏱ Tempo: 0.19s | 📦 Registros: 252

Frentes dos deputados:  36%|███▋      | 186/513 [00:43<01:02,  5.23it/s]

🌐 GET deputados/72442/frentes
⏱ Tempo: 0.17s | 📦 Registros: 288
🌐 GET deputados/204398/frentes
⏱ Tempo: 0.17s | 📦 Registros: 315

Frentes dos deputados:  37%|███▋      | 188/513 [00:43<01:04,  5.05it/s]

🌐 GET deputados/160666/frentes
⏱ Tempo: 0.22s | 📦 Registros: 706
🌐 GET deputados/204407/frentes
⏱ Tempo: 0.19s | 📦 Registros: 164

Frentes dos deputados:  37%|███▋      | 189/513 [00:43<01:03,  5.10it/s]

🌐 GET deputados/220656/frentes
⏱ Tempo: 0.19s | 📦 Registros: 248

Frentes dos deputados:  37%|███▋      | 191/513 [00:44<01:04,  5.00it/s]

🌐 GET deputados/141431/frentes
⏱ Tempo: 0.23s | 📦 Registros: 452
🌐 GET deputados/204445/frentes
⏱ Tempo: 0.18s | 📦 Registros: 54

Frentes dos deputados:  37%|███▋      | 192/513 [00:44<01:11,  4.48it/s]

🌐 GET deputados/92699/frentes
⏱ Tempo: 0.27s | 📦 Registros: 235

Frentes dos deputados:  38%|███▊      | 193/513 [00:44<01:10,  4.54it/s]

🌐 GET deputados/204427/frentes
⏱ Tempo: 0.21s | 📦 Registros: 354

Frentes dos deputados:  38%|███▊      | 194/513 [00:44<01:10,  4.49it/s]

🌐 GET deputados/204411/frentes
⏱ Tempo: 0.22s | 📦 Registros: 65

Frentes dos deputados:  38%|███▊      | 195/513 [00:48<05:49,  1.10s/it]

🌐 GET deputados/220545/frentes
⏱ Tempo: 3.14s | 📦 Registros: 117

Frentes dos deputados:  38%|███▊      | 197/513 [00:48<03:26,  1.53it/s]

🌐 GET deputados/160598/frentes
⏱ Tempo: 0.28s | 📦 Registros: 664
🌐 GET deputados/191923/frentes
⏱ Tempo: 0.18s | 📦 Registros: 202

Frentes dos deputados:  39%|███▉      | 199/513 [00:48<02:12,  2.37it/s]

🌐 GET deputados/220700/frentes
⏱ Tempo: 0.19s | 📦 Registros: 135
🌐 GET deputados/220551/frentes
⏱ Tempo: 0.19s | 📦 Registros: 81

Frentes dos deputados:  39%|███▉      | 201/513 [00:49<01:34,  3.29it/s]

🌐 GET deputados/204494/frentes
⏱ Tempo: 0.19s | 📦 Registros: 347
🌐 GET deputados/220534/frentes
⏱ Tempo: 0.18s | 📦 Registros: 226

Frentes dos deputados:  39%|███▉      | 202/513 [00:49<01:26,  3.61it/s]

🌐 GET deputados/224117/frentes
⏱ Tempo: 0.21s | 📦 Registros: 51

Frentes dos deputados:  40%|███▉      | 203/513 [00:49<01:19,  3.90it/s]

🌐 GET deputados/220708/frentes
⏱ Tempo: 0.20s | 📦 Registros: 33

Frentes dos deputados:  40%|███▉      | 204/513 [00:49<01:14,  4.14it/s]

🌐 GET deputados/204473/frentes
⏱ Tempo: 0.20s | 📦 Registros: 257

Frentes dos deputados:  40%|███▉      | 205/513 [00:50<01:12,  4.27it/s]

🌐 GET deputados/220611/frentes
⏱ Tempo: 0.21s | 📦 Registros: 112

Frentes dos deputados:  40%|████      | 207/513 [00:50<01:07,  4.56it/s]

🌐 GET deputados/178966/frentes
⏱ Tempo: 0.23s | 📦 Registros: 380
🌐 GET deputados/220702/frentes
⏱ Tempo: 0.18s | 📦 Registros: 165

Frentes dos deputados:  41%|████      | 209/513 [00:51<01:25,  3.57it/s]

🌐 GET deputados/74374/frentes
⏱ Tempo: 0.54s | 📦 Registros: 425
🌐 GET deputados/204394/frentes
⏱ Tempo: 0.19s | 📦 Registros: 97

Frentes dos deputados:  41%|████      | 211/513 [00:51<01:13,  4.10it/s]

🌐 GET deputados/74383/frentes
⏱ Tempo: 0.23s | 📦 Registros: 331
🌐 GET deputados/204491/frentes
⏱ Tempo: 0.19s | 📦 Registros: 473

Frentes dos deputados:  41%|████▏     | 212/513 [00:51<01:10,  4.28it/s]

🌐 GET deputados/74270/frentes
⏱ Tempo: 0.21s | 📦 Registros: 659

Frentes dos deputados:  42%|████▏     | 213/513 [00:52<01:08,  4.35it/s]

🌐 GET deputados/220529/frentes
⏱ Tempo: 0.22s | 📦 Registros: 215

Frentes dos deputados:  42%|████▏     | 214/513 [00:52<01:16,  3.89it/s]

🌐 GET deputados/204365/frentes
⏱ Tempo: 0.31s | 📦 Registros: 110

Frentes dos deputados:  42%|████▏     | 215/513 [00:52<01:14,  4.00it/s]

🌐 GET deputados/220526/frentes
⏱ Tempo: 0.23s | 📦 Registros: 48

Frentes dos deputados:  42%|████▏     | 216/513 [00:53<01:16,  3.88it/s]

🌐 GET deputados/160673/frentes
⏱ Tempo: 0.27s | 📦 Registros: 508

Frentes dos deputados:  42%|████▏     | 217/513 [00:53<01:14,  4.00it/s]

🌐 GET deputados/204419/frentes
⏱ Tempo: 0.23s | 📦 Registros: 103

Frentes dos deputados:  43%|████▎     | 219/513 [00:53<01:04,  4.53it/s]

🌐 GET deputados/107283/frentes
⏱ Tempo: 0.20s | 📦 Registros: 170
🌐 GET deputados/129618/frentes
⏱ Tempo: 0.18s | 📦 Registros: 214

Frentes dos deputados:  43%|████▎     | 220/513 [00:53<01:01,  4.74it/s]

🌐 GET deputados/198197/frentes
⏱ Tempo: 0.18s | 📦 Registros: 187

Frentes dos deputados:  43%|████▎     | 221/513 [00:54<01:02,  4.65it/s]

🌐 GET deputados/204531/frentes
⏱ Tempo: 0.21s | 📦 Registros: 155

Frentes dos deputados:  43%|████▎     | 222/513 [00:54<01:05,  4.47it/s]

🌐 GET deputados/220664/frentes
⏱ Tempo: 0.24s | 📦 Registros: 37
🌐 GET deputados/220568/frentes
⏱ Tempo: 0.20s | 📦 Registros: 155

Frentes dos deputados:  44%|████▎     | 224/513 [00:54<01:01,  4.72it/s]

🌐 GET deputados/204408/frentes
⏱ Tempo: 0.19s | 📦 Registros: 159

Frentes dos deputados:  44%|████▍     | 225/513 [00:54<01:08,  4.18it/s]

🌐 GET deputados/204456/frentes
⏱ Tempo: 0.29s | 📦 Registros: 331

Frentes dos deputados:  44%|████▍     | 226/513 [00:55<01:09,  4.16it/s]

🌐 GET deputados/178964/frentes
⏱ Tempo: 0.23s | 📦 Registros: 638

Frentes dos deputados:  44%|████▍     | 227/513 [00:55<01:06,  4.29it/s]

🌐 GET deputados/178873/frentes
⏱ Tempo: 0.21s | 📦 Registros: 407

Frentes dos deputados:  44%|████▍     | 228/513 [00:55<01:05,  4.37it/s]

🌐 GET deputados/220537/frentes
⏱ Tempo: 0.21s | 📦 Registros: 67

Frentes dos deputados:  45%|████▍     | 229/513 [00:55<01:03,  4.44it/s]

🌐 GET deputados/204444/frentes
⏱ Tempo: 0.21s | 📦 Registros: 224

Frentes dos deputados:  45%|████▌     | 231/513 [00:56<01:00,  4.68it/s]

🌐 GET deputados/234788/frentes
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET deputados/220672/frentes
⏱ Tempo: 0.19s | 📦 Registros: 165

Frentes dos deputados:  45%|████▌     | 233/513 [00:56<00:56,  4.92it/s]

🌐 GET deputados/204539/frentes
⏱ Tempo: 0.18s | 📦 Registros: 183
🌐 GET deputados/178884/frentes
⏱ Tempo: 0.19s | 📦 Registros: 325

Frentes dos deputados:  46%|████▌     | 234/513 [00:56<01:00,  4.64it/s]

🌐 GET deputados/141450/frentes
⏱ Tempo: 0.24s | 📦 Registros: 442

Frentes dos deputados:  46%|████▌     | 235/513 [00:57<01:01,  4.53it/s]

🌐 GET deputados/160674/frentes
⏱ Tempo: 0.23s | 📦 Registros: 410

Frentes dos deputados:  46%|████▌     | 237/513 [00:57<00:58,  4.68it/s]

🌐 GET deputados/220563/frentes
⏱ Tempo: 0.21s | 📦 Registros: 254
🌐 GET deputados/204533/frentes
⏱ Tempo: 0.19s | 📦 Registros: 146

Frentes dos deputados:  46%|████▋     | 238/513 [00:57<01:01,  4.49it/s]

🌐 GET deputados/204508/frentes
⏱ Tempo: 0.24s | 📦 Registros: 103

Frentes dos deputados:  47%|████▋     | 239/513 [00:58<01:01,  4.48it/s]

🌐 GET deputados/235620/frentes
⏱ Tempo: 0.22s | 📦 Registros: 0
🌐 GET deputados/74295/frentes
⏱ Tempo: 0.20s | 📦 Registros: 0

Frentes dos deputados:  47%|████▋     | 242/513 [00:58<00:54,  4.95it/s]

🌐 GET deputados/98615/frentes
⏱ Tempo: 0.21s | 📦 Registros: 81
🌐 GET deputados/204436/frentes
⏱ Tempo: 0.16s | 📦 Registros: 173

Frentes dos deputados:  47%|████▋     | 243/513 [00:58<00:52,  5.18it/s]

🌐 GET deputados/220696/frentes
⏱ Tempo: 0.17s | 📦 Registros: 57

Frentes dos deputados:  48%|████▊     | 245/513 [00:59<00:52,  5.07it/s]

🌐 GET deputados/220670/frentes
⏱ Tempo: 0.23s | 📦 Registros: 44
🌐 GET deputados/220527/frentes
⏱ Tempo: 0.17s | 📦 Registros: 63

Frentes dos deputados:  48%|████▊     | 246/513 [00:59<00:53,  5.00it/s]

🌐 GET deputados/220697/frentes
⏱ Tempo: 0.20s | 📦 Registros: 224
🌐 GET deputados/74848/frentes
⏱ Tempo: 0.20s | 📦 Registros: 239

Frentes dos deputados:  48%|████▊     | 248/513 [00:59<00:52,  5.06it/s]

🌐 GET deputados/220567/frentes
⏱ Tempo: 0.18s | 📦 Registros: 124

Frentes dos deputados:  49%|████▊     | 250/513 [01:00<00:50,  5.19it/s]

🌐 GET deputados/74273/frentes
⏱ Tempo: 0.20s | 📦 Registros: 686
🌐 GET deputados/141456/frentes
⏱ Tempo: 0.17s | 📦 Registros: 92

Frentes dos deputados:  49%|████▉     | 251/513 [01:00<00:49,  5.27it/s]

🌐 GET deputados/235869/frentes
⏱ Tempo: 0.18s | 📦 Registros: 0

Frentes dos deputados:  49%|████▉     | 253/513 [01:00<00:50,  5.11it/s]

🌐 GET deputados/141458/frentes
⏱ Tempo: 0.24s | 📦 Registros: 384
🌐 GET deputados/230957/frentes
⏱ Tempo: 0.17s | 📦 Registros: 4

Frentes dos deputados:  50%|████▉     | 254/513 [01:01<00:52,  4.92it/s]

🌐 GET deputados/178970/frentes
⏱ Tempo: 0.21s | 📦 Registros: 488

Frentes dos deputados:  50%|████▉     | 255/513 [01:01<00:53,  4.83it/s]

🌐 GET deputados/141459/frentes
⏱ Tempo: 0.21s | 📦 Registros: 117

Frentes dos deputados:  50%|█████     | 257/513 [01:01<00:53,  4.77it/s]

🌐 GET deputados/178910/frentes
⏱ Tempo: 0.23s | 📦 Registros: 459
🌐 GET deputados/160548/frentes
⏱ Tempo: 0.19s | 📦 Registros: 127

Frentes dos deputados:  50%|█████     | 258/513 [01:01<00:52,  4.83it/s]

🌐 GET deputados/235800/frentes
⏱ Tempo: 0.20s | 📦 Registros: 0

Frentes dos deputados:  50%|█████     | 259/513 [01:02<00:56,  4.46it/s]

🌐 GET deputados/205550/frentes
⏱ Tempo: 0.26s | 📦 Registros: 176

Frentes dos deputados:  51%|█████     | 260/513 [01:02<00:55,  4.54it/s]

🌐 GET deputados/214694/frentes
⏱ Tempo: 0.21s | 📦 Registros: 178

Frentes dos deputados:  51%|█████     | 261/513 [01:02<00:57,  4.37it/s]

🌐 GET deputados/178857/frentes
⏱ Tempo: 0.24s | 📦 Registros: 628

Frentes dos deputados:  51%|█████     | 262/513 [01:02<00:57,  4.37it/s]

🌐 GET deputados/141464/frentes
⏱ Tempo: 0.21s | 📦 Registros: 373

Frentes dos deputados:  51%|█████▏    | 263/513 [01:03<00:56,  4.43it/s]

🌐 GET deputados/204472/frentes
⏱ Tempo: 0.21s | 📦 Registros: 305

Frentes dos deputados:  51%|█████▏    | 264/513 [01:03<00:58,  4.29it/s]

🌐 GET deputados/204391/frentes
⏱ Tempo: 0.24s | 📦 Registros: 130

Frentes dos deputados:  52%|█████▏    | 265/513 [01:03<00:57,  4.29it/s]

🌐 GET deputados/74079/frentes
⏱ Tempo: 0.22s | 📦 Registros: 298

Frentes dos deputados:  52%|█████▏    | 266/513 [01:03<00:57,  4.29it/s]

🌐 GET deputados/74554/frentes
⏱ Tempo: 0.22s | 📦 Registros: 425
🌐 GET deputados/209189/frentes
⏱ Tempo: 0.19s | 📦 Registros: 146

Frentes dos deputados:  52%|█████▏    | 268/513 [01:04<00:53,  4.61it/s]

🌐 GET deputados/220578/frentes
⏱ Tempo: 0.20s | 📦 Registros: 74
🌐 GET deputados/215043/frentes
⏱ Tempo: 0.19s | 📦 Registros: 82

Frentes dos deputados:  53%|█████▎    | 271/513 [01:04<00:48,  4.95it/s]

🌐 GET deputados/204474/frentes
⏱ Tempo: 0.18s | 📦 Registros: 280
🌐 GET deputados/220559/frentes
⏱ Tempo: 0.19s | 📦 Registros: 77

Frentes dos deputados:  53%|█████▎    | 273/513 [01:05<00:48,  4.95it/s]

🌐 GET deputados/220640/frentes
⏱ Tempo: 0.22s | 📦 Registros: 72
🌐 GET deputados/66385/frentes
⏱ Tempo: 0.18s | 📦 Registros: 36

Frentes dos deputados:  53%|█████▎    | 274/513 [01:05<00:50,  4.73it/s]

🌐 GET deputados/74317/frentes
⏱ Tempo: 0.22s | 📦 Registros: 596

Frentes dos deputados:  54%|█████▎    | 275/513 [01:05<00:51,  4.65it/s]

🌐 GET deputados/204372/frentes
⏱ Tempo: 0.22s | 📦 Registros: 313

Frentes dos deputados:  54%|█████▍    | 276/513 [01:05<00:51,  4.60it/s]

🌐 GET deputados/74253/frentes
⏱ Tempo: 0.22s | 📦 Registros: 355

Frentes dos deputados:  54%|█████▍    | 278/513 [01:06<00:50,  4.67it/s]

🌐 GET deputados/204457/frentes
⏱ Tempo: 0.23s | 📦 Registros: 231
🌐 GET deputados/204520/frentes
⏱ Tempo: 0.19s | 📦 Registros: 235

Frentes dos deputados:  55%|█████▍    | 280/513 [01:06<00:46,  5.03it/s]

🌐 GET deputados/204497/frentes
⏱ Tempo: 0.18s | 📦 Registros: 324
🌐 GET deputados/204574/frentes
⏱ Tempo: 0.18s | 📦 Registros: 197

Frentes dos deputados:  55%|█████▍    | 282/513 [01:07<00:45,  5.05it/s]

🌐 GET deputados/204550/frentes
⏱ Tempo: 0.22s | 📦 Registros: 266
🌐 GET deputados/178886/frentes
⏱ Tempo: 0.17s | 📦 Registros: 95

Frentes dos deputados:  55%|█████▌    | 283/513 [01:07<00:50,  4.56it/s]

🌐 GET deputados/220677/frentes
⏱ Tempo: 0.26s | 📦 Registros: 22

Frentes dos deputados:  56%|█████▌    | 285/513 [01:07<00:48,  4.71it/s]

🌐 GET deputados/162067/frentes
⏱ Tempo: 0.22s | 📦 Registros: 92
🌐 GET deputados/204536/frentes
⏱ Tempo: 0.19s | 📦 Registros: 364

Frentes dos deputados:  56%|█████▌    | 286/513 [01:07<00:48,  4.72it/s]

🌐 GET deputados/98057/frentes
⏱ Tempo: 0.20s | 📦 Registros: 568

Frentes dos deputados:  56%|█████▌    | 287/513 [01:08<00:47,  4.72it/s]

🌐 GET deputados/74856/frentes
⏱ Tempo: 0.21s | 📦 Registros: 259

Frentes dos deputados:  56%|█████▌    | 288/513 [01:08<00:50,  4.43it/s]

🌐 GET deputados/178832/frentes
⏱ Tempo: 0.25s | 📦 Registros: 219

Frentes dos deputados:  57%|█████▋    | 290/513 [01:08<00:49,  4.53it/s]

🌐 GET deputados/220566/frentes
⏱ Tempo: 0.23s | 📦 Registros: 180
🌐 GET deputados/80815/frentes
⏱ Tempo: 0.19s | 📦 Registros: 88

Frentes dos deputados:  57%|█████▋    | 291/513 [01:09<00:50,  4.41it/s]

🌐 GET deputados/74156/frentes
⏱ Tempo: 0.24s | 📦 Registros: 884
🌐 GET deputados/92102/frentes
⏱ Tempo: 0.20s | 📦 Registros: 249

Frentes dos deputados:  57%|█████▋    | 293/513 [01:09<00:49,  4.44it/s]

🌐 GET deputados/139285/frentes
⏱ Tempo: 0.22s | 📦 Registros: 338

Frentes dos deputados:  58%|█████▊    | 295/513 [01:10<00:49,  4.37it/s]

🌐 GET deputados/74585/frentes
⏱ Tempo: 0.32s | 📦 Registros: 857
🌐 GET deputados/74858/frentes
⏱ Tempo: 0.16s | 📦 Registros: 180

Frentes dos deputados:  58%|█████▊    | 297/513 [01:10<00:46,  4.61it/s]

🌐 GET deputados/220662/frentes
⏱ Tempo: 0.21s | 📦 Registros: 167
🌐 GET deputados/204404/frentes
⏱ Tempo: 0.19s | 📦 Registros: 375

Frentes dos deputados:  58%|█████▊    | 298/513 [01:10<00:47,  4.56it/s]

🌐 GET deputados/220581/frentes
⏱ Tempo: 0.22s | 📦 Registros: 39

Frentes dos deputados:  58%|█████▊    | 299/513 [01:10<00:48,  4.44it/s]

🌐 GET deputados/74478/frentes
⏱ Tempo: 0.23s | 📦 Registros: 86

Frentes dos deputados:  58%|█████▊    | 300/513 [01:11<00:50,  4.22it/s]

🌐 GET deputados/178931/frentes
⏱ Tempo: 0.26s | 📦 Registros: 431

Frentes dos deputados:  59%|█████▊    | 301/513 [01:11<00:52,  4.01it/s]

🌐 GET deputados/220616/frentes
⏱ Tempo: 0.27s | 📦 Registros: 151

Frentes dos deputados:  59%|█████▉    | 302/513 [01:11<00:53,  3.97it/s]

🌐 GET deputados/178954/frentes
⏱ Tempo: 0.25s | 📦 Registros: 624

Frentes dos deputados:  59%|█████▉    | 303/513 [01:11<00:50,  4.13it/s]

🌐 GET deputados/204410/frentes
⏱ Tempo: 0.21s | 📦 Registros: 437

Frentes dos deputados:  59%|█████▉    | 304/513 [01:12<00:50,  4.16it/s]

🌐 GET deputados/141485/frentes
⏱ Tempo: 0.23s | 📦 Registros: 233

Frentes dos deputados:  59%|█████▉    | 305/513 [01:12<00:48,  4.32it/s]

🌐 GET deputados/73778/frentes
⏱ Tempo: 0.20s | 📦 Registros: 117

Frentes dos deputados:  60%|█████▉    | 306/513 [01:12<00:51,  4.04it/s]

🌐 GET deputados/204485/frentes
⏱ Tempo: 0.28s | 📦 Registros: 204
🌐 GET deputados/74041/frentes
⏱ Tempo: 0.20s | 📦 Registros: 358

Frentes dos deputados:  60%|██████    | 308/513 [01:13<00:58,  3.53it/s]

🌐 GET deputados/141487/frentes
⏱ Tempo: 0.39s | 📦 Registros: 390

Frentes dos deputados:  60%|██████    | 309/513 [01:13<00:55,  3.67it/s]

🌐 GET deputados/220658/frentes
⏱ Tempo: 0.24s | 📦 Registros: 67
🌐 GET deputados/204455/frentes
⏱ Tempo: 0.20s | 📦 Registros: 316

Frentes dos deputados:  61%|██████    | 312/513 [01:14<00:46,  4.28it/s]

🌐 GET deputados/162332/frentes
⏱ Tempo: 0.26s | 📦 Registros: 740
🌐 GET deputados/204526/frentes
⏱ Tempo: 0.17s | 📦 Registros: 257

Frentes dos deputados:  61%|██████    | 313/513 [01:14<00:46,  4.30it/s]

🌐 GET deputados/74784/frentes
⏱ Tempo: 0.22s | 📦 Registros: 248

Frentes dos deputados:  61%|██████    | 314/513 [01:14<00:50,  3.96it/s]

🌐 GET deputados/178866/frentes
⏱ Tempo: 0.30s | 📦 Registros: 262

Frentes dos deputados:  61%|██████▏   | 315/513 [01:14<00:50,  3.95it/s]

🌐 GET deputados/220669/frentes
⏱ Tempo: 0.25s | 📦 Registros: 104

Frentes dos deputados:  62%|██████▏   | 316/513 [01:15<00:59,  3.33it/s]

🌐 GET deputados/166402/frentes
⏱ Tempo: 0.40s | 📦 Registros: 247

Frentes dos deputados:  62%|██████▏   | 317/513 [01:15<00:55,  3.56it/s]

🌐 GET deputados/220648/frentes
⏱ Tempo: 0.23s | 📦 Registros: 305

Frentes dos deputados:  62%|██████▏   | 318/513 [01:15<00:51,  3.76it/s]

🌐 GET deputados/156190/frentes
⏱ Tempo: 0.23s | 📦 Registros: 167

Frentes dos deputados:  62%|██████▏   | 319/513 [01:16<00:49,  3.92it/s]

🌐 GET deputados/179000/frentes
⏱ Tempo: 0.22s | 📦 Registros: 406

Frentes dos deputados:  62%|██████▏   | 320/513 [01:16<00:48,  3.99it/s]

🌐 GET deputados/220599/frentes
⏱ Tempo: 0.24s | 📦 Registros: 226
🌐 GET deputados/133810/frentes
⏱ Tempo: 0.20s | 📦 Registros: 116

Frentes dos deputados:  63%|██████▎   | 323/513 [01:16<00:41,  4.55it/s]

🌐 GET deputados/204558/frentes
⏱ Tempo: 0.21s | 📦 Registros: 274
🌐 GET deputados/160161/frentes
⏱ Tempo: 0.19s | 📦 Registros: 214

Frentes dos deputados:  63%|██████▎   | 324/513 [01:17<00:42,  4.42it/s]

🌐 GET deputados/178983/frentes
⏱ Tempo: 0.23s | 📦 Registros: 292

Frentes dos deputados:  64%|██████▎   | 326/513 [01:17<00:41,  4.53it/s]

🌐 GET deputados/179001/frentes
⏱ Tempo: 0.24s | 📦 Registros: 212
🌐 GET deputados/220687/frentes
⏱ Tempo: 0.19s | 📦 Registros: 254

Frentes dos deputados:  64%|██████▎   | 327/513 [01:17<00:41,  4.45it/s]

🌐 GET deputados/81055/frentes
⏱ Tempo: 0.23s | 📦 Registros: 273

Frentes dos deputados:  64%|██████▍   | 328/513 [01:18<00:42,  4.35it/s]

🌐 GET deputados/150418/frentes
⏱ Tempo: 0.24s | 📦 Registros: 810

Frentes dos deputados:  64%|██████▍   | 329/513 [01:18<00:45,  4.00it/s]

🌐 GET deputados/160535/frentes
⏱ Tempo: 0.29s | 📦 Registros: 631

Frentes dos deputados:  65%|██████▍   | 331/513 [01:18<00:41,  4.38it/s]

🌐 GET deputados/204431/frentes
⏱ Tempo: 0.22s | 📦 Registros: 74
🌐 GET deputados/204506/frentes
⏱ Tempo: 0.19s | 📦 Registros: 151

Frentes dos deputados:  65%|██████▍   | 332/513 [01:18<00:40,  4.52it/s]

🌐 GET deputados/220547/frentes
⏱ Tempo: 0.20s | 📦 Registros: 127

Frentes dos deputados:  65%|██████▍   | 333/513 [01:19<00:40,  4.44it/s]

🌐 GET deputados/178943/frentes
⏱ Tempo: 0.23s | 📦 Registros: 64

Frentes dos deputados:  65%|██████▌   | 334/513 [01:19<00:39,  4.51it/s]

🌐 GET deputados/220604/frentes
⏱ Tempo: 0.21s | 📦 Registros: 119

Frentes dos deputados:  65%|██████▌   | 335/513 [01:19<00:41,  4.31it/s]

🌐 GET deputados/220668/frentes
⏱ Tempo: 0.25s | 📦 Registros: 186

Frentes dos deputados:  65%|██████▌   | 336/513 [01:19<00:43,  4.04it/s]

🌐 GET deputados/74398/frentes
⏱ Tempo: 0.28s | 📦 Registros: 429

Frentes dos deputados:  66%|██████▌   | 337/513 [01:23<03:23,  1.15s/it]

🌐 GET deputados/204540/frentes
⏱ Tempo: 3.27s | 📦 Registros: 166

Frentes dos deputados:  66%|██████▌   | 338/513 [01:23<02:32,  1.15it/s]

🌐 GET deputados/220637/frentes
⏱ Tempo: 0.20s | 📦 Registros: 0

Frentes dos deputados:  66%|██████▌   | 339/513 [01:23<01:57,  1.49it/s]

🌐 GET deputados/220655/frentes
⏱ Tempo: 0.21s | 📦 Registros: 100

Frentes dos deputados:  66%|██████▋   | 340/513 [01:23<01:34,  1.84it/s]

🌐 GET deputados/74158/frentes
⏱ Tempo: 0.23s | 📦 Registros: 552

Frentes dos deputados:  66%|██████▋   | 341/513 [01:24<01:17,  2.23it/s]

🌐 GET deputados/178858/frentes
⏱ Tempo: 0.22s | 📦 Registros: 484

Frentes dos deputados:  67%|██████▋   | 342/513 [01:24<01:06,  2.58it/s]

🌐 GET deputados/220572/frentes
⏱ Tempo: 0.24s | 📦 Registros: 143

Frentes dos deputados:  67%|██████▋   | 344/513 [01:24<00:49,  3.43it/s]

🌐 GET deputados/178843/frentes
⏱ Tempo: 0.21s | 📦 Registros: 499
🌐 GET deputados/220661/frentes
⏱ Tempo: 0.18s | 📦 Registros: 70

Frentes dos deputados:  67%|██████▋   | 345/513 [01:25<00:53,  3.15it/s]

🌐 GET deputados/220609/frentes
⏱ Tempo: 0.37s | 📦 Registros: 61

Frentes dos deputados:  67%|██████▋   | 346/513 [01:25<00:48,  3.43it/s]

🌐 GET deputados/220628/frentes
⏱ Tempo: 0.22s | 📦 Registros: 87

Frentes dos deputados:  68%|██████▊   | 348/513 [01:25<00:41,  3.97it/s]

🌐 GET deputados/220550/frentes
⏱ Tempo: 0.23s | 📦 Registros: 108
🌐 GET deputados/220647/frentes
⏱ Tempo: 0.19s | 📦 Registros: 191

Frentes dos deputados:  68%|██████▊   | 349/513 [01:26<00:40,  4.07it/s]

🌐 GET deputados/204486/frentes
⏱ Tempo: 0.22s | 📦 Registros: 233
🌐 GET deputados/220607/frentes
⏱ Tempo: 0.20s | 📦 Registros: 209

Frentes dos deputados:  69%|██████▊   | 352/513 [01:26<00:34,  4.70it/s]

🌐 GET deputados/220591/frentes
⏱ Tempo: 0.19s | 📦 Registros: 205
🌐 GET deputados/74428/frentes
⏱ Tempo: 0.18s | 📦 Registros: 172

Frentes dos deputados:  69%|██████▉   | 353/513 [01:26<00:35,  4.44it/s]

🌐 GET deputados/188097/frentes
⏱ Tempo: 0.25s | 📦 Registros: 176

Frentes dos deputados:  69%|██████▉   | 355/513 [01:27<00:35,  4.47it/s]

🌐 GET deputados/220585/frentes
⏱ Tempo: 0.26s | 📦 Registros: 103
🌐 GET deputados/220530/frentes
⏱ Tempo: 0.18s | 📦 Registros: 172

Frentes dos deputados:  70%|██████▉   | 357/513 [01:28<01:03,  2.45it/s]

🌐 GET deputados/171786/frentes
⏱ Tempo: 1.14s | 📦 Registros: 64
🌐 GET deputados/178985/frentes
⏱ Tempo: 0.19s | 📦 Registros: 430

Frentes dos deputados:  70%|██████▉   | 359/513 [01:29<00:46,  3.31it/s]

🌐 GET deputados/154178/frentes
⏱ Tempo: 0.21s | 📦 Registros: 232
🌐 GET deputados/178895/frentes
⏱ Tempo: 0.19s | 📦 Registros: 349

Frentes dos deputados:  70%|███████   | 360/513 [01:29<00:51,  2.95it/s]

🌐 GET deputados/160561/frentes
⏱ Tempo: 0.42s | 📦 Registros: 304

Frentes dos deputados:  70%|███████   | 361/513 [01:29<00:48,  3.13it/s]

🌐 GET deputados/178997/frentes
⏱ Tempo: 0.27s | 📦 Registros: 558

Frentes dos deputados:  71%|███████   | 362/513 [01:30<00:45,  3.30it/s]

🌐 GET deputados/220617/frentes
⏱ Tempo: 0.26s | 📦 Registros: 161

Frentes dos deputados:  71%|███████   | 364/513 [01:30<00:39,  3.80it/s]

🌐 GET deputados/220584/frentes
⏱ Tempo: 0.26s | 📦 Registros: 70
🌐 GET deputados/204453/frentes
⏱ Tempo: 0.19s | 📦 Registros: 226

Frentes dos deputados:  71%|███████   | 365/513 [01:30<00:36,  4.03it/s]

🌐 GET deputados/204449/frentes
⏱ Tempo: 0.20s | 📦 Registros: 69

Frentes dos deputados:  71%|███████▏  | 366/513 [01:30<00:34,  4.24it/s]

🌐 GET deputados/220622/frentes
⏱ Tempo: 0.20s | 📦 Registros: 34

Frentes dos deputados:  72%|███████▏  | 367/513 [01:31<00:34,  4.25it/s]

🌐 GET deputados/220703/frentes
⏱ Tempo: 0.23s | 📦 Registros: 121
🌐 GET deputados/178896/frentes
⏱ Tempo: 0.20s | 📦 Registros: 580

Frentes dos deputados:  72%|███████▏  | 369/513 [01:31<00:31,  4.59it/s]

🌐 GET deputados/204479/frentes
⏱ Tempo: 0.19s | 📦 Registros: 324
🌐 GET deputados/209787/frentes
⏱ Tempo: 0.20s | 📦 Registros: 80

Frentes dos deputados:  72%|███████▏  | 371/513 [01:32<00:34,  4.07it/s]

🌐 GET deputados/178986/frentes
⏱ Tempo: 0.31s | 📦 Registros: 605

Frentes dos deputados:  73%|███████▎  | 373/513 [01:32<00:31,  4.38it/s]

🌐 GET deputados/74159/frentes
⏱ Tempo: 0.22s | 📦 Registros: 347
🌐 GET deputados/204498/frentes
⏱ Tempo: 0.19s | 📦 Registros: 181

Frentes dos deputados:  73%|███████▎  | 374/513 [01:32<00:32,  4.33it/s]

🌐 GET deputados/178987/frentes
⏱ Tempo: 0.23s | 📦 Registros: 536

Frentes dos deputados:  73%|███████▎  | 375/513 [01:33<00:33,  4.17it/s]

🌐 GET deputados/73692/frentes
⏱ Tempo: 0.26s | 📦 Registros: 304

Frentes dos deputados:  73%|███████▎  | 376/513 [01:33<00:33,  4.14it/s]

🌐 GET deputados/204441/frentes
⏱ Tempo: 0.24s | 📦 Registros: 396

Frentes dos deputados:  73%|███████▎  | 377/513 [01:33<00:31,  4.26it/s]

🌐 GET deputados/220706/frentes
⏱ Tempo: 0.21s | 📦 Registros: 95

Frentes dos deputados:  74%|███████▎  | 378/513 [01:33<00:31,  4.28it/s]

🌐 GET deputados/160556/frentes
⏱ Tempo: 0.23s | 📦 Registros: 792

Frentes dos deputados:  74%|███████▍  | 379/513 [01:34<00:34,  3.90it/s]

🌐 GET deputados/180214/frentes
⏱ Tempo: 0.30s | 📦 Registros: 169
🌐 GET deputados/160642/frentes
⏱ Tempo: 0.20s | 📦 Registros: 606

Frentes dos deputados:  74%|███████▍  | 381/513 [01:34<00:30,  4.30it/s]

🌐 GET deputados/204570/frentes
⏱ Tempo: 0.21s | 📦 Registros: 135

Frentes dos deputados:  74%|███████▍  | 382/513 [01:34<00:30,  4.37it/s]

🌐 GET deputados/220615/frentes
⏱ Tempo: 0.21s | 📦 Registros: 84

Frentes dos deputados:  75%|███████▍  | 384/513 [01:35<00:30,  4.21it/s]

🌐 GET deputados/204553/frentes
⏱ Tempo: 0.31s | 📦 Registros: 277
🌐 GET deputados/74160/frentes
⏱ Tempo: 0.19s | 📦 Registros: 422

Frentes dos deputados:  75%|███████▌  | 385/513 [01:35<00:29,  4.31it/s]

🌐 GET deputados/171617/frentes
⏱ Tempo: 0.21s | 📦 Registros: 305
🌐 GET deputados/141518/frentes
⏱ Tempo: 0.20s | 📦 Registros: 248

Frentes dos deputados:  75%|███████▌  | 387/513 [01:35<00:29,  4.33it/s]

🌐 GET deputados/141516/frentes
⏱ Tempo: 0.24s | 📦 Registros: 418

Frentes dos deputados:  76%|███████▌  | 388/513 [01:36<00:29,  4.18it/s]

🌐 GET deputados/220650/frentes
⏱ Tempo: 0.25s | 📦 Registros: 206

Frentes dos deputados:  76%|███████▌  | 389/513 [01:36<00:29,  4.28it/s]

🌐 GET deputados/178860/frentes
⏱ Tempo: 0.21s | 📦 Registros: 137

Frentes dos deputados:  76%|███████▌  | 390/513 [01:36<00:28,  4.26it/s]

🌐 GET deputados/160517/frentes
⏱ Tempo: 0.23s | 📦 Registros: 657

Frentes dos deputados:  76%|███████▌  | 391/513 [01:36<00:28,  4.33it/s]

🌐 GET deputados/160558/frentes
⏱ Tempo: 0.22s | 📦 Registros: 559

Frentes dos deputados:  77%|███████▋  | 393/513 [01:37<00:25,  4.66it/s]

🌐 GET deputados/204492/frentes
⏱ Tempo: 0.22s | 📦 Registros: 310
🌐 GET deputados/233592/frentes
⏱ Tempo: 0.18s | 📦 Registros: 2

Frentes dos deputados:  77%|███████▋  | 394/513 [01:37<00:24,  4.94it/s]

🌐 GET deputados/220685/frentes
⏱ Tempo: 0.17s | 📦 Registros: 63

Frentes dos deputados:  77%|███████▋  | 395/513 [01:37<00:24,  4.78it/s]

🌐 GET deputados/74574/frentes
⏱ Tempo: 0.22s | 📦 Registros: 146

Frentes dos deputados:  77%|███████▋  | 396/513 [01:37<00:25,  4.62it/s]

🌐 GET deputados/128760/frentes
⏱ Tempo: 0.23s | 📦 Registros: 2
🌐 GET deputados/74400/frentes
⏱ Tempo: 0.20s | 📦 Registros: 300

Frentes dos deputados:  78%|███████▊  | 398/513 [01:38<00:25,  4.53it/s]

🌐 GET deputados/141488/frentes
⏱ Tempo: 0.23s | 📦 Registros: 525

Frentes dos deputados:  78%|███████▊  | 399/513 [01:38<00:25,  4.50it/s]

🌐 GET deputados/220630/frentes
⏱ Tempo: 0.22s | 📦 Registros: 211

Frentes dos deputados:  78%|███████▊  | 400/513 [01:38<00:25,  4.38it/s]

🌐 GET deputados/220667/frentes
⏱ Tempo: 0.24s | 📦 Registros: 101

Frentes dos deputados:  78%|███████▊  | 402/513 [01:39<00:25,  4.31it/s]

🌐 GET deputados/122974/frentes
⏱ Tempo: 0.30s | 📦 Registros: 285
🌐 GET deputados/204395/frentes
⏱ Tempo: 0.18s | 📦 Registros: 192

Frentes dos deputados:  79%|███████▊  | 403/513 [01:39<00:24,  4.52it/s]

🌐 GET deputados/122158/frentes
⏱ Tempo: 0.19s | 📦 Registros: 324

Frentes dos deputados:  79%|███████▉  | 404/513 [01:39<00:24,  4.40it/s]

🌐 GET deputados/160604/frentes
⏱ Tempo: 0.23s | 📦 Registros: 677
🌐 GET deputados/204406/frentes
⏱ Tempo: 0.19s | 📦 Registros: 356

Frentes dos deputados:  79%|███████▉  | 407/513 [01:40<00:22,  4.79it/s]

🌐 GET deputados/161440/frentes
⏱ Tempo: 0.20s | 📦 Registros: 234
🌐 GET deputados/204524/frentes
⏱ Tempo: 0.19s | 📦 Registros: 248

Frentes dos deputados:  80%|███████▉  | 409/513 [01:40<00:20,  5.00it/s]

🌐 GET deputados/73486/frentes
⏱ Tempo: 0.20s | 📦 Registros: 670
🌐 GET deputados/160601/frentes
⏱ Tempo: 0.17s | 📦 Registros: 369

Frentes dos deputados:  80%|███████▉  | 410/513 [01:40<00:22,  4.59it/s]

🌐 GET deputados/220533/frentes
⏱ Tempo: 0.25s | 📦 Registros: 185

Frentes dos deputados:  80%|████████  | 412/513 [01:41<00:21,  4.73it/s]

🌐 GET deputados/204390/frentes
⏱ Tempo: 0.23s | 📦 Registros: 228
🌐 GET deputados/221338/frentes
⏱ Tempo: 0.18s | 📦 Registros: 131

Frentes dos deputados:  81%|████████  | 413/513 [01:41<00:20,  4.86it/s]

🌐 GET deputados/160641/frentes
⏱ Tempo: 0.19s | 📦 Registros: 341

Frentes dos deputados:  81%|████████  | 415/513 [01:41<00:20,  4.89it/s]

🌐 GET deputados/220586/frentes
⏱ Tempo: 0.21s | 📦 Registros: 55
🌐 GET deputados/233594/frentes
⏱ Tempo: 0.19s | 📦 Registros: 7

Frentes dos deputados:  81%|████████  | 416/513 [01:42<00:20,  4.81it/s]

🌐 GET deputados/220532/frentes
⏱ Tempo: 0.21s | 📦 Registros: 55

Frentes dos deputados:  81%|████████▏ | 417/513 [01:42<00:20,  4.59it/s]

🌐 GET deputados/220626/frentes
⏱ Tempo: 0.24s | 📦 Registros: 105
🌐 GET deputados/204567/frentes
⏱ Tempo: 0.21s | 📦 Registros: 317

Frentes dos deputados:  82%|████████▏ | 419/513 [01:42<00:21,  4.37it/s]

🌐 GET deputados/74084/frentes
⏱ Tempo: 0.25s | 📦 Registros: 191

Frentes dos deputados:  82%|████████▏ | 421/513 [01:43<00:20,  4.58it/s]

🌐 GET deputados/74161/frentes
⏱ Tempo: 0.23s | 📦 Registros: 688
🌐 GET deputados/220606/frentes
⏱ Tempo: 0.18s | 📦 Registros: 104

Frentes dos deputados:  82%|████████▏ | 422/513 [01:43<00:22,  4.03it/s]

🌐 GET deputados/178989/frentes
⏱ Tempo: 0.31s | 📦 Registros: 328
🌐 GET deputados/153423/frentes
⏱ Tempo: 0.20s | 📦 Registros: 242

Frentes dos deputados:  83%|████████▎ | 424/513 [01:43<00:19,  4.49it/s]

🌐 GET deputados/73801/frentes
⏱ Tempo: 0.19s | 📦 Registros: 291

Frentes dos deputados:  83%|████████▎ | 426/513 [01:44<00:19,  4.55it/s]

🌐 GET deputados/175765/frentes
⏱ Tempo: 0.26s | 📦 Registros: 12
🌐 GET deputados/235088/frentes
⏱ Tempo: 0.18s | 📦 Registros: 0

Frentes dos deputados:  83%|████████▎ | 427/513 [01:44<00:25,  3.34it/s]

🌐 GET deputados/221329/frentes
⏱ Tempo: 0.48s | 📦 Registros: 57

Frentes dos deputados:  83%|████████▎ | 428/513 [01:45<00:36,  2.32it/s]

🌐 GET deputados/220543/frentes
⏱ Tempo: 0.73s | 📦 Registros: 220
🌐 GET deputados/73788/frentes
⏱ Tempo: 0.19s | 📦 Registros: 193

Frentes dos deputados:  84%|████████▍ | 430/513 [01:46<00:29,  2.84it/s]

🌐 GET deputados/204362/frentes
⏱ Tempo: 0.32s | 📦 Registros: 201

Frentes dos deputados:  84%|████████▍ | 431/513 [01:46<00:31,  2.60it/s]

🌐 GET deputados/220694/frentes
⏱ Tempo: 0.45s | 📦 Registros: 61

Frentes dos deputados:  84%|████████▍ | 433/513 [01:47<00:28,  2.76it/s]

🌐 GET deputados/220633/frentes
⏱ Tempo: 0.57s | 📦 Registros: 89
🌐 GET deputados/204489/frentes
⏱ Tempo: 0.17s | 📦 Registros: 96

Frentes dos deputados:  85%|████████▍ | 434/513 [01:47<00:24,  3.19it/s]

🌐 GET deputados/220693/frentes
⏱ Tempo: 0.19s | 📦 Registros: 73
🌐 GET deputados/220588/frentes
⏱ Tempo: 0.19s | 📦 Registros: 261

Frentes dos deputados:  85%|████████▍ | 436/513 [01:48<00:19,  3.96it/s]

🌐 GET deputados/220613/frentes
⏱ Tempo: 0.18s | 📦 Registros: 156

Frentes dos deputados:  85%|████████▌ | 437/513 [01:48<00:18,  4.10it/s]

🌐 GET deputados/220624/frentes
⏱ Tempo: 0.22s | 📦 Registros: 61

Frentes dos deputados:  86%|████████▌ | 439/513 [01:48<00:16,  4.49it/s]

🌐 GET deputados/220546/frentes
⏱ Tempo: 0.22s | 📦 Registros: 43
🌐 GET deputados/230767/frentes
⏱ Tempo: 0.18s | 📦 Registros: 12

Frentes dos deputados:  86%|████████▌ | 440/513 [01:48<00:16,  4.43it/s]

🌐 GET deputados/141531/frentes
⏱ Tempo: 0.23s | 📦 Registros: 474

Frentes dos deputados:  86%|████████▌ | 441/513 [01:49<00:16,  4.27it/s]

🌐 GET deputados/220641/frentes
⏱ Tempo: 0.24s | 📦 Registros: 158

Frentes dos deputados:  86%|████████▌ | 442/513 [01:49<00:16,  4.20it/s]

🌐 GET deputados/141533/frentes
⏱ Tempo: 0.24s | 📦 Registros: 9

Frentes dos deputados:  87%|████████▋ | 444/513 [01:49<00:15,  4.43it/s]

🌐 GET deputados/165470/frentes
⏱ Tempo: 0.25s | 📦 Registros: 136
🌐 GET deputados/220695/frentes
⏱ Tempo: 0.18s | 📦 Registros: 209

Frentes dos deputados:  87%|████████▋ | 445/513 [01:50<00:14,  4.56it/s]

🌐 GET deputados/204480/frentes
⏱ Tempo: 0.20s | 📦 Registros: 415

Frentes dos deputados:  87%|████████▋ | 446/513 [01:50<00:16,  4.13it/s]

🌐 GET deputados/160629/frentes
⏱ Tempo: 0.29s | 📦 Registros: 305

Frentes dos deputados:  87%|████████▋ | 447/513 [01:50<00:15,  4.13it/s]

🌐 GET deputados/204525/frentes
⏱ Tempo: 0.24s | 📦 Registros: 262

Frentes dos deputados:  88%|████████▊ | 449/513 [01:51<00:21,  2.98it/s]

🌐 GET deputados/178945/frentes
⏱ Tempo: 0.79s | 📦 Registros: 210
🌐 GET deputados/220644/frentes
⏱ Tempo: 0.16s | 📦 Registros: 121

Frentes dos deputados:  88%|████████▊ | 450/513 [01:51<00:18,  3.36it/s]

🌐 GET deputados/220620/frentes
⏱ Tempo: 0.20s | 📦 Registros: 98

Frentes dos deputados:  88%|████████▊ | 451/513 [01:52<00:27,  2.28it/s]

🌐 GET deputados/74371/frentes
⏱ Tempo: 0.76s | 📦 Registros: 788

Frentes dos deputados:  88%|████████▊ | 452/513 [01:52<00:22,  2.67it/s]

🌐 GET deputados/178887/frentes
⏱ Tempo: 0.22s | 📦 Registros: 449

Frentes dos deputados:  88%|████████▊ | 453/513 [01:53<00:27,  2.16it/s]

🌐 GET deputados/73604/frentes
⏱ Tempo: 0.66s | 📦 Registros: 258
🌐 GET deputados/160635/frentes
⏱ Tempo: 0.20s | 📦 Registros: 515

Frentes dos deputados:  89%|████████▉ | 456/513 [01:54<00:17,  3.22it/s]

🌐 GET deputados/204535/frentes
⏱ Tempo: 0.33s | 📦 Registros: 257
🌐 GET deputados/220631/frentes
⏱ Tempo: 0.16s | 📦 Registros: 43

Frentes dos deputados:  89%|████████▉ | 457/513 [01:54<00:15,  3.62it/s]

🌐 GET deputados/204416/frentes
⏱ Tempo: 0.19s | 📦 Registros: 310
🌐 GET deputados/160621/frentes
⏱ Tempo: 0.20s | 📦 Registros: 275

Frentes dos deputados:  89%|████████▉ | 459/513 [01:54<00:17,  3.05it/s]

🌐 GET deputados/204387/frentes
⏱ Tempo: 0.49s | 📦 Registros: 267

Frentes dos deputados:  90%|████████▉ | 460/513 [01:55<00:16,  3.14it/s]

🌐 GET deputados/220621/frentes
⏱ Tempo: 0.29s | 📦 Registros: 87

Frentes dos deputados:  90%|████████▉ | 461/513 [01:58<01:01,  1.18s/it]

🌐 GET deputados/220618/frentes
⏱ Tempo: 3.19s | 📦 Registros: 224

Frentes dos deputados:  90%|█████████ | 462/513 [01:58<00:45,  1.11it/s]

🌐 GET deputados/220713/frentes
⏱ Tempo: 0.23s | 📦 Registros: 189

Frentes dos deputados:  90%|█████████ | 463/513 [01:59<00:36,  1.38it/s]

🌐 GET deputados/226837/frentes
⏱ Tempo: 0.30s | 📦 Registros: 17

Frentes dos deputados:  90%|█████████ | 464/513 [01:59<00:28,  1.70it/s]

🌐 GET deputados/73808/frentes
⏱ Tempo: 0.26s | 📦 Registros: 360

Frentes dos deputados:  91%|█████████ | 466/513 [01:59<00:19,  2.38it/s]

🌐 GET deputados/178933/frentes
⏱ Tempo: 0.37s | 📦 Registros: 298
🌐 GET deputados/235776/frentes
⏱ Tempo: 0.18s | 📦 Registros: 0

Frentes dos deputados:  91%|█████████ | 467/513 [02:00<00:19,  2.39it/s]

🌐 GET deputados/204557/frentes
⏱ Tempo: 0.40s | 📦 Registros: 221

Frentes dos deputados:  91%|█████████▏| 469/513 [02:00<00:13,  3.22it/s]

🌐 GET deputados/204360/frentes
⏱ Tempo: 0.22s | 📦 Registros: 473
🌐 GET deputados/227310/frentes
⏱ Tempo: 0.19s | 📦 Registros: 0

Frentes dos deputados:  92%|█████████▏| 470/513 [02:00<00:12,  3.50it/s]

🌐 GET deputados/204425/frentes
⏱ Tempo: 0.22s | 📦 Registros: 367

Frentes dos deputados:  92%|█████████▏| 472/513 [02:01<00:10,  4.08it/s]

🌐 GET deputados/220569/frentes
⏱ Tempo: 0.25s | 📦 Registros: 197
🌐 GET deputados/220651/frentes
⏱ Tempo: 0.17s | 📦 Registros: 72

Frentes dos deputados:  92%|█████████▏| 474/513 [02:01<00:08,  4.61it/s]

🌐 GET deputados/104552/frentes
⏱ Tempo: 0.18s | 📦 Registros: 228
🌐 GET deputados/220643/frentes
⏱ Tempo: 0.19s | 📦 Registros: 0

Frentes dos deputados:  93%|█████████▎| 475/513 [02:01<00:08,  4.35it/s]

🌐 GET deputados/178946/frentes
⏱ Tempo: 0.26s | 📦 Registros: 167

Frentes dos deputados:  93%|█████████▎| 476/513 [02:02<00:10,  3.62it/s]

🌐 GET deputados/178947/frentes
⏱ Tempo: 0.38s | 📦 Registros: 680

Frentes dos deputados:  93%|█████████▎| 477/513 [02:02<00:09,  3.78it/s]

🌐 GET deputados/92776/frentes
⏱ Tempo: 0.23s | 📦 Registros: 567

Frentes dos deputados:  93%|█████████▎| 478/513 [02:05<00:31,  1.11it/s]

🌐 GET deputados/204534/frentes
⏱ Tempo: 2.39s | 📦 Registros: 168

Frentes dos deputados:  93%|█████████▎| 479/513 [02:05<00:24,  1.42it/s]

🌐 GET deputados/220682/frentes
⏱ Tempo: 0.24s | 📦 Registros: 157

Frentes dos deputados:  94%|█████████▎| 480/513 [02:05<00:18,  1.75it/s]

🌐 GET deputados/204464/frentes
⏱ Tempo: 0.26s | 📦 Registros: 161
🌐 GET deputados/220598/frentes
⏱ Tempo: 0.20s | 📦 Registros: 137

Frentes dos deputados:  94%|█████████▍| 483/513 [02:06<00:09,  3.01it/s]

🌐 GET deputados/220560/frentes
⏱ Tempo: 0.22s | 📦 Registros: 90
🌐 GET deputados/220597/frentes
⏱ Tempo: 0.19s | 📦 Registros: 65

Frentes dos deputados:  94%|█████████▍| 484/513 [02:06<00:08,  3.33it/s]

🌐 GET deputados/143084/frentes
⏱ Tempo: 0.22s | 📦 Registros: 158

Frentes dos deputados:  95%|█████████▍| 486/513 [02:06<00:06,  4.06it/s]

🌐 GET deputados/220684/frentes
⏱ Tempo: 0.23s | 📦 Registros: 84
🌐 GET deputados/160976/frentes
⏱ Tempo: 0.16s | 📦 Registros: 403

Frentes dos deputados:  95%|█████████▍| 487/513 [02:07<00:06,  4.10it/s]

🌐 GET deputados/178934/frentes
⏱ Tempo: 0.23s | 📦 Registros: 557

Frentes dos deputados:  95%|█████████▌| 488/513 [02:07<00:06,  4.10it/s]

🌐 GET deputados/157130/frentes
⏱ Tempo: 0.24s | 📦 Registros: 221

Frentes dos deputados:  96%|█████████▌| 490/513 [02:07<00:05,  4.42it/s]

🌐 GET deputados/160610/frentes
⏱ Tempo: 0.25s | 📦 Registros: 746
🌐 GET deputados/74376/frentes
⏱ Tempo: 0.17s | 📦 Registros: 343

Frentes dos deputados:  96%|█████████▌| 491/513 [02:07<00:05,  4.23it/s]

🌐 GET deputados/234673/frentes
⏱ Tempo: 0.25s | 📦 Registros: 1

Frentes dos deputados:  96%|█████████▌| 492/513 [02:08<00:05,  4.09it/s]

🌐 GET deputados/235712/frentes
⏱ Tempo: 0.26s | 📦 Registros: 0

Frentes dos deputados:  96%|█████████▌| 493/513 [02:08<00:06,  2.86it/s]

🌐 GET deputados/204396/frentes
⏱ Tempo: 0.58s | 📦 Registros: 325

Frentes dos deputados:  96%|█████████▋| 494/513 [02:09<00:06,  2.96it/s]

🌐 GET deputados/137070/frentes
⏱ Tempo: 0.30s | 📦 Registros: 530

Frentes dos deputados:  97%|█████████▋| 496/513 [02:09<00:04,  3.71it/s]

🌐 GET deputados/141555/frentes
⏱ Tempo: 0.23s | 📦 Registros: 723
🌐 GET deputados/160591/frentes
⏱ Tempo: 0.18s | 📦 Registros: 111

Frentes dos deputados:  97%|█████████▋| 497/513 [02:09<00:04,  3.92it/s]

🌐 GET deputados/178992/frentes
⏱ Tempo: 0.22s | 📦 Registros: 459

Frentes dos deputados:  97%|█████████▋| 498/513 [02:09<00:03,  4.12it/s]

🌐 GET deputados/91228/frentes
⏱ Tempo: 0.21s | 📦 Registros: 49

Frentes dos deputados:  97%|█████████▋| 499/513 [02:10<00:03,  3.81it/s]

🌐 GET deputados/160569/frentes
⏱ Tempo: 0.31s | 📦 Registros: 490

Frentes dos deputados:  97%|█████████▋| 500/513 [02:10<00:03,  4.02it/s]

🌐 GET deputados/160518/frentes
⏱ Tempo: 0.21s | 📦 Registros: 705

Frentes dos deputados:  98%|█████████▊| 502/513 [02:10<00:02,  4.31it/s]

🌐 GET deputados/74043/frentes
⏱ Tempo: 0.27s | 📦 Registros: 615
🌐 GET deputados/224333/frentes
⏱ Tempo: 0.17s | 📦 Registros: 97

Frentes dos deputados:  98%|█████████▊| 504/513 [02:11<00:01,  4.59it/s]

🌐 GET deputados/74044/frentes
⏱ Tempo: 0.22s | 📦 Registros: 376
🌐 GET deputados/220564/frentes
⏱ Tempo: 0.19s | 📦 Registros: 235

Frentes dos deputados:  98%|█████████▊| 505/513 [02:11<00:01,  4.69it/s]

🌐 GET deputados/230768/frentes
⏱ Tempo: 0.20s | 📦 Registros: 7

Frentes dos deputados:  99%|█████████▊| 506/513 [02:11<00:01,  4.66it/s]

🌐 GET deputados/220536/frentes
⏱ Tempo: 0.21s | 📦 Registros: 121

Frentes dos deputados:  99%|█████████▉| 507/513 [02:12<00:01,  3.78it/s]

🌐 GET deputados/204559/frentes
⏱ Tempo: 0.37s | 📦 Registros: 277

Frentes dos deputados:  99%|█████████▉| 508/513 [02:12<00:01,  3.78it/s]

🌐 GET deputados/160632/frentes
⏱ Tempo: 0.26s | 📦 Registros: 717
🌐 GET deputados/220558/frentes
⏱ Tempo: 0.20s | 📦 Registros: 207

Frentes dos deputados:  99%|█████████▉| 510/513 [02:12<00:00,  4.07it/s]

🌐 GET deputados/204517/frentes
⏱ Tempo: 0.23s | 📦 Registros: 317

Frentes dos deputados: 100%|█████████▉| 511/513 [02:13<00:00,  3.97it/s]

🌐 GET deputados/160592/frentes
⏱ Tempo: 0.26s | 📦 Registros: 592
🌐 GET deputados/220592/frentes
⏱ Tempo: 0.20s | 📦 Registros: 197

Frentes dos deputados: 100%|██████████| 513/513 [02:13<00:00,  3.84it/s]

🌐 GET deputados/220552/frentes
⏱ Tempo: 0.20s | 📦 Registros: 188

In [ ]:
#salvar deputados e suas frentes na bronze

loader.save_bronze(
    df= df_deputadosFrentes,
    dataset = 'deputados_frentes',
    layer='bronze'
)

Arquivo salvo em: data/bronze/deputados_frentes/deputados_frentes.parquet

In [15]:
dataset = 'deputados_frentes'
df_deputadosFrentes = pd.read_parquet(path)

In [16]:
df_deputadosFrentes[df_deputadosFrentes.duplicated(subset=['source_id'],keep=False)]

Empty DataFrame
Columns: [id, uri, nomeCivil, cpf, sexo, urlWebsite, redeSocial, dataNascimento, dataFalecimento, ufNascimento, municipioNascimento, escolaridade, ultimoStatus.id, ultimoStatus.uri, ultimoStatus.nome, ultimoStatus.siglaPartido, ultimoStatus.uriPartido, ultimoStatus.siglaUf, ultimoStatus.idLegislatura, ultimoStatus.urlFoto, ultimoStatus.email, ultimoStatus.data, ultimoStatus.nomeEleitoral, ultimoStatus.gabinete.nome, ultimoStatus.gabinete.predio, ultimoStatus.gabinete.sala, ultimoStatus.gabinete.andar, ultimoStatus.gabinete.telefone, ultimoStatus.gabinete.email, ultimoStatus.situacao, ultimoStatus.condicaoEleitoral, ultimoStatus.descricaoStatus, source_id, data_extracao]
Index: []

[0 rows x 34 columns]

In [29]:
# Extração de proposições
years = [2023,2024,2025,2026]
df_proposicoes = extractor.extract_by_period(years, 
                                             endpoint_template='proposicoes?ano={year}',
                                             desc= 'Extração porposições por período')

🚀 Iniciando extração: Extração porposições por período
📅 Período: [2023, 2024, 2025, 2026]

Extração porposições por período:  25%|██▌       | 1/4 [00:03<00:10,  3.44s/it]

🌐 GET proposicoes?ano=2023
⏱ Tempo: 3.43s | 📦 Registros: 15

Extração porposições por período:  50%|█████     | 2/4 [00:06<00:06,  3.20s/it]

🌐 GET proposicoes?ano=2024
⏱ Tempo: 3.03s | 📦 Registros: 15

Extração porposições por período:  75%|███████▌  | 3/4 [00:12<00:04,  4.45s/it]

🌐 GET proposicoes?ano=2025
⏱ Tempo: 5.93s | 📦 Registros: 15

Extração porposições por período: 100%|██████████| 4/4 [00:14<00:00,  3.75s/it]

🌐 GET proposicoes?ano=2026
⏱ Tempo: 2.57s | 📦 Registros: 15
📦 Total registros: 60

In [31]:
# salvando proposiçoes

loader.save_bronze(
    df=df_proposicoes,
    dataset='proposicoes',
    layer = 'bronze'
)

💾 Salvo em: data/bronze/proposicoes/proposicoes.parquet

In [32]:
# Extração das proposições detalhadas

id_proposicoes = df_proposicoes['id']

df_proposicoesDetalhamento = extractor.extract_by_ids(
    ids=id_proposicoes,
    endpoint_template='proposicoes/{id}'
)

Extract by ID:   2%|▏         | 1/60 [00:00<00:11,  5.20it/s]

🌐 GET proposicoes/369205
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:   3%|▎         | 2/60 [00:00<00:15,  3.71it/s]

🌐 GET proposicoes/618609
⏱ Tempo: 0.32s | 📦 Registros: 1

Extract by ID:   5%|▌         | 3/60 [00:00<00:15,  3.75it/s]

🌐 GET proposicoes/1197773
⏱ Tempo: 0.26s | 📦 Registros: 1

Extract by ID:   8%|▊         | 5/60 [00:01<00:14,  3.87it/s]

🌐 GET proposicoes/1198010
⏱ Tempo: 0.35s | 📦 Registros: 1
🌐 GET proposicoes/2074843
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  12%|█▏        | 7/60 [00:01<00:12,  4.31it/s]

🌐 GET proposicoes/2115253
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET proposicoes/2345485
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  13%|█▎        | 8/60 [00:01<00:11,  4.58it/s]

🌐 GET proposicoes/2345487
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  17%|█▋        | 10/60 [00:02<00:10,  4.76it/s]

🌐 GET proposicoes/2345488
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/2345493
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  20%|██        | 12/60 [00:02<00:09,  5.08it/s]

🌐 GET proposicoes/2345494
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2345495
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  22%|██▏       | 13/60 [00:02<00:09,  4.97it/s]

🌐 GET proposicoes/2345496
⏱ Tempo: 0.21s | 📦 Registros: 1

Extract by ID:  25%|██▌       | 15/60 [00:03<00:08,  5.03it/s]

🌐 GET proposicoes/2345498
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2345501
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  27%|██▋       | 16/60 [00:03<00:09,  4.83it/s]

🌐 GET proposicoes/253500
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/510035
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  30%|███       | 18/60 [00:03<00:08,  5.02it/s]

🌐 GET proposicoes/1548579
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  33%|███▎      | 20/60 [00:04<00:08,  4.97it/s]

🌐 GET proposicoes/2092056
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/2416804
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  35%|███▌      | 21/60 [00:04<00:07,  5.01it/s]

🌐 GET proposicoes/2416813
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2416814
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  40%|████      | 24/60 [00:05<00:07,  5.00it/s]

🌐 GET proposicoes/2416819
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2416820
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  42%|████▏     | 25/60 [00:05<00:07,  4.89it/s]

🌐 GET proposicoes/2416821
⏱ Tempo: 0.21s | 📦 Registros: 1

Extract by ID:  45%|████▌     | 27/60 [00:05<00:06,  4.90it/s]

🌐 GET proposicoes/2416822
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET proposicoes/2416823
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  48%|████▊     | 29/60 [00:06<00:06,  5.03it/s]

🌐 GET proposicoes/2416824
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2416825
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  50%|█████     | 30/60 [00:06<00:05,  5.08it/s]

🌐 GET proposicoes/2416826
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  52%|█████▏    | 31/60 [00:06<00:06,  4.81it/s]

🌐 GET proposicoes/2481874
⏱ Tempo: 0.23s | 📦 Registros: 1

Extract by ID:  55%|█████▌    | 33/60 [00:07<00:05,  4.53it/s]

🌐 GET proposicoes/2481875
⏱ Tempo: 0.32s | 📦 Registros: 1
🌐 GET proposicoes/2481876
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  57%|█████▋    | 34/60 [00:07<00:05,  4.70it/s]

🌐 GET proposicoes/2481877
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  58%|█████▊    | 35/60 [00:07<00:05,  4.62it/s]

🌐 GET proposicoes/2481880
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/2481881
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  62%|██████▏   | 37/60 [00:07<00:05,  4.57it/s]

🌐 GET proposicoes/2481882
⏱ Tempo: 0.23s | 📦 Registros: 1

Extract by ID:  65%|██████▌   | 39/60 [00:08<00:04,  4.76it/s]

🌐 GET proposicoes/2481883
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2481884
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  67%|██████▋   | 40/60 [00:08<00:04,  4.89it/s]

🌐 GET proposicoes/2481885
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2481886
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  70%|███████   | 42/60 [00:08<00:03,  4.90it/s]

🌐 GET proposicoes/2481887
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  73%|███████▎  | 44/60 [00:09<00:03,  4.81it/s]

🌐 GET proposicoes/2481888
⏱ Tempo: 0.26s | 📦 Registros: 1
🌐 GET proposicoes/2481889
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  77%|███████▋  | 46/60 [00:09<00:02,  5.08it/s]

🌐 GET proposicoes/2481890
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2599885
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  80%|████████  | 48/60 [00:10<00:02,  5.21it/s]

🌐 GET proposicoes/2599886
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET proposicoes/2599888
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  82%|████████▏ | 49/60 [00:10<00:02,  5.20it/s]

🌐 GET proposicoes/2599889
⏱ Tempo: 0.19s | 📦 Registros: 1

Extract by ID:  83%|████████▎ | 50/60 [00:10<00:02,  4.98it/s]

🌐 GET proposicoes/2599890
⏱ Tempo: 0.21s | 📦 Registros: 1

Extract by ID:  87%|████████▋ | 52/60 [00:10<00:01,  4.94it/s]

🌐 GET proposicoes/2599891
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/2599892
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  88%|████████▊ | 53/60 [00:11<00:01,  5.02it/s]

🌐 GET proposicoes/2599893
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2599894
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  92%|█████████▏| 55/60 [00:11<00:01,  4.69it/s]

🌐 GET proposicoes/2599895
⏱ Tempo: 0.24s | 📦 Registros: 1

Extract by ID:  93%|█████████▎| 56/60 [00:12<00:01,  3.09it/s]

🌐 GET proposicoes/2599896
⏱ Tempo: 0.57s | 📦 Registros: 1

Extract by ID:  97%|█████████▋| 58/60 [00:12<00:00,  3.84it/s]

🌐 GET proposicoes/2599897
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET proposicoes/2599898
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  98%|█████████▊| 59/60 [00:12<00:00,  4.08it/s]

🌐 GET proposicoes/2599899
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID: 100%|██████████| 60/60 [00:13<00:00,  4.61it/s]

🌐 GET proposicoes/2599900
⏱ Tempo: 0.21s | 📦 Registros: 1

In [33]:
#salvando na bronze

loader.save_bronze(
    df= df_proposicoesDetalhamento,
    dataset='proposicoes_detalhamento',
    layer='bronze'
)

💾 Salvo em: data/bronze/proposicoes_detalhamento/proposicoes_detalhamento.parquet

In [34]:
# Extração de autores das proposicoes

df_proposicoesAutores = extractor.extract_by_ids(
    ids =id_proposicoes,
    endpoint_template='proposicoes/{id}/autores',
    desc='Extração de autores das proposicoes'
)

Extração de autores das proposicoes:   2%|▏         | 1/60 [00:00<00:16,  3.54it/s]

🌐 GET proposicoes/369205/autores
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração de autores das proposicoes:   5%|▌         | 3/60 [00:00<00:11,  4.81it/s]

🌐 GET proposicoes/618609/autores
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET proposicoes/1197773/autores
⏱ Tempo: 0.17s | 📦 Registros: 1

Extração de autores das proposicoes:   7%|▋         | 4/60 [00:00<00:12,  4.34it/s]

🌐 GET proposicoes/1198010/autores
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração de autores das proposicoes:   8%|▊         | 5/60 [00:01<00:13,  4.14it/s]

🌐 GET proposicoes/2074843/autores
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração de autores das proposicoes:  12%|█▏        | 7/60 [00:01<00:11,  4.57it/s]

🌐 GET proposicoes/2115253/autores
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2345485/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  13%|█▎        | 8/60 [00:01<00:11,  4.46it/s]

🌐 GET proposicoes/2345487/autores
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração de autores das proposicoes:  17%|█▋        | 10/60 [00:02<00:10,  4.79it/s]

🌐 GET proposicoes/2345488/autores
⏱ Tempo: 0.21s | 📦 Registros: 0
🌐 GET proposicoes/2345493/autores
⏱ Tempo: 0.17s | 📦 Registros: 1

Extração de autores das proposicoes:  20%|██        | 12/60 [00:02<00:09,  4.98it/s]

🌐 GET proposicoes/2345494/autores
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2345495/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  23%|██▎       | 14/60 [00:02<00:08,  5.15it/s]

🌐 GET proposicoes/2345496/autores
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2345498/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  25%|██▌       | 15/60 [00:03<00:08,  5.13it/s]

🌐 GET proposicoes/2345501/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  28%|██▊       | 17/60 [00:03<00:08,  4.93it/s]

🌐 GET proposicoes/253500/autores
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET proposicoes/510035/autores
⏱ Tempo: 0.16s | 📦 Registros: 1

Extração de autores das proposicoes:  30%|███       | 18/60 [00:03<00:08,  5.00it/s]

🌐 GET proposicoes/1548579/autores
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2092056/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  33%|███▎      | 20/60 [00:04<00:07,  5.10it/s]

🌐 GET proposicoes/2416804/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  37%|███▋      | 22/60 [00:04<00:07,  5.02it/s]

🌐 GET proposicoes/2416813/autores
⏱ Tempo: 0.20s | 📦 Registros: 0
🌐 GET proposicoes/2416814/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  40%|████      | 24/60 [00:04<00:06,  5.26it/s]

🌐 GET proposicoes/2416819/autores
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET proposicoes/2416820/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  42%|████▏     | 25/60 [00:05<00:06,  5.17it/s]

🌐 GET proposicoes/2416821/autores
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de autores das proposicoes:  43%|████▎     | 26/60 [00:05<00:06,  5.06it/s]

🌐 GET proposicoes/2416822/autores
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de autores das proposicoes:  45%|████▌     | 27/60 [00:05<00:07,  4.41it/s]

🌐 GET proposicoes/2416823/autores
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração de autores das proposicoes:  47%|████▋     | 28/60 [00:05<00:07,  4.33it/s]

🌐 GET proposicoes/2416824/autores
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração de autores das proposicoes:  48%|████▊     | 29/60 [00:06<00:07,  4.41it/s]

🌐 GET proposicoes/2416825/autores
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração de autores das proposicoes:  50%|█████     | 30/60 [00:06<00:06,  4.44it/s]

🌐 GET proposicoes/2416826/autores
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração de autores das proposicoes:  52%|█████▏    | 31/60 [00:06<00:08,  3.53it/s]

🌐 GET proposicoes/2481874/autores
⏱ Tempo: 0.41s | 📦 Registros: 1

Extração de autores das proposicoes:  53%|█████▎    | 32/60 [00:07<00:07,  3.61it/s]

🌐 GET proposicoes/2481875/autores
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração de autores das proposicoes:  55%|█████▌    | 33/60 [00:07<00:07,  3.85it/s]

🌐 GET proposicoes/2481876/autores
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de autores das proposicoes:  57%|█████▋    | 34/60 [00:07<00:06,  3.91it/s]

🌐 GET proposicoes/2481877/autores
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração de autores das proposicoes:  58%|█████▊    | 35/60 [00:07<00:06,  4.04it/s]

🌐 GET proposicoes/2481880/autores
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET proposicoes/2481881/autores
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de autores das proposicoes:  63%|██████▎   | 38/60 [00:08<00:04,  4.53it/s]

🌐 GET proposicoes/2481882/autores
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2481883/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  67%|██████▋   | 40/60 [00:08<00:04,  4.93it/s]

🌐 GET proposicoes/2481884/autores
⏱ Tempo: 0.17s | 📦 Registros: 1
🌐 GET proposicoes/2481885/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  70%|███████   | 42/60 [00:09<00:04,  4.38it/s]

🌐 GET proposicoes/2481886/autores
⏱ Tempo: 0.33s | 📦 Registros: 1
🌐 GET proposicoes/2481887/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  73%|███████▎  | 44/60 [00:09<00:03,  4.74it/s]

🌐 GET proposicoes/2481888/autores
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/2481889/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  77%|███████▋  | 46/60 [00:10<00:02,  4.79it/s]

🌐 GET proposicoes/2481890/autores
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET proposicoes/2599885/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  80%|████████  | 48/60 [00:10<00:02,  5.06it/s]

🌐 GET proposicoes/2599886/autores
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2599888/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  83%|████████▎ | 50/60 [00:10<00:02,  4.75it/s]

🌐 GET proposicoes/2599889/autores
⏱ Tempo: 0.26s | 📦 Registros: 0
🌐 GET proposicoes/2599890/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  87%|████████▋ | 52/60 [00:11<00:01,  4.54it/s]

🌐 GET proposicoes/2599891/autores
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET proposicoes/2599892/autores
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de autores das proposicoes:  90%|█████████ | 54/60 [00:11<00:01,  4.66it/s]

🌐 GET proposicoes/2599893/autores
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET proposicoes/2599894/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  92%|█████████▏| 55/60 [00:11<00:01,  4.91it/s]

🌐 GET proposicoes/2599895/autores
⏱ Tempo: 0.17s | 📦 Registros: 1

Extração de autores das proposicoes:  95%|█████████▌| 57/60 [00:12<00:00,  4.91it/s]

🌐 GET proposicoes/2599896/autores
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET proposicoes/2599897/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração de autores das proposicoes:  97%|█████████▋| 58/60 [00:12<00:00,  4.40it/s]

🌐 GET proposicoes/2599898/autores
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET proposicoes/2599899/autores
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de autores das proposicoes: 100%|██████████| 60/60 [00:13<00:00,  4.59it/s]

🌐 GET proposicoes/2599900/autores
⏱ Tempo: 0.18s | 📦 Registros: 1

In [35]:
#salvando na bronze 
loader.save_bronze(
    df=df_proposicoesAutores,
    dataset='proposicoes_autores'

)

💾 Salvo em: data/bronze/proposicoes_autores/proposicoes_autores.parquet

In [37]:
# Extração de temas das proposições
df_proposicoesTemas = extractor.extract_by_ids(
    ids=id_proposicoes,
    endpoint_template='proposicoes/{id}/temas',
    desc='Extração de temas das proposiçoes'
)

Extração de temas das proposiçoes:   3%|▎         | 2/60 [00:00<00:12,  4.55it/s]

🌐 GET proposicoes/369205/temas
⏱ Tempo: 0.25s | 📦 Registros: 2
🌐 GET proposicoes/618609/temas
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração de temas das proposiçoes:   5%|▌         | 3/60 [00:00<00:11,  4.82it/s]

🌐 GET proposicoes/1197773/temas
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET proposicoes/1198010/temas
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de temas das proposiçoes:   8%|▊         | 5/60 [00:01<00:11,  4.86it/s]

🌐 GET proposicoes/2074843/temas
⏱ Tempo: 0.20s | 📦 Registros: 2
🌐 GET proposicoes/2115253/temas
⏱ Tempo: 0.20s | 📦 Registros: 2

Extração de temas das proposiçoes:  13%|█▎        | 8/60 [00:01<00:10,  5.06it/s]

🌐 GET proposicoes/2345485/temas
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET proposicoes/2345487/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  17%|█▋        | 10/60 [00:01<00:09,  5.44it/s]

🌐 GET proposicoes/2345488/temas
⏱ Tempo: 0.17s | 📦 Registros: 0
🌐 GET proposicoes/2345493/temas
⏱ Tempo: 0.17s | 📦 Registros: 1

Extração de temas das proposiçoes:  20%|██        | 12/60 [00:02<00:08,  5.34it/s]

🌐 GET proposicoes/2345494/temas
⏱ Tempo: 0.19s | 📦 Registros: 2
🌐 GET proposicoes/2345495/temas
⏱ Tempo: 0.18s | 📦 Registros: 2

Extração de temas das proposiçoes:  22%|██▏       | 13/60 [00:02<00:08,  5.32it/s]

🌐 GET proposicoes/2345496/temas
⏱ Tempo: 0.19s | 📦 Registros: 2

Extração de temas das proposiçoes:  25%|██▌       | 15/60 [00:03<00:10,  4.22it/s]

🌐 GET proposicoes/2345498/temas
⏱ Tempo: 0.41s | 📦 Registros: 2
🌐 GET proposicoes/2345501/temas
⏱ Tempo: 0.19s | 📦 Registros: 0

Extração de temas das proposiçoes:  27%|██▋       | 16/60 [00:03<00:10,  4.33it/s]

🌐 GET proposicoes/253500/temas
⏱ Tempo: 0.21s | 📦 Registros: 2

Extração de temas das proposiçoes:  28%|██▊       | 17/60 [00:03<00:09,  4.47it/s]

🌐 GET proposicoes/510035/temas
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET proposicoes/1548579/temas
⏱ Tempo: 0.20s | 📦 Registros: 2

Extração de temas das proposiçoes:  33%|███▎      | 20/60 [00:04<00:07,  5.14it/s]

🌐 GET proposicoes/2092056/temas
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET proposicoes/2416804/temas
⏱ Tempo: 0.16s | 📦 Registros: 3

Extração de temas das proposiçoes:  37%|███▋      | 22/60 [00:04<00:06,  5.50it/s]

🌐 GET proposicoes/2416813/temas
⏱ Tempo: 0.18s | 📦 Registros: 0
🌐 GET proposicoes/2416814/temas
⏱ Tempo: 0.16s | 📦 Registros: 0

Extração de temas das proposiçoes:  38%|███▊      | 23/60 [00:04<00:07,  4.76it/s]

🌐 GET proposicoes/2416819/temas
⏱ Tempo: 0.27s | 📦 Registros: 0
🌐 GET proposicoes/2416820/temas
⏱ Tempo: 0.20s | 📦 Registros: 0

Extração de temas das proposiçoes:  42%|████▏     | 25/60 [00:05<00:07,  4.79it/s]

🌐 GET proposicoes/2416821/temas
⏱ Tempo: 0.21s | 📦 Registros: 0

Extração de temas das proposiçoes:  43%|████▎     | 26/60 [00:05<00:07,  4.78it/s]

🌐 GET proposicoes/2416822/temas
⏱ Tempo: 0.20s | 📦 Registros: 0

Extração de temas das proposiçoes:  47%|████▋     | 28/60 [00:05<00:06,  4.81it/s]

🌐 GET proposicoes/2416823/temas
⏱ Tempo: 0.21s | 📦 Registros: 0
🌐 GET proposicoes/2416824/temas
⏱ Tempo: 0.19s | 📦 Registros: 0

Extração de temas das proposiçoes:  48%|████▊     | 29/60 [00:05<00:06,  4.97it/s]

🌐 GET proposicoes/2416825/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  50%|█████     | 30/60 [00:06<00:06,  4.85it/s]

🌐 GET proposicoes/2416826/temas
⏱ Tempo: 0.21s | 📦 Registros: 2

Extração de temas das proposiçoes:  53%|█████▎    | 32/60 [00:06<00:05,  4.75it/s]

🌐 GET proposicoes/2481874/temas
⏱ Tempo: 0.24s | 📦 Registros: 2
🌐 GET proposicoes/2481875/temas
⏱ Tempo: 0.19s | 📦 Registros: 2

Extração de temas das proposiçoes:  55%|█████▌    | 33/60 [00:06<00:05,  4.95it/s]

🌐 GET proposicoes/2481876/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  58%|█████▊    | 35/60 [00:07<00:04,  5.03it/s]

🌐 GET proposicoes/2481877/temas
⏱ Tempo: 0.21s | 📦 Registros: 0
🌐 GET proposicoes/2481880/temas
⏱ Tempo: 0.18s | 📦 Registros: 4

Extração de temas das proposiçoes:  62%|██████▏   | 37/60 [00:07<00:04,  5.08it/s]

🌐 GET proposicoes/2481881/temas
⏱ Tempo: 0.20s | 📦 Registros: 0
🌐 GET proposicoes/2481882/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  65%|██████▌   | 39/60 [00:08<00:04,  5.12it/s]

🌐 GET proposicoes/2481883/temas
⏱ Tempo: 0.20s | 📦 Registros: 0
🌐 GET proposicoes/2481884/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  68%|██████▊   | 41/60 [00:08<00:03,  5.22it/s]

🌐 GET proposicoes/2481885/temas
⏱ Tempo: 0.19s | 📦 Registros: 0
🌐 GET proposicoes/2481886/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  72%|███████▏  | 43/60 [00:08<00:03,  5.36it/s]

🌐 GET proposicoes/2481887/temas
⏱ Tempo: 0.18s | 📦 Registros: 0
🌐 GET proposicoes/2481888/temas
⏱ Tempo: 0.18s | 📦 Registros: 0

Extração de temas das proposiçoes:  73%|███████▎  | 44/60 [00:08<00:02,  5.47it/s]

🌐 GET proposicoes/2481889/temas
⏱ Tempo: 0.17s | 📦 Registros: 0

Extração de temas das proposiçoes:  75%|███████▌  | 45/60 [00:09<00:02,  5.01it/s]

🌐 GET proposicoes/2481890/temas
⏱ Tempo: 0.24s | 📦 Registros: 0
🌐 GET proposicoes/2599885/temas
⏱ Tempo: 0.20s | 📦 Registros: 3

Extração de temas das proposiçoes:  78%|███████▊  | 47/60 [00:09<00:02,  5.00it/s]

🌐 GET proposicoes/2599886/temas
⏱ Tempo: 0.19s | 📦 Registros: 0
🌐 GET proposicoes/2599888/temas
⏱ Tempo: 0.20s | 📦 Registros: 3

Extração de temas das proposiçoes:  82%|████████▏ | 49/60 [00:09<00:02,  4.95it/s]

🌐 GET proposicoes/2599889/temas
⏱ Tempo: 0.20s | 📦 Registros: 0

Extração de temas das proposiçoes:  83%|████████▎ | 50/60 [00:10<00:02,  4.91it/s]

🌐 GET proposicoes/2599890/temas
⏱ Tempo: 0.20s | 📦 Registros: 2
🌐 GET proposicoes/2599891/temas
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração de temas das proposiçoes:  88%|████████▊ | 53/60 [00:10<00:01,  5.15it/s]

🌐 GET proposicoes/2599892/temas
⏱ Tempo: 0.18s | 📦 Registros: 3
🌐 GET proposicoes/2599893/temas
⏱ Tempo: 0.18s | 📦 Registros: 2

Extração de temas das proposiçoes:  92%|█████████▏| 55/60 [00:11<00:00,  5.11it/s]

🌐 GET proposicoes/2599894/temas
⏱ Tempo: 0.20s | 📦 Registros: 3
🌐 GET proposicoes/2599895/temas
⏱ Tempo: 0.19s | 📦 Registros: 2

Extração de temas das proposiçoes:  95%|█████████▌| 57/60 [00:14<00:03,  1.07s/it]

🌐 GET proposicoes/2599896/temas
⏱ Tempo: 0.17s | 📦 Registros: 2
🌐 GET proposicoes/2599897/temas
⏱ Tempo: 3.12s | 📦 Registros: 2

Extração de temas das proposiçoes:  97%|█████████▋| 58/60 [00:14<00:01,  1.25it/s]

🌐 GET proposicoes/2599898/temas
⏱ Tempo: 0.16s | 📦 Registros: 1

Extração de temas das proposiçoes:  98%|█████████▊| 59/60 [00:14<00:00,  1.61it/s]

🌐 GET proposicoes/2599899/temas
⏱ Tempo: 0.20s | 📦 Registros: 0

Extração de temas das proposiçoes: 100%|██████████| 60/60 [00:15<00:00,  3.99it/s]

🌐 GET proposicoes/2599900/temas
⏱ Tempo: 0.20s | 📦 Registros: 0

In [38]:
loader.save_bronze(
    df=df_proposicoesTemas,
    dataset='proposicoes_temas'
)

💾 Salvo em: data/bronze/proposicoes_temas/proposicoes_temas.parquet

In [39]:
#extração de votações de proposicoes

df_proposicoesVotacoes = extractor.extract_by_ids(
    ids=id_proposicoes,
    endpoint_template='proposicoes/{id}/votacoes'
)

Extract by ID:   2%|▏         | 1/60 [00:01<01:14,  1.27s/it]

🌐 GET proposicoes/369205/votacoes
⏱ Tempo: 1.26s | 📦 Registros: 8

Extract by ID:   3%|▎         | 2/60 [00:02<01:17,  1.34s/it]

🌐 GET proposicoes/618609/votacoes
⏱ Tempo: 1.38s | 📦 Registros: 4

Extract by ID:   5%|▌         | 3/60 [00:04<01:25,  1.49s/it]

🌐 GET proposicoes/1197773/votacoes
⏱ Tempo: 1.67s | 📦 Registros: 13

Extract by ID:   7%|▋         | 4/60 [00:05<01:22,  1.47s/it]

🌐 GET proposicoes/1198010/votacoes
⏱ Tempo: 1.43s | 📦 Registros: 12

Extract by ID:   8%|▊         | 5/60 [00:08<01:43,  1.88s/it]

🌐 GET proposicoes/2074843/votacoes
⏱ Tempo: 2.60s | 📦 Registros: 7

Extract by ID:  10%|█         | 6/60 [00:09<01:31,  1.70s/it]

🌐 GET proposicoes/2115253/votacoes
⏱ Tempo: 1.34s | 📦 Registros: 17

Extract by ID:  12%|█▏        | 7/60 [00:11<01:28,  1.67s/it]

🌐 GET proposicoes/2345485/votacoes
⏱ Tempo: 1.61s | 📦 Registros: 0

Extract by ID:  13%|█▎        | 8/60 [00:12<01:20,  1.55s/it]

🌐 GET proposicoes/2345487/votacoes
⏱ Tempo: 1.30s | 📦 Registros: 0

Extract by ID:  15%|█▌        | 9/60 [00:14<01:19,  1.57s/it]

🌐 GET proposicoes/2345488/votacoes
⏱ Tempo: 1.59s | 📦 Registros: 0

Extract by ID:  17%|█▋        | 10/60 [00:17<01:50,  2.21s/it]

🌐 GET proposicoes/2345493/votacoes
⏱ Tempo: 3.65s | 📦 Registros: 12

Extract by ID:  18%|█▊        | 11/60 [00:20<01:58,  2.43s/it]

🌐 GET proposicoes/2345494/votacoes
⏱ Tempo: 2.91s | 📦 Registros: 0

Extract by ID:  20%|██        | 12/60 [00:22<01:40,  2.09s/it]

🌐 GET proposicoes/2345495/votacoes
⏱ Tempo: 1.31s | 📦 Registros: 1

Extract by ID:  22%|██▏       | 13/60 [00:24<01:45,  2.24s/it]

🌐 GET proposicoes/2345496/votacoes
⏱ Tempo: 2.59s | 📦 Registros: 0

Extract by ID:  23%|██▎       | 14/60 [00:26<01:32,  2.02s/it]

🌐 GET proposicoes/2345498/votacoes
⏱ Tempo: 1.48s | 📦 Registros: 3

Extract by ID:  25%|██▌       | 15/60 [00:28<01:30,  2.01s/it]

🌐 GET proposicoes/2345501/votacoes
⏱ Tempo: 1.99s | 📦 Registros: 6

Extract by ID:  27%|██▋       | 16/60 [00:33<02:11,  2.98s/it]

🌐 GET proposicoes/253500/votacoes
⏱ Tempo: 5.23s | 📦 Registros: 103

Extract by ID:  28%|██▊       | 17/60 [00:36<02:12,  3.09s/it]

🌐 GET proposicoes/510035/votacoes
⏱ Tempo: 3.34s | 📦 Registros: 6

Extract by ID:  30%|███       | 18/60 [00:38<01:50,  2.64s/it]

🌐 GET proposicoes/1548579/votacoes
⏱ Tempo: 1.58s | 📦 Registros: 40

Extract by ID:  32%|███▏      | 19/60 [00:42<02:04,  3.05s/it]

🌐 GET proposicoes/2092056/votacoes
⏱ Tempo: 3.99s | 📦 Registros: 7

Extract by ID:  33%|███▎      | 20/60 [00:45<02:00,  3.01s/it]

🌐 GET proposicoes/2416804/votacoes
⏱ Tempo: 2.93s | 📦 Registros: 6

Extract by ID:  35%|███▌      | 21/60 [00:47<01:42,  2.64s/it]

🌐 GET proposicoes/2416813/votacoes
⏱ Tempo: 1.75s | 📦 Registros: 0

Extract by ID:  37%|███▋      | 22/60 [00:48<01:29,  2.37s/it]

🌐 GET proposicoes/2416814/votacoes
⏱ Tempo: 1.73s | 📦 Registros: 0

Extract by ID:  38%|███▊      | 23/60 [00:50<01:23,  2.26s/it]

🌐 GET proposicoes/2416819/votacoes
⏱ Tempo: 2.02s | 📦 Registros: 0

Extract by ID:  40%|████      | 24/60 [00:52<01:16,  2.14s/it]

🌐 GET proposicoes/2416820/votacoes
⏱ Tempo: 1.84s | 📦 Registros: 0

Extract by ID:  42%|████▏     | 25/60 [00:55<01:25,  2.45s/it]

🌐 GET proposicoes/2416821/votacoes
⏱ Tempo: 3.17s | 📦 Registros: 0

Extract by ID:  43%|████▎     | 26/60 [00:57<01:17,  2.27s/it]

🌐 GET proposicoes/2416822/votacoes
⏱ Tempo: 1.85s | 📦 Registros: 0

Extract by ID:  45%|████▌     | 27/60 [00:59<01:07,  2.04s/it]

🌐 GET proposicoes/2416823/votacoes
⏱ Tempo: 1.50s | 📦 Registros: 0

Extract by ID:  47%|████▋     | 28/60 [01:01<01:08,  2.15s/it]

🌐 GET proposicoes/2416824/votacoes
⏱ Tempo: 2.39s | 📦 Registros: 0

Extract by ID:  48%|████▊     | 29/60 [01:03<01:05,  2.12s/it]

🌐 GET proposicoes/2416825/votacoes
⏱ Tempo: 2.05s | 📦 Registros: 0

Extract by ID:  50%|█████     | 30/60 [01:11<01:56,  3.88s/it]

🌐 GET proposicoes/2416826/votacoes
⏱ Tempo: 7.97s | 📦 Registros: 4

Extract by ID:  52%|█████▏    | 31/60 [01:13<01:31,  3.15s/it]

🌐 GET proposicoes/2481874/votacoes
⏱ Tempo: 1.44s | 📦 Registros: 8

Extract by ID:  53%|█████▎    | 32/60 [01:16<01:29,  3.18s/it]

🌐 GET proposicoes/2481875/votacoes
⏱ Tempo: 3.25s | 📦 Registros: 8

Extract by ID:  55%|█████▌    | 33/60 [01:21<01:41,  3.77s/it]

🌐 GET proposicoes/2481876/votacoes
⏱ Tempo: 5.13s | 📦 Registros: 1

Extract by ID:  57%|█████▋    | 34/60 [01:22<01:19,  3.05s/it]

🌐 GET proposicoes/2481877/votacoes
⏱ Tempo: 1.39s | 📦 Registros: 0

Extract by ID:  58%|█████▊    | 35/60 [01:24<01:06,  2.64s/it]

🌐 GET proposicoes/2481880/votacoes
⏱ Tempo: 1.68s | 📦 Registros: 0

Extract by ID:  60%|██████    | 36/60 [01:27<01:03,  2.63s/it]

🌐 GET proposicoes/2481881/votacoes
⏱ Tempo: 2.59s | 📦 Registros: 0

Extract by ID:  62%|██████▏   | 37/60 [01:29<00:57,  2.50s/it]

🌐 GET proposicoes/2481882/votacoes
⏱ Tempo: 2.18s | 📦 Registros: 1

Extract by ID:  63%|██████▎   | 38/60 [01:30<00:48,  2.20s/it]

🌐 GET proposicoes/2481883/votacoes
⏱ Tempo: 1.50s | 📦 Registros: 0

Extract by ID:  65%|██████▌   | 39/60 [01:32<00:41,  2.00s/it]

🌐 GET proposicoes/2481884/votacoes
⏱ Tempo: 1.51s | 📦 Registros: 1

Extract by ID:  67%|██████▋   | 40/60 [01:34<00:38,  1.92s/it]

🌐 GET proposicoes/2481885/votacoes
⏱ Tempo: 1.72s | 📦 Registros: 0

Extract by ID:  68%|██████▊   | 41/60 [01:35<00:33,  1.77s/it]

🌐 GET proposicoes/2481886/votacoes
⏱ Tempo: 1.41s | 📦 Registros: 1

Extract by ID:  70%|███████   | 42/60 [01:37<00:31,  1.77s/it]

🌐 GET proposicoes/2481887/votacoes
⏱ Tempo: 1.77s | 📦 Registros: 0

Extract by ID:  72%|███████▏  | 43/60 [01:38<00:29,  1.72s/it]

🌐 GET proposicoes/2481888/votacoes
⏱ Tempo: 1.61s | 📦 Registros: 1

Extract by ID:  73%|███████▎  | 44/60 [01:43<00:41,  2.59s/it]

🌐 GET proposicoes/2481889/votacoes
⏱ Tempo: 4.62s | 📦 Registros: 0

Extract by ID:  75%|███████▌  | 45/60 [01:46<00:42,  2.81s/it]

🌐 GET proposicoes/2481890/votacoes
⏱ Tempo: 3.30s | 📦 Registros: 1

Extract by ID:  77%|███████▋  | 46/60 [01:49<00:38,  2.77s/it]

🌐 GET proposicoes/2599885/votacoes
⏱ Tempo: 2.67s | 📦 Registros: 0

Extract by ID:  78%|███████▊  | 47/60 [01:52<00:35,  2.74s/it]

🌐 GET proposicoes/2599886/votacoes
⏱ Tempo: 2.68s | 📦 Registros: 0

Extract by ID:  80%|████████  | 48/60 [01:54<00:29,  2.48s/it]

🌐 GET proposicoes/2599888/votacoes
⏱ Tempo: 1.87s | 📦 Registros: 0

Extract by ID:  82%|████████▏ | 49/60 [01:56<00:25,  2.34s/it]

🌐 GET proposicoes/2599889/votacoes
⏱ Tempo: 2.00s | 📦 Registros: 0

Extract by ID:  83%|████████▎ | 50/60 [01:58<00:22,  2.24s/it]

🌐 GET proposicoes/2599890/votacoes
⏱ Tempo: 2.00s | 📦 Registros: 0

Extract by ID:  85%|████████▌ | 51/60 [01:59<00:19,  2.12s/it]

🌐 GET proposicoes/2599891/votacoes
⏱ Tempo: 1.85s | 📦 Registros: 0

Extract by ID:  87%|████████▋ | 52/60 [02:01<00:16,  2.01s/it]

🌐 GET proposicoes/2599892/votacoes
⏱ Tempo: 1.75s | 📦 Registros: 0

Extract by ID:  88%|████████▊ | 53/60 [02:05<00:17,  2.45s/it]

🌐 GET proposicoes/2599893/votacoes
⏱ Tempo: 3.46s | 📦 Registros: 0

Extract by ID:  90%|█████████ | 54/60 [02:06<00:13,  2.26s/it]

🌐 GET proposicoes/2599894/votacoes
⏱ Tempo: 1.81s | 📦 Registros: 0

Extract by ID:  92%|█████████▏| 55/60 [02:08<00:10,  2.19s/it]

🌐 GET proposicoes/2599895/votacoes
⏱ Tempo: 2.02s | 📦 Registros: 0

Extract by ID:  93%|█████████▎| 56/60 [02:11<00:08,  2.24s/it]

🌐 GET proposicoes/2599896/votacoes
⏱ Tempo: 2.36s | 📦 Registros: 0

Extract by ID:  95%|█████████▌| 57/60 [02:13<00:06,  2.08s/it]

🌐 GET proposicoes/2599897/votacoes
⏱ Tempo: 1.69s | 📦 Registros: 0

Extract by ID:  97%|█████████▋| 58/60 [02:17<00:05,  2.89s/it]

🌐 GET proposicoes/2599898/votacoes
⏱ Tempo: 4.78s | 📦 Registros: 0

Extract by ID:  98%|█████████▊| 59/60 [02:19<00:02,  2.56s/it]

🌐 GET proposicoes/2599899/votacoes
⏱ Tempo: 1.78s | 📦 Registros: 0

Extract by ID: 100%|██████████| 60/60 [02:23<00:00,  2.39s/it]

🌐 GET proposicoes/2599900/votacoes
⏱ Tempo: 3.85s | 📦 Registros: 0

In [40]:
loader.save_bronze(
    df=df_proposicoesVotacoes,
    dataset='proposicoes_votacoes',
)

💾 Salvo em: data/bronze/proposicoes_votacoes/proposicoes_votacoes.parquet

In [41]:
df_partidos = extractor.extract(
    endpoint='/partidos',
    desc='Extracão de partidos'
)

🚀 Iniciando extração: Extracão de partidos
🌐 GET /partidos
⏱ Tempo: 2.89s | 📦 Registros: 15
📦 Registros extraídos: 15

In [42]:
loader.save_bronze(
    df=df_partidos,
    dataset='partidos'
)

💾 Salvo em: data/bronze/partidos/partidos.parquet

In [43]:
ids_partidos = df_partidos['id']
df_partidosDetalhamento = extractor.extract_by_ids(
    ids=ids_partidos,
    endpoint_template='partidos/{id}'
)

Extract by ID:  13%|█▎        | 2/15 [00:00<00:02,  5.45it/s]

🌐 GET partidos/36898
⏱ Tempo: 0.18s | 📦 Registros: 1
🌐 GET partidos/37905
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  20%|██        | 3/15 [00:00<00:02,  5.10it/s]

🌐 GET partidos/36899
⏱ Tempo: 0.21s | 📦 Registros: 1

Extract by ID:  27%|██▋       | 4/15 [00:00<00:02,  4.49it/s]

🌐 GET partidos/38011
⏱ Tempo: 0.26s | 📦 Registros: 1

Extract by ID:  33%|███▎      | 5/15 [00:01<00:02,  4.58it/s]

🌐 GET partidos/37901
⏱ Tempo: 0.20s | 📦 Registros: 1

Extract by ID:  47%|████▋     | 7/15 [00:01<00:01,  4.61it/s]

🌐 GET partidos/36779
⏱ Tempo: 0.26s | 📦 Registros: 1
🌐 GET partidos/36786
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  60%|██████    | 9/15 [00:01<00:01,  4.95it/s]

🌐 GET partidos/37906
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET partidos/36896
⏱ Tempo: 0.17s | 📦 Registros: 1

Extract by ID:  67%|██████▋   | 10/15 [00:02<00:00,  5.12it/s]

🌐 GET partidos/37903
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  80%|████████  | 12/15 [00:02<00:00,  4.91it/s]

🌐 GET partidos/38010
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET partidos/36832
⏱ Tempo: 0.18s | 📦 Registros: 1

Extract by ID:  87%|████████▋ | 13/15 [00:02<00:00,  4.61it/s]

🌐 GET partidos/36834
⏱ Tempo: 0.24s | 📦 Registros: 1

Extract by ID:  93%|█████████▎| 14/15 [00:02<00:00,  4.52it/s]

🌐 GET partidos/36835
⏱ Tempo: 0.23s | 📦 Registros: 1

Extract by ID: 100%|██████████| 15/15 [00:03<00:00,  4.66it/s]

🌐 GET partidos/36839
⏱ Tempo: 0.23s | 📦 Registros: 1

In [44]:
loader.save_bronze(
    df=df_partidosDetalhamento,
    dataset='partidos_detalhamento'
)

💾 Salvo em: data/bronze/partidos_detalhamento/partidos_detalhamento.parquet

In [46]:
df_frentes = extractor.extract(endpoint='frentes',desc='Extração frentes')

🚀 Iniciando extração: Extração frentes
🌐 GET frentes
⏱ Tempo: 0.19s | 📦 Registros: 100
📦 Registros extraídos: 100

In [47]:
loader.save_bronze(
    df=df_frentes,
    dataset='frentes'
)

💾 Salvo em: data/bronze/frentes/frentes.parquet

In [48]:
ids_frentes = df_frentes['id']

df_frentesDetalhamento = extractor.extract_by_ids(
    ids=ids_frentes,
    endpoint_template='frentes/{id}',
    desc= 'Extração detalhamento frentes'
)

Extração detalhamento frentes:   1%|          | 1/100 [00:00<00:31,  3.19it/s]

🌐 GET frentes/55688
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento frentes:   2%|▏         | 2/100 [00:00<00:29,  3.32it/s]

🌐 GET frentes/55699
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento frentes:   3%|▎         | 3/100 [00:00<00:32,  3.03it/s]

🌐 GET frentes/55644
⏱ Tempo: 0.36s | 📦 Registros: 1

Extração detalhamento frentes:   4%|▍         | 4/100 [00:01<00:32,  2.93it/s]

🌐 GET frentes/55711
⏱ Tempo: 0.36s | 📦 Registros: 1

Extração detalhamento frentes:   5%|▌         | 5/100 [00:01<00:29,  3.18it/s]

🌐 GET frentes/55710
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:   6%|▌         | 6/100 [00:01<00:31,  2.96it/s]

🌐 GET frentes/55708
⏱ Tempo: 0.38s | 📦 Registros: 1

Extração detalhamento frentes:   7%|▋         | 7/100 [00:02<00:29,  3.20it/s]

🌐 GET frentes/55712
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:   8%|▊         | 8/100 [00:02<00:28,  3.23it/s]

🌐 GET frentes/55705
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:   9%|▉         | 9/100 [00:02<00:26,  3.47it/s]

🌐 GET frentes/55704
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  10%|█         | 10/100 [00:03<00:24,  3.64it/s]

🌐 GET frentes/55692
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  11%|█         | 11/100 [00:03<00:24,  3.67it/s]

🌐 GET frentes/55680
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  12%|█▏        | 12/100 [00:03<00:23,  3.70it/s]

🌐 GET frentes/55701
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  13%|█▎        | 13/100 [00:03<00:23,  3.70it/s]

🌐 GET frentes/55700
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  14%|█▍        | 14/100 [00:04<00:22,  3.76it/s]

🌐 GET frentes/55702
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  15%|█▌        | 15/100 [00:04<00:22,  3.75it/s]

🌐 GET frentes/55695
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  16%|█▌        | 16/100 [00:04<00:24,  3.50it/s]

🌐 GET frentes/55697
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento frentes:  17%|█▋        | 17/100 [00:04<00:23,  3.53it/s]

🌐 GET frentes/55686
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  18%|█▊        | 18/100 [00:05<00:23,  3.56it/s]

🌐 GET frentes/55595
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  19%|█▉        | 19/100 [00:05<00:24,  3.28it/s]

🌐 GET frentes/55645
⏱ Tempo: 0.35s | 📦 Registros: 1

Extração detalhamento frentes:  20%|██        | 20/100 [00:05<00:23,  3.45it/s]

🌐 GET frentes/55662
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  21%|██        | 21/100 [00:06<00:21,  3.62it/s]

🌐 GET frentes/55687
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  22%|██▏       | 22/100 [00:06<00:20,  3.75it/s]

🌐 GET frentes/55671
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  23%|██▎       | 23/100 [00:06<00:20,  3.73it/s]

🌐 GET frentes/55672
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  24%|██▍       | 24/100 [00:06<00:19,  3.83it/s]

🌐 GET frentes/55618
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  25%|██▌       | 25/100 [00:07<00:19,  3.84it/s]

🌐 GET frentes/55681
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  26%|██▌       | 26/100 [00:07<00:18,  3.93it/s]

🌐 GET frentes/55606
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento frentes:  27%|██▋       | 27/100 [00:07<00:18,  3.87it/s]

🌐 GET frentes/55649
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  28%|██▊       | 28/100 [00:07<00:18,  3.96it/s]

🌐 GET frentes/55670
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento frentes:  29%|██▉       | 29/100 [00:08<00:17,  4.01it/s]

🌐 GET frentes/55653
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  30%|███       | 30/100 [00:08<00:17,  4.01it/s]

🌐 GET frentes/55667
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  31%|███       | 31/100 [00:08<00:17,  4.02it/s]

🌐 GET frentes/55637
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  32%|███▏      | 32/100 [00:08<00:18,  3.69it/s]

🌐 GET frentes/55605
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento frentes:  33%|███▎      | 33/100 [00:09<00:18,  3.68it/s]

🌐 GET frentes/55655
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  34%|███▍      | 34/100 [00:09<00:17,  3.74it/s]

🌐 GET frentes/55669
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  35%|███▌      | 35/100 [00:09<00:18,  3.49it/s]

🌐 GET frentes/55656
⏱ Tempo: 0.33s | 📦 Registros: 1

Extração detalhamento frentes:  36%|███▌      | 36/100 [00:10<00:18,  3.41it/s]

🌐 GET frentes/55660
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:  37%|███▋      | 37/100 [00:10<00:17,  3.51it/s]

🌐 GET frentes/55641
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  38%|███▊      | 38/100 [00:10<00:17,  3.53it/s]

🌐 GET frentes/55638
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  39%|███▉      | 39/100 [00:10<00:16,  3.68it/s]

🌐 GET frentes/55652
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  40%|████      | 40/100 [00:11<00:18,  3.21it/s]

🌐 GET frentes/55647
⏱ Tempo: 0.39s | 📦 Registros: 1

Extração detalhamento frentes:  41%|████      | 41/100 [00:11<00:17,  3.33it/s]

🌐 GET frentes/55651
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  42%|████▏     | 42/100 [00:11<00:17,  3.25it/s]

🌐 GET frentes/55650
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento frentes:  43%|████▎     | 43/100 [00:12<00:16,  3.46it/s]

🌐 GET frentes/55628
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  44%|████▍     | 44/100 [00:12<00:16,  3.31it/s]

🌐 GET frentes/55640
⏱ Tempo: 0.33s | 📦 Registros: 1

Extração detalhamento frentes:  45%|████▌     | 45/100 [00:12<00:18,  2.98it/s]

🌐 GET frentes/55634
⏱ Tempo: 0.41s | 📦 Registros: 1

Extração detalhamento frentes:  46%|████▌     | 46/100 [00:13<00:19,  2.72it/s]

🌐 GET frentes/55639
⏱ Tempo: 0.44s | 📦 Registros: 1

Extração detalhamento frentes:  47%|████▋     | 47/100 [00:13<00:17,  2.95it/s]

🌐 GET frentes/55622
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  48%|████▊     | 48/100 [00:13<00:18,  2.85it/s]

🌐 GET frentes/55625
⏱ Tempo: 0.37s | 📦 Registros: 1

Extração detalhamento frentes:  49%|████▉     | 49/100 [00:14<00:16,  3.13it/s]

🌐 GET frentes/55629
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  50%|█████     | 50/100 [00:14<00:15,  3.32it/s]

🌐 GET frentes/55636
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  51%|█████     | 51/100 [00:14<00:14,  3.47it/s]

🌐 GET frentes/55614
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  52%|█████▏    | 52/100 [00:15<00:15,  3.14it/s]

🌐 GET frentes/55604
⏱ Tempo: 0.38s | 📦 Registros: 1

Extração detalhamento frentes:  53%|█████▎    | 53/100 [00:15<00:14,  3.34it/s]

🌐 GET frentes/55619
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  54%|█████▍    | 54/100 [00:15<00:13,  3.39it/s]

🌐 GET frentes/55621
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  55%|█████▌    | 55/100 [00:15<00:13,  3.40it/s]

🌐 GET frentes/55607
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento frentes:  56%|█████▌    | 56/100 [00:16<00:13,  3.23it/s]

🌐 GET frentes/55582
⏱ Tempo: 0.34s | 📦 Registros: 1

Extração detalhamento frentes:  57%|█████▋    | 57/100 [00:16<00:12,  3.41it/s]

🌐 GET frentes/55603
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  58%|█████▊    | 58/100 [00:16<00:12,  3.36it/s]

🌐 GET frentes/54486
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:  59%|█████▉    | 59/100 [00:17<00:12,  3.31it/s]

🌐 GET frentes/55594
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento frentes:  60%|██████    | 60/100 [00:17<00:12,  3.22it/s]

🌐 GET frentes/54561
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento frentes:  61%|██████    | 61/100 [00:17<00:11,  3.32it/s]

🌐 GET frentes/55601
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  62%|██████▏   | 62/100 [00:18<00:10,  3.54it/s]

🌐 GET frentes/55597
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  63%|██████▎   | 63/100 [00:18<00:10,  3.61it/s]

🌐 GET frentes/55587
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  64%|██████▍   | 64/100 [00:18<00:09,  3.65it/s]

🌐 GET frentes/55599
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  65%|██████▌   | 65/100 [00:18<00:09,  3.50it/s]

🌐 GET frentes/55598
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento frentes:  66%|██████▌   | 66/100 [00:19<00:09,  3.59it/s]

🌐 GET frentes/55575
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  67%|██████▋   | 67/100 [00:19<00:09,  3.56it/s]

🌐 GET frentes/55589
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  68%|██████▊   | 68/100 [00:19<00:08,  3.57it/s]

🌐 GET frentes/55588
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  69%|██████▉   | 69/100 [00:19<00:08,  3.68it/s]

🌐 GET frentes/55573
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  70%|███████   | 70/100 [00:20<00:08,  3.45it/s]

🌐 GET frentes/55581
⏱ Tempo: 0.33s | 📦 Registros: 1

Extração detalhamento frentes:  71%|███████   | 71/100 [00:20<00:08,  3.52it/s]

🌐 GET frentes/55584
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  72%|███████▏  | 72/100 [00:20<00:07,  3.62it/s]

🌐 GET frentes/55576
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  73%|███████▎  | 73/100 [00:21<00:08,  3.07it/s]

🌐 GET frentes/55583
⏱ Tempo: 0.43s | 📦 Registros: 1

Extração detalhamento frentes:  74%|███████▍  | 74/100 [00:21<00:08,  3.19it/s]

🌐 GET frentes/55586
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  75%|███████▌  | 75/100 [00:21<00:07,  3.34it/s]

🌐 GET frentes/55580
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento frentes:  76%|███████▌  | 76/100 [00:23<00:14,  1.68it/s]

🌐 GET frentes/54537
⏱ Tempo: 1.28s | 📦 Registros: 1

Extração detalhamento frentes:  77%|███████▋  | 77/100 [00:23<00:11,  1.93it/s]

🌐 GET frentes/54566
⏱ Tempo: 0.33s | 📦 Registros: 1

Extração detalhamento frentes:  78%|███████▊  | 78/100 [00:23<00:09,  2.25it/s]

🌐 GET frentes/54558
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  79%|███████▉  | 79/100 [00:24<00:08,  2.47it/s]

🌐 GET frentes/54560
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:  80%|████████  | 80/100 [00:24<00:07,  2.51it/s]

🌐 GET frentes/54559
⏱ Tempo: 0.37s | 📦 Registros: 1

Extração detalhamento frentes:  81%|████████  | 81/100 [00:24<00:06,  2.85it/s]

🌐 GET frentes/55571
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes:  82%|████████▏ | 82/100 [00:24<00:05,  3.02it/s]

🌐 GET frentes/55572
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  83%|████████▎ | 83/100 [00:25<00:05,  3.19it/s]

🌐 GET frentes/55566
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  84%|████████▍ | 84/100 [00:25<00:04,  3.27it/s]

🌐 GET frentes/54557
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento frentes:  85%|████████▌ | 85/100 [00:28<00:17,  1.17s/it]

🌐 GET frentes/55567
⏱ Tempo: 3.19s | 📦 Registros: 1

Extração detalhamento frentes:  86%|████████▌ | 86/100 [00:28<00:12,  1.11it/s]

🌐 GET frentes/55568
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  87%|████████▋ | 87/100 [00:29<00:09,  1.35it/s]

🌐 GET frentes/55569
⏱ Tempo: 0.35s | 📦 Registros: 1

Extração detalhamento frentes:  88%|████████▊ | 88/100 [00:29<00:07,  1.65it/s]

🌐 GET frentes/54565
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento frentes:  89%|████████▉ | 89/100 [00:29<00:05,  1.84it/s]

🌐 GET frentes/54563
⏱ Tempo: 0.39s | 📦 Registros: 1

Extração detalhamento frentes:  90%|█████████ | 90/100 [00:30<00:04,  2.20it/s]

🌐 GET frentes/54564
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento frentes:  91%|█████████ | 91/100 [00:30<00:03,  2.38it/s]

🌐 GET frentes/54507
⏱ Tempo: 0.33s | 📦 Registros: 1

Extração detalhamento frentes:  92%|█████████▏| 92/100 [00:31<00:04,  2.00it/s]

🌐 GET frentes/55570
⏱ Tempo: 0.69s | 📦 Registros: 1

Extração detalhamento frentes:  93%|█████████▎| 93/100 [00:31<00:03,  2.24it/s]

🌐 GET frentes/54562
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento frentes:  94%|█████████▍| 94/100 [00:31<00:02,  2.58it/s]

🌐 GET frentes/54545
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento frentes:  95%|█████████▌| 95/100 [00:32<00:01,  2.78it/s]

🌐 GET frentes/54553
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento frentes:  96%|█████████▌| 96/100 [00:32<00:01,  2.91it/s]

🌐 GET frentes/54550
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:  97%|█████████▋| 97/100 [00:32<00:00,  3.02it/s]

🌐 GET frentes/54555
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento frentes:  98%|█████████▊| 98/100 [00:33<00:00,  3.18it/s]

🌐 GET frentes/54548
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento frentes:  99%|█████████▉| 99/100 [00:33<00:00,  3.41it/s]

🌐 GET frentes/54552
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento frentes: 100%|██████████| 100/100 [00:33<00:00,  2.98it/s]

🌐 GET frentes/54554
⏱ Tempo: 0.27s | 📦 Registros: 1

In [49]:
loader.save_bronze(
    df=df_frentesDetalhamento,
    dataset='frentes_detalhamento'
)

💾 Salvo em: data/bronze/frentes_detalhamento/frentes_detalhamento.parquet

In [51]:
ids_votacoes = df_proposicoesVotacoes['id']

df_votacoesDetalhamento = extractor.extract_by_ids(
    ids=ids_votacoes,
    endpoint_template='votacoes/{id}',
    desc= 'Extração detalhamento votações'
)

Extração detalhamento votações:   0%|          | 1/271 [00:00<01:15,  3.57it/s]

🌐 GET votacoes/369205-154
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:   1%|          | 2/271 [00:00<01:10,  3.79it/s]

🌐 GET votacoes/369205-151
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:   1%|          | 3/271 [00:00<01:14,  3.61it/s]

🌐 GET votacoes/369205-129
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento votações:   1%|▏         | 4/271 [00:01<01:08,  3.92it/s]

🌐 GET votacoes/369205-128
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:   2%|▏         | 5/271 [00:01<01:07,  3.97it/s]

🌐 GET votacoes/369205-127
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:   2%|▏         | 6/271 [00:01<01:04,  4.14it/s]

🌐 GET votacoes/369205-126
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:   3%|▎         | 7/271 [00:01<01:05,  4.02it/s]

🌐 GET votacoes/369205-71
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:   3%|▎         | 8/271 [00:02<01:04,  4.07it/s]

🌐 GET votacoes/369205-38
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:   3%|▎         | 9/271 [00:02<01:01,  4.28it/s]

🌐 GET votacoes/618609-107
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:   4%|▎         | 10/271 [00:02<00:59,  4.42it/s]

🌐 GET votacoes/618609-80
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:   4%|▍         | 11/271 [00:02<00:57,  4.49it/s]

🌐 GET votacoes/618609-65
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:   4%|▍         | 12/271 [00:02<00:57,  4.52it/s]

🌐 GET votacoes/618609-40
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:   5%|▍         | 13/271 [00:03<00:57,  4.52it/s]

🌐 GET votacoes/1197773-157
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:   5%|▌         | 14/271 [00:03<00:57,  4.45it/s]

🌐 GET votacoes/1197773-156
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:   6%|▌         | 15/271 [00:03<00:58,  4.41it/s]

🌐 GET votacoes/1197773-154
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:   6%|▌         | 16/271 [00:03<00:57,  4.41it/s]

🌐 GET votacoes/1197773-150
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:   7%|▋         | 18/271 [00:04<00:57,  4.42it/s]

🌐 GET votacoes/1197773-140
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET votacoes/1197773-104
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:   7%|▋         | 19/271 [00:04<00:55,  4.53it/s]

🌐 GET votacoes/1197773-99
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:   7%|▋         | 20/271 [00:04<00:56,  4.46it/s]

🌐 GET votacoes/1197773-95
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:   8%|▊         | 21/271 [00:04<00:55,  4.49it/s]

🌐 GET votacoes/1197773-90
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:   8%|▊         | 22/271 [00:05<00:54,  4.57it/s]

🌐 GET votacoes/1197773-87
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:   8%|▊         | 23/271 [00:05<00:59,  4.18it/s]

🌐 GET votacoes/1197773-81
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento votações:   9%|▉         | 24/271 [00:05<00:58,  4.24it/s]

🌐 GET votacoes/1197773-76
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:   9%|▉         | 25/271 [00:05<00:55,  4.41it/s]

🌐 GET votacoes/2375501-8
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  10%|▉         | 27/271 [00:06<00:57,  4.28it/s]

🌐 GET votacoes/1198010-165
⏱ Tempo: 0.30s | 📦 Registros: 1
🌐 GET votacoes/1198010-163
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  10%|█         | 28/271 [00:06<00:57,  4.23it/s]

🌐 GET votacoes/1198010-154
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  11%|█         | 29/271 [00:06<00:55,  4.36it/s]

🌐 GET votacoes/1198010-144
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  11%|█         | 30/271 [00:07<00:56,  4.30it/s]

🌐 GET votacoes/1198010-140
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  12%|█▏        | 32/271 [00:07<00:53,  4.44it/s]

🌐 GET votacoes/1198010-130
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET votacoes/1198010-117
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  13%|█▎        | 34/271 [00:07<00:51,  4.64it/s]

🌐 GET votacoes/1198010-99
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/1198010-76
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  13%|█▎        | 35/271 [00:08<00:49,  4.73it/s]

🌐 GET votacoes/1198010-61
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET votacoes/1198010-49
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  14%|█▎        | 37/271 [00:08<00:48,  4.79it/s]

🌐 GET votacoes/1198010-33
⏱ Tempo: 0.19s | 📦 Registros: 1
🌐 GET votacoes/2074843-165
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  15%|█▍        | 40/271 [00:09<00:45,  5.07it/s]

🌐 GET votacoes/2074843-163
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET votacoes/2074843-113
⏱ Tempo: 0.17s | 📦 Registros: 1

Extração detalhamento votações:  15%|█▌        | 41/271 [00:09<00:46,  4.95it/s]

🌐 GET votacoes/2074843-110
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  15%|█▌        | 42/271 [00:09<00:47,  4.86it/s]

🌐 GET votacoes/2074843-97
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  16%|█▌        | 43/271 [00:09<00:47,  4.75it/s]

🌐 GET votacoes/2379387-8
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  16%|█▌        | 44/271 [00:09<00:49,  4.61it/s]

🌐 GET votacoes/2074843-85
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  17%|█▋        | 46/271 [00:10<00:49,  4.58it/s]

🌐 GET votacoes/2115253-183
⏱ Tempo: 0.26s | 📦 Registros: 1
🌐 GET votacoes/2115253-179
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  17%|█▋        | 47/271 [00:10<00:49,  4.55it/s]

🌐 GET votacoes/2115253-175
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  18%|█▊        | 48/271 [00:10<00:52,  4.27it/s]

🌐 GET votacoes/2115253-172
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  18%|█▊        | 49/271 [00:11<00:51,  4.29it/s]

🌐 GET votacoes/2115253-167
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  18%|█▊        | 50/271 [00:11<00:50,  4.38it/s]

🌐 GET votacoes/2115253-156
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  19%|█▉        | 51/271 [00:11<00:49,  4.48it/s]

🌐 GET votacoes/2115253-123
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET votacoes/2115253-121
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  20%|█▉        | 53/271 [00:12<00:48,  4.53it/s]

🌐 GET votacoes/2115253-118
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  20%|█▉        | 54/271 [00:12<00:47,  4.56it/s]

🌐 GET votacoes/2115253-116
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  20%|██        | 55/271 [00:12<00:47,  4.58it/s]

🌐 GET votacoes/2115253-111
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  21%|██        | 57/271 [00:12<00:48,  4.46it/s]

🌐 GET votacoes/2115253-104
⏱ Tempo: 0.28s | 📦 Registros: 1
🌐 GET votacoes/2115253-93
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  21%|██▏       | 58/271 [00:13<00:49,  4.29it/s]

🌐 GET votacoes/2359287-7
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  22%|██▏       | 59/271 [00:13<00:48,  4.38it/s]

🌐 GET votacoes/2115253-86
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  22%|██▏       | 60/271 [00:13<00:50,  4.21it/s]

🌐 GET votacoes/2115253-67
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  23%|██▎       | 61/271 [00:13<00:49,  4.26it/s]

🌐 GET votacoes/2115253-32
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  23%|██▎       | 62/271 [00:14<00:48,  4.28it/s]

🌐 GET votacoes/2345493-64
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  23%|██▎       | 63/271 [00:14<00:48,  4.28it/s]

🌐 GET votacoes/2345493-62
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  24%|██▎       | 64/271 [00:14<00:51,  4.03it/s]

🌐 GET votacoes/2345493-52
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento votações:  24%|██▍       | 65/271 [00:14<00:50,  4.10it/s]

🌐 GET votacoes/2345493-50
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  24%|██▍       | 66/271 [00:15<00:51,  3.99it/s]

🌐 GET votacoes/2345493-47
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  25%|██▍       | 67/271 [00:15<00:49,  4.09it/s]

🌐 GET votacoes/2345493-44
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  25%|██▌       | 68/271 [00:15<00:49,  4.07it/s]

🌐 GET votacoes/2345493-41
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  25%|██▌       | 69/271 [00:15<00:51,  3.93it/s]

🌐 GET votacoes/2345493-39
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  26%|██▌       | 70/271 [00:16<00:50,  3.99it/s]

🌐 GET votacoes/2345493-38
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  26%|██▌       | 71/271 [00:16<00:50,  3.98it/s]

🌐 GET votacoes/2345493-35
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  27%|██▋       | 72/271 [00:16<00:49,  4.04it/s]

🌐 GET votacoes/2345493-31
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  27%|██▋       | 73/271 [00:16<00:49,  4.04it/s]

🌐 GET votacoes/2345493-9
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  27%|██▋       | 74/271 [00:18<01:52,  1.75it/s]

🌐 GET votacoes/2353475-2
⏱ Tempo: 1.32s | 📦 Registros: 1

Extração detalhamento votações:  28%|██▊       | 75/271 [00:18<01:31,  2.15it/s]

🌐 GET votacoes/2345498-69
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET votacoes/2345498-54
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  28%|██▊       | 77/271 [00:18<01:03,  3.07it/s]

🌐 GET votacoes/2345498-38
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  29%|██▉       | 78/271 [00:19<00:56,  3.39it/s]

🌐 GET votacoes/2345501-28
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET votacoes/2345501-26
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  30%|██▉       | 80/271 [00:19<00:47,  4.00it/s]

🌐 GET votacoes/2345501-25
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  30%|██▉       | 81/271 [00:19<00:46,  4.06it/s]

🌐 GET votacoes/2345501-18
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  30%|███       | 82/271 [00:19<00:45,  4.12it/s]

🌐 GET votacoes/2345501-17
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/2345502-6
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  31%|███       | 84/271 [00:20<00:44,  4.24it/s]

🌐 GET votacoes/253500-398
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  31%|███▏      | 85/271 [00:20<00:45,  4.06it/s]

🌐 GET votacoes/253500-396
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  32%|███▏      | 86/271 [00:20<00:45,  4.10it/s]

🌐 GET votacoes/253500-384
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  32%|███▏      | 87/271 [00:21<00:45,  4.06it/s]

🌐 GET votacoes/253500-383
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  32%|███▏      | 88/271 [00:21<00:45,  4.05it/s]

🌐 GET votacoes/253500-382
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  33%|███▎      | 89/271 [00:21<00:44,  4.11it/s]

🌐 GET votacoes/253500-381
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  33%|███▎      | 90/271 [00:21<00:45,  3.94it/s]

🌐 GET votacoes/253500-380
⏱ Tempo: 0.27s | 📦 Registros: 1
🌐 GET votacoes/2451405-8
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  34%|███▍      | 92/271 [00:23<01:26,  2.07it/s]

🌐 GET votacoes/253500-356
⏱ Tempo: 1.05s | 📦 Registros: 1

Extração detalhamento votações:  34%|███▍      | 93/271 [00:23<01:17,  2.30it/s]

🌐 GET votacoes/253500-339
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento votações:  35%|███▍      | 94/271 [00:23<01:07,  2.64it/s]

🌐 GET votacoes/2079335-2
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  35%|███▌      | 95/271 [00:23<00:58,  3.00it/s]

🌐 GET votacoes/2079333-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  35%|███▌      | 96/271 [00:24<00:53,  3.27it/s]

🌐 GET votacoes/2079331-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  36%|███▌      | 97/271 [00:24<00:57,  3.05it/s]

🌐 GET votacoes/253500-331
⏱ Tempo: 0.37s | 📦 Registros: 1

Extração detalhamento votações:  36%|███▌      | 98/271 [00:24<01:02,  2.76it/s]

🌐 GET votacoes/253500-330
⏱ Tempo: 0.44s | 📦 Registros: 1

Extração detalhamento votações:  37%|███▋      | 99/271 [00:25<00:59,  2.91it/s]

🌐 GET votacoes/253500-329
⏱ Tempo: 0.30s | 📦 Registros: 1
🌐 GET votacoes/559154-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  37%|███▋      | 101/271 [00:25<00:47,  3.55it/s]

🌐 GET votacoes/559153-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  38%|███▊      | 102/271 [00:25<00:45,  3.75it/s]

🌐 GET votacoes/559152-2
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/559151-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  38%|███▊      | 104/271 [00:26<00:40,  4.10it/s]

🌐 GET votacoes/559150-2
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET votacoes/559149-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  39%|███▉      | 106/271 [00:26<00:36,  4.51it/s]

🌐 GET votacoes/559148-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  40%|███▉      | 108/271 [00:27<00:34,  4.71it/s]

🌐 GET votacoes/559147-2
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET votacoes/557268-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  41%|████      | 110/271 [00:27<00:33,  4.74it/s]

🌐 GET votacoes/556546-2
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/553525-2
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  41%|████      | 111/271 [00:27<00:33,  4.77it/s]

🌐 GET votacoes/553479-2
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET votacoes/553467-2
⏱ Tempo: 3.13s | 📦 Registros: 1

Extração detalhamento votações:  42%|████▏     | 113/271 [00:31<02:09,  1.22it/s]

🌐 GET votacoes/553466-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  42%|████▏     | 114/271 [00:31<01:41,  1.54it/s]

🌐 GET votacoes/553465-2
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/553464-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  43%|████▎     | 117/271 [00:32<00:55,  2.78it/s]

🌐 GET votacoes/553461-2
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/553423-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  44%|████▎     | 118/271 [00:32<00:47,  3.23it/s]

🌐 GET votacoes/553422-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  44%|████▍     | 119/271 [00:32<00:43,  3.52it/s]

🌐 GET votacoes/553421-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  44%|████▍     | 120/271 [00:32<00:40,  3.75it/s]

🌐 GET votacoes/553420-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  45%|████▍     | 121/271 [00:32<00:37,  3.99it/s]

🌐 GET votacoes/553384-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  45%|████▌     | 122/271 [00:33<00:35,  4.15it/s]

🌐 GET votacoes/553357-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  45%|████▌     | 123/271 [00:33<00:34,  4.31it/s]

🌐 GET votacoes/553289-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  46%|████▌     | 124/271 [00:33<00:34,  4.28it/s]

🌐 GET votacoes/553288-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  46%|████▌     | 125/271 [00:33<00:33,  4.30it/s]

🌐 GET votacoes/553287-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  46%|████▋     | 126/271 [00:34<00:33,  4.31it/s]

🌐 GET votacoes/553286-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  47%|████▋     | 127/271 [00:34<00:32,  4.45it/s]

🌐 GET votacoes/553272-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  47%|████▋     | 128/271 [00:34<00:33,  4.31it/s]

🌐 GET votacoes/553269-2
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  48%|████▊     | 129/271 [00:34<00:35,  4.04it/s]

🌐 GET votacoes/553266-2
⏱ Tempo: 0.28s | 📦 Registros: 1

Extração detalhamento votações:  48%|████▊     | 130/271 [00:35<00:34,  4.08it/s]

🌐 GET votacoes/553262-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  48%|████▊     | 131/271 [00:35<00:34,  4.10it/s]

🌐 GET votacoes/553261-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  49%|████▊     | 132/271 [00:35<00:32,  4.24it/s]

🌐 GET votacoes/553260-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  49%|████▉     | 133/271 [00:35<00:36,  3.82it/s]

🌐 GET votacoes/553259-2
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento votações:  49%|████▉     | 134/271 [00:36<00:34,  3.98it/s]

🌐 GET votacoes/553258-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  50%|████▉     | 135/271 [00:36<00:33,  4.11it/s]

🌐 GET votacoes/553257-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  50%|█████     | 136/271 [00:36<00:32,  4.14it/s]

🌐 GET votacoes/553256-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  51%|█████     | 137/271 [00:36<00:32,  4.19it/s]

🌐 GET votacoes/553255-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  51%|█████     | 138/271 [00:37<00:33,  3.99it/s]

🌐 GET votacoes/553253-2
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  51%|█████▏    | 139/271 [00:37<00:33,  3.98it/s]

🌐 GET votacoes/553251-2
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  52%|█████▏    | 140/271 [00:37<00:31,  4.13it/s]

🌐 GET votacoes/553250-2
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET votacoes/553248-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  52%|█████▏    | 142/271 [00:37<00:30,  4.18it/s]

🌐 GET votacoes/553246-2
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET votacoes/553245-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  53%|█████▎    | 144/271 [00:38<00:29,  4.30it/s]

🌐 GET votacoes/553244-2
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  54%|█████▎    | 145/271 [00:38<00:28,  4.38it/s]

🌐 GET votacoes/553243-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  54%|█████▍    | 146/271 [00:38<00:29,  4.25it/s]

🌐 GET votacoes/553242-2
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  54%|█████▍    | 147/271 [00:39<00:28,  4.30it/s]

🌐 GET votacoes/553241-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  55%|█████▍    | 148/271 [00:39<00:29,  4.18it/s]

🌐 GET votacoes/253500-223
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  55%|█████▌    | 150/271 [00:39<00:26,  4.52it/s]

🌐 GET votacoes/472189-3
⏱ Tempo: 0.22s | 📦 Registros: 1
🌐 GET votacoes/472187-3
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  56%|█████▌    | 151/271 [00:39<00:25,  4.67it/s]

🌐 GET votacoes/471727-4
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  56%|█████▌    | 152/271 [00:40<00:26,  4.46it/s]

🌐 GET votacoes/253500-142
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  56%|█████▋    | 153/271 [00:40<00:27,  4.37it/s]

🌐 GET votacoes/253500-141
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  57%|█████▋    | 154/271 [00:40<00:26,  4.41it/s]

🌐 GET votacoes/253500-140
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  57%|█████▋    | 155/271 [00:41<00:31,  3.66it/s]

🌐 GET votacoes/467027-2
⏱ Tempo: 0.37s | 📦 Registros: 1

Extração detalhamento votações:  58%|█████▊    | 156/271 [00:41<00:29,  3.89it/s]

🌐 GET votacoes/467025-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  58%|█████▊    | 157/271 [00:41<00:28,  3.97it/s]

🌐 GET votacoes/467023-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  58%|█████▊    | 158/271 [00:41<00:28,  3.97it/s]

🌐 GET votacoes/467022-2
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  59%|█████▊    | 159/271 [00:41<00:27,  4.06it/s]

🌐 GET votacoes/467020-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  59%|█████▉    | 160/271 [00:42<00:26,  4.23it/s]

🌐 GET votacoes/466193-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  60%|█████▉    | 162/271 [00:42<00:23,  4.61it/s]

🌐 GET votacoes/462366-2
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET votacoes/462253-2
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  60%|██████    | 163/271 [00:42<00:23,  4.69it/s]

🌐 GET votacoes/461790-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  61%|██████    | 164/271 [00:43<00:23,  4.57it/s]

🌐 GET votacoes/461789-2
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  61%|██████    | 165/271 [00:43<00:23,  4.60it/s]

🌐 GET votacoes/461475-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  62%|██████▏   | 167/271 [00:43<00:21,  4.74it/s]

🌐 GET votacoes/461465-2
⏱ Tempo: 0.21s | 📦 Registros: 1
🌐 GET votacoes/461402-2
⏱ Tempo: 0.18s | 📦 Registros: 1

Extração detalhamento votações:  62%|██████▏   | 168/271 [00:43<00:21,  4.80it/s]

🌐 GET votacoes/461373-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  62%|██████▏   | 169/271 [00:44<00:21,  4.77it/s]

🌐 GET votacoes/461366-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  63%|██████▎   | 170/271 [00:44<00:21,  4.70it/s]

🌐 GET votacoes/461356-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  63%|██████▎   | 171/271 [00:44<00:21,  4.64it/s]

🌐 GET votacoes/461261-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  63%|██████▎   | 172/271 [00:44<00:21,  4.59it/s]

🌐 GET votacoes/461220-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  64%|██████▍   | 173/271 [00:44<00:21,  4.57it/s]

🌐 GET votacoes/461218-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  64%|██████▍   | 174/271 [00:45<00:22,  4.33it/s]

🌐 GET votacoes/461217-2
⏱ Tempo: 0.25s | 📦 Registros: 1
🌐 GET votacoes/461215-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  65%|██████▍   | 176/271 [00:45<00:21,  4.33it/s]

🌐 GET votacoes/461214-2
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/460925-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  66%|██████▌   | 178/271 [00:46<00:21,  4.32it/s]

🌐 GET votacoes/460923-2
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  66%|██████▌   | 179/271 [00:47<00:48,  1.91it/s]

🌐 GET votacoes/460922-2
⏱ Tempo: 1.20s | 📦 Registros: 1

Extração detalhamento votações:  66%|██████▋   | 180/271 [00:47<00:39,  2.28it/s]

🌐 GET votacoes/459944-2
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  67%|██████▋   | 181/271 [00:47<00:34,  2.60it/s]

🌐 GET votacoes/459943-2
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  67%|██████▋   | 182/271 [00:48<00:29,  2.97it/s]

🌐 GET votacoes/459942-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  68%|██████▊   | 183/271 [00:48<00:26,  3.29it/s]

🌐 GET votacoes/459941-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  68%|██████▊   | 184/271 [00:48<00:23,  3.64it/s]

🌐 GET votacoes/459940-2
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  68%|██████▊   | 185/271 [00:48<00:23,  3.66it/s]

🌐 GET votacoes/253500-62
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  69%|██████▊   | 186/271 [00:48<00:21,  3.90it/s]

🌐 GET votacoes/267849-2
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  69%|██████▉   | 187/271 [00:49<00:23,  3.65it/s]

🌐 GET votacoes/510035-126
⏱ Tempo: 0.31s | 📦 Registros: 1

Extração detalhamento votações:  69%|██████▉   | 188/271 [00:49<00:22,  3.77it/s]

🌐 GET votacoes/510035-116
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  70%|██████▉   | 189/271 [00:49<00:20,  3.92it/s]

🌐 GET votacoes/510035-92
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  70%|███████   | 190/271 [00:50<00:20,  3.97it/s]

🌐 GET votacoes/510035-77
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  70%|███████   | 191/271 [00:50<00:19,  4.00it/s]

🌐 GET votacoes/510035-61
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  71%|███████   | 192/271 [00:50<00:19,  3.98it/s]

🌐 GET votacoes/510035-46
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  71%|███████   | 193/271 [00:50<00:19,  4.08it/s]

🌐 GET votacoes/1548579-198
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  72%|███████▏  | 194/271 [00:51<00:19,  4.00it/s]

🌐 GET votacoes/1548579-196
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  72%|███████▏  | 195/271 [00:51<00:18,  4.09it/s]

🌐 GET votacoes/1548579-194
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  72%|███████▏  | 196/271 [00:51<00:18,  3.97it/s]

🌐 GET votacoes/1548579-186
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  73%|███████▎  | 197/271 [00:51<00:18,  4.06it/s]

🌐 GET votacoes/1548579-170
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  73%|███████▎  | 198/271 [00:51<00:17,  4.12it/s]

🌐 GET votacoes/1548579-169
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  73%|███████▎  | 199/271 [00:52<00:17,  4.19it/s]

🌐 GET votacoes/1548579-168
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  74%|███████▍  | 200/271 [00:52<00:17,  4.03it/s]

🌐 GET votacoes/1548579-167
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  74%|███████▍  | 201/271 [00:52<00:16,  4.19it/s]

🌐 GET votacoes/1548579-166
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  75%|███████▍  | 202/271 [00:52<00:16,  4.23it/s]

🌐 GET votacoes/1548579-165
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  75%|███████▍  | 203/271 [00:53<00:15,  4.31it/s]

🌐 GET votacoes/1548579-164
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  75%|███████▌  | 204/271 [00:53<00:15,  4.29it/s]

🌐 GET votacoes/1548579-163
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  76%|███████▌  | 205/271 [00:53<00:15,  4.17it/s]

🌐 GET votacoes/1548579-162
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  76%|███████▌  | 206/271 [00:53<00:17,  3.79it/s]

🌐 GET votacoes/1548579-161
⏱ Tempo: 0.32s | 📦 Registros: 1

Extração detalhamento votações:  76%|███████▋  | 207/271 [00:54<00:16,  3.94it/s]

🌐 GET votacoes/1548579-160
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  77%|███████▋  | 208/271 [00:54<00:16,  3.86it/s]

🌐 GET votacoes/1548579-159
⏱ Tempo: 0.26s | 📦 Registros: 1

Extração detalhamento votações:  77%|███████▋  | 209/271 [00:54<00:15,  3.91it/s]

🌐 GET votacoes/1548579-146
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  77%|███████▋  | 210/271 [00:54<00:15,  4.01it/s]

🌐 GET votacoes/1548579-144
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  78%|███████▊  | 211/271 [00:55<00:15,  3.79it/s]

🌐 GET votacoes/1548579-126
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento votações:  78%|███████▊  | 212/271 [00:55<00:17,  3.46it/s]

🌐 GET votacoes/1548579-122
⏱ Tempo: 0.34s | 📦 Registros: 1

Extração detalhamento votações:  79%|███████▊  | 213/271 [00:55<00:15,  3.66it/s]

🌐 GET votacoes/1548579-114
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  79%|███████▉  | 214/271 [00:56<00:15,  3.70it/s]

🌐 GET votacoes/1548579-109
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  79%|███████▉  | 215/271 [00:56<00:14,  3.89it/s]

🌐 GET votacoes/1548579-101
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  80%|███████▉  | 216/271 [00:56<00:14,  3.79it/s]

🌐 GET votacoes/1548579-100
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  80%|████████  | 217/271 [00:56<00:14,  3.85it/s]

🌐 GET votacoes/1548579-99
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  80%|████████  | 218/271 [00:57<00:13,  3.94it/s]

🌐 GET votacoes/1548579-98
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  81%|████████  | 219/271 [00:57<00:12,  4.04it/s]

🌐 GET votacoes/1548579-97
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  81%|████████  | 220/271 [00:57<00:12,  4.03it/s]

🌐 GET votacoes/1548579-96
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  82%|████████▏ | 221/271 [00:57<00:13,  3.73it/s]

🌐 GET votacoes/1548579-95
⏱ Tempo: 0.30s | 📦 Registros: 1

Extração detalhamento votações:  82%|████████▏ | 222/271 [00:58<00:12,  3.95it/s]

🌐 GET votacoes/1548579-94
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  82%|████████▏ | 223/271 [00:58<00:12,  3.90it/s]

🌐 GET votacoes/1548579-93
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  83%|████████▎ | 224/271 [00:58<00:12,  3.87it/s]

🌐 GET votacoes/1548579-92
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  83%|████████▎ | 225/271 [00:58<00:11,  3.92it/s]

🌐 GET votacoes/1548579-91
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  83%|████████▎ | 226/271 [00:59<00:11,  3.92it/s]

🌐 GET votacoes/1548579-90
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  84%|████████▍ | 227/271 [00:59<00:10,  4.04it/s]

🌐 GET votacoes/1548579-89
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  84%|████████▍ | 228/271 [00:59<00:10,  4.10it/s]

🌐 GET votacoes/1548579-88
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  85%|████████▍ | 229/271 [00:59<00:10,  4.14it/s]

🌐 GET votacoes/1548579-87
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  85%|████████▍ | 230/271 [01:00<00:09,  4.26it/s]

🌐 GET votacoes/1548579-86
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  85%|████████▌ | 231/271 [01:00<00:09,  4.28it/s]

🌐 GET votacoes/1548579-85
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  86%|████████▌ | 232/271 [01:00<00:09,  4.21it/s]

🌐 GET votacoes/1548579-84
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  86%|████████▌ | 233/271 [01:00<00:09,  4.18it/s]

🌐 GET votacoes/2092056-118
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  86%|████████▋ | 234/271 [01:01<00:08,  4.21it/s]

🌐 GET votacoes/2092056-99
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  87%|████████▋ | 235/271 [01:01<00:09,  3.88it/s]

🌐 GET votacoes/2092056-98
⏱ Tempo: 0.29s | 📦 Registros: 1
🌐 GET votacoes/2092056-86
⏱ Tempo: 0.19s | 📦 Registros: 1

Extração detalhamento votações:  87%|████████▋ | 237/271 [01:01<00:08,  4.13it/s]

🌐 GET votacoes/2092056-83
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  88%|████████▊ | 238/271 [01:02<00:08,  3.96it/s]

🌐 GET votacoes/2092056-68
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  88%|████████▊ | 239/271 [01:02<00:07,  4.12it/s]

🌐 GET votacoes/2092056-67
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  89%|████████▊ | 240/271 [01:02<00:07,  4.27it/s]

🌐 GET votacoes/2416804-56
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  89%|████████▉ | 241/271 [01:02<00:06,  4.31it/s]

🌐 GET votacoes/2416804-54
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  89%|████████▉ | 242/271 [01:02<00:06,  4.29it/s]

🌐 GET votacoes/2416804-51
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  90%|████████▉ | 243/271 [01:06<00:31,  1.12s/it]

🌐 GET votacoes/2416804-48
⏱ Tempo: 3.16s | 📦 Registros: 1

Extração detalhamento votações:  90%|█████████ | 244/271 [01:06<00:23,  1.15it/s]

🌐 GET votacoes/2416804-43
⏱ Tempo: 0.29s | 📦 Registros: 1

Extração detalhamento votações:  90%|█████████ | 245/271 [01:06<00:17,  1.46it/s]

🌐 GET votacoes/2416804-31
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  91%|█████████ | 246/271 [01:06<00:13,  1.83it/s]

🌐 GET votacoes/2416826-60
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  91%|█████████ | 247/271 [01:07<00:10,  2.22it/s]

🌐 GET votacoes/2416826-59
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  92%|█████████▏| 248/271 [01:07<00:08,  2.62it/s]

🌐 GET votacoes/2416826-52
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  92%|█████████▏| 249/271 [01:07<00:07,  2.93it/s]

🌐 GET votacoes/2416826-49
⏱ Tempo: 0.24s | 📦 Registros: 1
🌐 GET votacoes/2481874-37
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  93%|█████████▎| 251/271 [01:08<00:05,  3.37it/s]

🌐 GET votacoes/2481874-35
⏱ Tempo: 0.27s | 📦 Registros: 1

Extração detalhamento votações:  93%|█████████▎| 252/271 [01:08<00:05,  3.66it/s]

🌐 GET votacoes/2481874-29
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  93%|█████████▎| 253/271 [01:08<00:04,  3.96it/s]

🌐 GET votacoes/2481874-16
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  94%|█████████▎| 254/271 [01:08<00:04,  4.10it/s]

🌐 GET votacoes/2481874-15
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  94%|█████████▍| 255/271 [01:08<00:03,  4.01it/s]

🌐 GET votacoes/2481874-14
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  94%|█████████▍| 256/271 [01:09<00:03,  4.12it/s]

🌐 GET votacoes/2481874-13
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  95%|█████████▍| 257/271 [01:09<00:03,  4.14it/s]

🌐 GET votacoes/2494647-7
⏱ Tempo: 0.23s | 📦 Registros: 1
🌐 GET votacoes/2481875-40
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  96%|█████████▌| 259/271 [01:10<00:03,  3.56it/s]

🌐 GET votacoes/2481875-38
⏱ Tempo: 0.36s | 📦 Registros: 1

Extração detalhamento votações:  96%|█████████▌| 260/271 [01:10<00:02,  3.71it/s]

🌐 GET votacoes/2481875-32
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  96%|█████████▋| 261/271 [01:10<00:02,  3.89it/s]

🌐 GET votacoes/2481875-17
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  97%|█████████▋| 262/271 [01:10<00:02,  4.04it/s]

🌐 GET votacoes/2481875-16
⏱ Tempo: 0.21s | 📦 Registros: 1

Extração detalhamento votações:  97%|█████████▋| 263/271 [01:11<00:01,  4.02it/s]

🌐 GET votacoes/2481875-15
⏱ Tempo: 0.24s | 📦 Registros: 1

Extração detalhamento votações:  97%|█████████▋| 264/271 [01:11<00:01,  4.07it/s]

🌐 GET votacoes/2481875-14
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  98%|█████████▊| 265/271 [01:11<00:01,  4.23it/s]

🌐 GET votacoes/2494658-8
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações:  98%|█████████▊| 266/271 [01:11<00:01,  4.26it/s]

🌐 GET votacoes/2481876-24
⏱ Tempo: 0.22s | 📦 Registros: 1

Extração detalhamento votações:  99%|█████████▊| 267/271 [01:11<00:00,  4.19it/s]

🌐 GET votacoes/2481882-23
⏱ Tempo: 0.23s | 📦 Registros: 1

Extração detalhamento votações:  99%|█████████▉| 268/271 [01:12<00:00,  4.08it/s]

🌐 GET votacoes/2481884-23
⏱ Tempo: 0.25s | 📦 Registros: 1

Extração detalhamento votações:  99%|█████████▉| 269/271 [01:12<00:00,  4.25it/s]

🌐 GET votacoes/2481886-23
⏱ Tempo: 0.20s | 📦 Registros: 1
🌐 GET votacoes/2481888-23
⏱ Tempo: 0.20s | 📦 Registros: 1

Extração detalhamento votações: 100%|██████████| 271/271 [01:12<00:00,  3.72it/s]

🌐 GET votacoes/2481890-23
⏱ Tempo: 0.27s | 📦 Registros: 1

In [52]:
loader.save_bronze(
    df= df_votacoesDetalhamento,
    dataset='votacoes_detalhamento'
)

💾 Salvo em: data/bronze/votacoes_detalhamento/votacoes_detalhamento.parquet

In [54]:
df_votacoesOrientacoes = extractor.extract_by_ids(
    ids=ids_votacoes,
    endpoint_template='votacoes/{id}/orientacoes'
)

Extract by ID:   0%|          | 1/271 [00:00<03:57,  1.14it/s]

🌐 GET votacoes/369205-154/orientacoes
⏱ Tempo: 0.88s | 📦 Registros: 0

Extract by ID:   1%|          | 2/271 [00:01<02:39,  1.69it/s]

🌐 GET votacoes/369205-151/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:   1%|          | 3/271 [00:01<02:14,  1.99it/s]

🌐 GET votacoes/369205-129/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:   1%|▏         | 4/271 [00:02<02:01,  2.20it/s]

🌐 GET votacoes/369205-128/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:   2%|▏         | 5/271 [00:02<02:22,  1.87it/s]

🌐 GET votacoes/369205-127/orientacoes
⏱ Tempo: 0.67s | 📦 Registros: 0

Extract by ID:   2%|▏         | 6/271 [00:06<06:29,  1.47s/it]

🌐 GET votacoes/369205-126/orientacoes
⏱ Tempo: 3.27s | 📦 Registros: 0

Extract by ID:   3%|▎         | 7/271 [00:06<05:26,  1.23s/it]

🌐 GET votacoes/369205-71/orientacoes
⏱ Tempo: 0.75s | 📦 Registros: 0

Extract by ID:   3%|▎         | 8/271 [00:07<04:19,  1.01it/s]

🌐 GET votacoes/369205-38/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:   3%|▎         | 9/271 [00:07<03:44,  1.17it/s]

🌐 GET votacoes/618609-107/orientacoes
⏱ Tempo: 0.57s | 📦 Registros: 0

Extract by ID:   4%|▎         | 10/271 [00:08<03:02,  1.43it/s]

🌐 GET votacoes/618609-80/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:   4%|▍         | 11/271 [00:08<02:34,  1.69it/s]

🌐 GET votacoes/618609-65/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:   4%|▍         | 12/271 [00:08<02:15,  1.91it/s]

🌐 GET votacoes/618609-40/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:   5%|▍         | 13/271 [00:09<02:05,  2.06it/s]

🌐 GET votacoes/1197773-157/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:   5%|▌         | 14/271 [00:09<02:03,  2.08it/s]

🌐 GET votacoes/1197773-156/orientacoes
⏱ Tempo: 0.47s | 📦 Registros: 0

Extract by ID:   6%|▌         | 15/271 [00:10<01:53,  2.26it/s]

🌐 GET votacoes/1197773-154/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:   6%|▌         | 16/271 [00:10<01:46,  2.39it/s]

🌐 GET votacoes/1197773-150/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:   6%|▋         | 17/271 [00:11<02:56,  1.44it/s]

🌐 GET votacoes/1197773-140/orientacoes
⏱ Tempo: 1.33s | 📦 Registros: 11

Extract by ID:   7%|▋         | 18/271 [00:12<02:35,  1.62it/s]

🌐 GET votacoes/1197773-104/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:   7%|▋         | 19/271 [00:13<02:59,  1.41it/s]

🌐 GET votacoes/1197773-99/orientacoes
⏱ Tempo: 0.93s | 📦 Registros: 10

Extract by ID:   7%|▋         | 20/271 [00:13<02:33,  1.63it/s]

🌐 GET votacoes/1197773-95/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:   8%|▊         | 21/271 [00:15<04:40,  1.12s/it]

🌐 GET votacoes/1197773-90/orientacoes
⏱ Tempo: 2.30s | 📦 Registros: 10

Extract by ID:   8%|▊         | 22/271 [00:16<03:43,  1.11it/s]

🌐 GET votacoes/1197773-87/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:   8%|▊         | 23/271 [00:16<03:04,  1.34it/s]

🌐 GET votacoes/1197773-81/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:   9%|▉         | 24/271 [00:16<02:36,  1.58it/s]

🌐 GET votacoes/1197773-76/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:   9%|▉         | 25/271 [00:17<02:56,  1.39it/s]

🌐 GET votacoes/2375501-8/orientacoes
⏱ Tempo: 0.91s | 📦 Registros: 10

Extract by ID:  10%|▉         | 26/271 [00:18<02:41,  1.52it/s]

🌐 GET votacoes/1198010-165/orientacoes
⏱ Tempo: 0.51s | 📦 Registros: 0

Extract by ID:  10%|▉         | 27/271 [00:18<02:19,  1.75it/s]

🌐 GET votacoes/1198010-163/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  10%|█         | 28/271 [00:19<02:08,  1.89it/s]

🌐 GET votacoes/1198010-154/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  11%|█         | 29/271 [00:19<02:02,  1.97it/s]

🌐 GET votacoes/1198010-144/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  11%|█         | 30/271 [00:20<01:54,  2.11it/s]

🌐 GET votacoes/1198010-140/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  11%|█▏        | 31/271 [00:20<01:49,  2.19it/s]

🌐 GET votacoes/1198010-130/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  12%|█▏        | 32/271 [00:20<01:47,  2.22it/s]

🌐 GET votacoes/1198010-117/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  12%|█▏        | 33/271 [00:21<02:01,  1.96it/s]

🌐 GET votacoes/1198010-99/orientacoes
⏱ Tempo: 0.64s | 📦 Registros: 0

Extract by ID:  13%|█▎        | 34/271 [00:22<01:56,  2.03it/s]

🌐 GET votacoes/1198010-76/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  13%|█▎        | 35/271 [00:22<02:09,  1.82it/s]

🌐 GET votacoes/1198010-61/orientacoes
⏱ Tempo: 0.68s | 📦 Registros: 0

Extract by ID:  13%|█▎        | 36/271 [00:23<02:17,  1.71it/s]

🌐 GET votacoes/1198010-49/orientacoes
⏱ Tempo: 0.66s | 📦 Registros: 0

Extract by ID:  14%|█▎        | 37/271 [00:24<02:20,  1.66it/s]

🌐 GET votacoes/1198010-33/orientacoes
⏱ Tempo: 0.64s | 📦 Registros: 0

Extract by ID:  14%|█▍        | 38/271 [00:24<02:04,  1.87it/s]

🌐 GET votacoes/2074843-165/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  14%|█▍        | 39/271 [00:24<02:09,  1.79it/s]

🌐 GET votacoes/2074843-163/orientacoes
⏱ Tempo: 0.60s | 📦 Registros: 0

Extract by ID:  15%|█▍        | 40/271 [00:26<03:06,  1.24it/s]

🌐 GET votacoes/2074843-113/orientacoes
⏱ Tempo: 1.39s | 📦 Registros: 0

Extract by ID:  15%|█▌        | 41/271 [00:26<02:34,  1.49it/s]

🌐 GET votacoes/2074843-110/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  15%|█▌        | 42/271 [00:27<02:19,  1.64it/s]

🌐 GET votacoes/2074843-97/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  16%|█▌        | 43/271 [00:27<02:12,  1.72it/s]

🌐 GET votacoes/2379387-8/orientacoes
⏱ Tempo: 0.51s | 📦 Registros: 0

Extract by ID:  16%|█▌        | 44/271 [00:28<01:56,  1.94it/s]

🌐 GET votacoes/2074843-85/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  17%|█▋        | 45/271 [00:29<02:44,  1.37it/s]

🌐 GET votacoes/2115253-183/orientacoes
⏱ Tempo: 1.22s | 📦 Registros: 10

Extract by ID:  17%|█▋        | 46/271 [00:30<02:59,  1.25it/s]

🌐 GET votacoes/2115253-179/orientacoes
⏱ Tempo: 0.95s | 📦 Registros: 10

Extract by ID:  17%|█▋        | 47/271 [00:32<04:08,  1.11s/it]

🌐 GET votacoes/2115253-175/orientacoes
⏱ Tempo: 1.83s | 📦 Registros: 10

Extract by ID:  18%|█▊        | 48/271 [00:34<05:36,  1.51s/it]

🌐 GET votacoes/2115253-172/orientacoes
⏱ Tempo: 2.42s | 📦 Registros: 10

Extract by ID:  18%|█▊        | 49/271 [00:35<05:11,  1.40s/it]

🌐 GET votacoes/2115253-167/orientacoes
⏱ Tempo: 1.15s | 📦 Registros: 10

Extract by ID:  18%|█▊        | 50/271 [00:36<04:52,  1.32s/it]

🌐 GET votacoes/2115253-156/orientacoes
⏱ Tempo: 1.13s | 📦 Registros: 10

Extract by ID:  19%|█▉        | 51/271 [00:37<03:50,  1.05s/it]

🌐 GET votacoes/2115253-123/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  19%|█▉        | 52/271 [00:37<03:09,  1.15it/s]

🌐 GET votacoes/2115253-121/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  20%|█▉        | 53/271 [00:42<06:58,  1.92s/it]

🌐 GET votacoes/2115253-118/orientacoes
⏱ Tempo: 4.37s | 📦 Registros: 10

Extract by ID:  20%|█▉        | 54/271 [00:43<06:39,  1.84s/it]

🌐 GET votacoes/2115253-116/orientacoes
⏱ Tempo: 1.65s | 📦 Registros: 10

Extract by ID:  20%|██        | 55/271 [00:45<06:11,  1.72s/it]

🌐 GET votacoes/2115253-111/orientacoes
⏱ Tempo: 1.43s | 📦 Registros: 10

Extract by ID:  21%|██        | 56/271 [00:46<05:22,  1.50s/it]

🌐 GET votacoes/2115253-104/orientacoes
⏱ Tempo: 0.98s | 📦 Registros: 10

Extract by ID:  21%|██        | 57/271 [00:46<04:11,  1.17s/it]

🌐 GET votacoes/2115253-93/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  21%|██▏       | 58/271 [00:47<04:14,  1.19s/it]

🌐 GET votacoes/2359287-7/orientacoes
⏱ Tempo: 1.23s | 📦 Registros: 10

Extract by ID:  22%|██▏       | 59/271 [00:48<03:21,  1.05it/s]

🌐 GET votacoes/2115253-86/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  22%|██▏       | 60/271 [00:48<02:45,  1.27it/s]

🌐 GET votacoes/2115253-67/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  23%|██▎       | 61/271 [00:48<02:18,  1.51it/s]

🌐 GET votacoes/2115253-32/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  23%|██▎       | 62/271 [00:49<02:05,  1.66it/s]

🌐 GET votacoes/2345493-64/orientacoes
⏱ Tempo: 0.46s | 📦 Registros: 0

Extract by ID:  23%|██▎       | 63/271 [00:49<01:51,  1.86it/s]

🌐 GET votacoes/2345493-62/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  24%|██▎       | 64/271 [00:50<01:46,  1.94it/s]

🌐 GET votacoes/2345493-52/orientacoes
⏱ Tempo: 0.46s | 📦 Registros: 0

Extract by ID:  24%|██▍       | 65/271 [00:51<02:37,  1.31it/s]

🌐 GET votacoes/2345493-50/orientacoes
⏱ Tempo: 1.34s | 📦 Registros: 10

Extract by ID:  24%|██▍       | 66/271 [00:52<03:01,  1.13it/s]

🌐 GET votacoes/2345493-47/orientacoes
⏱ Tempo: 1.17s | 📦 Registros: 10

Extract by ID:  25%|██▍       | 67/271 [00:54<03:46,  1.11s/it]

🌐 GET votacoes/2345493-44/orientacoes
⏱ Tempo: 1.63s | 📦 Registros: 10

Extract by ID:  25%|██▌       | 68/271 [00:55<03:36,  1.07s/it]

🌐 GET votacoes/2345493-41/orientacoes
⏱ Tempo: 0.96s | 📦 Registros: 10

Extract by ID:  25%|██▌       | 69/271 [00:56<03:10,  1.06it/s]

🌐 GET votacoes/2345493-39/orientacoes
⏱ Tempo: 0.65s | 📦 Registros: 0

Extract by ID:  26%|██▌       | 70/271 [00:57<03:17,  1.02it/s]

🌐 GET votacoes/2345493-38/orientacoes
⏱ Tempo: 1.06s | 📦 Registros: 10

Extract by ID:  26%|██▌       | 71/271 [00:58<03:16,  1.02it/s]

🌐 GET votacoes/2345493-35/orientacoes
⏱ Tempo: 0.98s | 📦 Registros: 10

Extract by ID:  27%|██▋       | 72/271 [00:59<03:21,  1.01s/it]

🌐 GET votacoes/2345493-31/orientacoes
⏱ Tempo: 1.07s | 📦 Registros: 10

Extract by ID:  27%|██▋       | 73/271 [00:59<03:04,  1.07it/s]

🌐 GET votacoes/2345493-9/orientacoes
⏱ Tempo: 0.74s | 📦 Registros: 0

Extract by ID:  27%|██▋       | 74/271 [01:00<02:32,  1.29it/s]

🌐 GET votacoes/2353475-2/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  28%|██▊       | 75/271 [01:00<02:07,  1.54it/s]

🌐 GET votacoes/2345498-69/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  28%|██▊       | 76/271 [01:01<02:12,  1.47it/s]

🌐 GET votacoes/2345498-54/orientacoes
⏱ Tempo: 0.76s | 📦 Registros: 0

Extract by ID:  28%|██▊       | 77/271 [01:01<01:53,  1.71it/s]

🌐 GET votacoes/2345498-38/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  29%|██▉       | 78/271 [01:02<02:00,  1.61it/s]

🌐 GET votacoes/2345501-28/orientacoes
⏱ Tempo: 0.71s | 📦 Registros: 0

Extract by ID:  29%|██▉       | 79/271 [01:03<01:57,  1.64it/s]

🌐 GET votacoes/2345501-26/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  30%|██▉       | 80/271 [01:03<02:03,  1.55it/s]

🌐 GET votacoes/2345501-25/orientacoes
⏱ Tempo: 0.72s | 📦 Registros: 0

Extract by ID:  30%|██▉       | 81/271 [01:04<01:58,  1.60it/s]

🌐 GET votacoes/2345501-18/orientacoes
⏱ Tempo: 0.57s | 📦 Registros: 0

Extract by ID:  30%|███       | 82/271 [01:05<02:00,  1.56it/s]

🌐 GET votacoes/2345501-17/orientacoes
⏱ Tempo: 0.67s | 📦 Registros: 0

Extract by ID:  31%|███       | 83/271 [01:05<01:46,  1.76it/s]

🌐 GET votacoes/2345502-6/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  31%|███       | 84/271 [01:05<01:38,  1.91it/s]

🌐 GET votacoes/253500-398/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  31%|███▏      | 85/271 [01:06<01:38,  1.89it/s]

🌐 GET votacoes/253500-396/orientacoes
⏱ Tempo: 0.53s | 📦 Registros: 0

Extract by ID:  32%|███▏      | 86/271 [01:07<01:45,  1.75it/s]

🌐 GET votacoes/253500-384/orientacoes
⏱ Tempo: 0.67s | 📦 Registros: 0

Extract by ID:  32%|███▏      | 87/271 [01:07<01:52,  1.64it/s]

🌐 GET votacoes/253500-383/orientacoes
⏱ Tempo: 0.69s | 📦 Registros: 0

Extract by ID:  32%|███▏      | 88/271 [01:08<02:22,  1.28it/s]

🌐 GET votacoes/253500-382/orientacoes
⏱ Tempo: 1.17s | 📦 Registros: 0

Extract by ID:  33%|███▎      | 89/271 [01:10<02:47,  1.09it/s]

🌐 GET votacoes/253500-381/orientacoes
⏱ Tempo: 1.25s | 📦 Registros: 0

Extract by ID:  33%|███▎      | 90/271 [01:10<02:34,  1.17it/s]

🌐 GET votacoes/253500-380/orientacoes
⏱ Tempo: 0.69s | 📦 Registros: 0

Extract by ID:  34%|███▎      | 91/271 [01:12<02:49,  1.06it/s]

🌐 GET votacoes/2451405-8/orientacoes
⏱ Tempo: 1.14s | 📦 Registros: 11

Extract by ID:  34%|███▍      | 92/271 [01:12<02:21,  1.27it/s]

🌐 GET votacoes/253500-356/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  34%|███▍      | 93/271 [01:12<02:01,  1.46it/s]

🌐 GET votacoes/253500-339/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  35%|███▍      | 94/271 [01:16<04:19,  1.47s/it]

🌐 GET votacoes/2079335-2/orientacoes
⏱ Tempo: 3.28s | 📦 Registros: 0

Extract by ID:  35%|███▌      | 95/271 [01:16<03:33,  1.22s/it]

🌐 GET votacoes/2079333-2/orientacoes
⏱ Tempo: 0.62s | 📦 Registros: 0

Extract by ID:  35%|███▌      | 96/271 [01:17<03:03,  1.05s/it]

🌐 GET votacoes/2079331-2/orientacoes
⏱ Tempo: 0.65s | 📦 Registros: 0

Extract by ID:  36%|███▌      | 97/271 [01:17<02:31,  1.15it/s]

🌐 GET votacoes/253500-331/orientacoes
⏱ Tempo: 0.44s | 📦 Registros: 0

Extract by ID:  36%|███▌      | 98/271 [01:18<02:09,  1.33it/s]

🌐 GET votacoes/253500-330/orientacoes
⏱ Tempo: 0.47s | 📦 Registros: 0

Extract by ID:  37%|███▋      | 99/271 [01:18<01:51,  1.55it/s]

🌐 GET votacoes/253500-329/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  37%|███▋      | 100/271 [01:19<01:39,  1.72it/s]

🌐 GET votacoes/559154-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  37%|███▋      | 101/271 [01:19<01:31,  1.86it/s]

🌐 GET votacoes/559153-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  38%|███▊      | 102/271 [01:20<01:26,  1.95it/s]

🌐 GET votacoes/559152-2/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  38%|███▊      | 103/271 [01:20<01:28,  1.90it/s]

🌐 GET votacoes/559151-2/orientacoes
⏱ Tempo: 0.56s | 📦 Registros: 0

Extract by ID:  38%|███▊      | 104/271 [01:21<01:36,  1.72it/s]

🌐 GET votacoes/559150-2/orientacoes
⏱ Tempo: 0.70s | 📦 Registros: 0

Extract by ID:  39%|███▊      | 105/271 [01:21<01:31,  1.81it/s]

🌐 GET votacoes/559149-2/orientacoes
⏱ Tempo: 0.48s | 📦 Registros: 0

Extract by ID:  39%|███▉      | 106/271 [01:22<01:31,  1.80it/s]

🌐 GET votacoes/559148-2/orientacoes
⏱ Tempo: 0.55s | 📦 Registros: 0

Extract by ID:  39%|███▉      | 107/271 [01:22<01:21,  2.01it/s]

🌐 GET votacoes/559147-2/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  40%|███▉      | 108/271 [01:23<01:27,  1.86it/s]

🌐 GET votacoes/557268-2/orientacoes
⏱ Tempo: 0.62s | 📦 Registros: 0

Extract by ID:  40%|████      | 109/271 [01:24<01:35,  1.70it/s]

🌐 GET votacoes/556546-2/orientacoes
⏱ Tempo: 0.70s | 📦 Registros: 0

Extract by ID:  41%|████      | 110/271 [01:24<01:33,  1.72it/s]

🌐 GET votacoes/553525-2/orientacoes
⏱ Tempo: 0.56s | 📦 Registros: 0

Extract by ID:  41%|████      | 111/271 [01:25<01:24,  1.89it/s]

🌐 GET votacoes/553479-2/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  41%|████▏     | 112/271 [01:25<01:18,  2.03it/s]

🌐 GET votacoes/553467-2/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  42%|████▏     | 113/271 [01:26<01:21,  1.94it/s]

🌐 GET votacoes/553466-2/orientacoes
⏱ Tempo: 0.57s | 📦 Registros: 0

Extract by ID:  42%|████▏     | 114/271 [01:26<01:14,  2.12it/s]

🌐 GET votacoes/553465-2/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  42%|████▏     | 115/271 [01:26<01:09,  2.24it/s]

🌐 GET votacoes/553464-2/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  43%|████▎     | 116/271 [01:27<01:04,  2.39it/s]

🌐 GET votacoes/553461-2/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:  43%|████▎     | 117/271 [01:27<01:06,  2.33it/s]

🌐 GET votacoes/553423-2/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  44%|████▎     | 118/271 [01:28<01:12,  2.12it/s]

🌐 GET votacoes/553422-2/orientacoes
⏱ Tempo: 0.56s | 📦 Registros: 0

Extract by ID:  44%|████▍     | 119/271 [01:28<01:08,  2.21it/s]

🌐 GET votacoes/553421-2/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  44%|████▍     | 120/271 [01:29<01:07,  2.25it/s]

🌐 GET votacoes/553420-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  45%|████▍     | 121/271 [01:29<01:14,  2.01it/s]

🌐 GET votacoes/553384-2/orientacoes
⏱ Tempo: 0.61s | 📦 Registros: 0

Extract by ID:  45%|████▌     | 122/271 [01:30<01:10,  2.11it/s]

🌐 GET votacoes/553357-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  45%|████▌     | 123/271 [01:30<01:08,  2.16it/s]

🌐 GET votacoes/553289-2/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  46%|████▌     | 124/271 [01:31<01:08,  2.16it/s]

🌐 GET votacoes/553288-2/orientacoes
⏱ Tempo: 0.46s | 📦 Registros: 0

Extract by ID:  46%|████▌     | 125/271 [01:31<01:09,  2.12it/s]

🌐 GET votacoes/553287-2/orientacoes
⏱ Tempo: 0.49s | 📦 Registros: 0

Extract by ID:  46%|████▋     | 126/271 [01:32<01:19,  1.82it/s]

🌐 GET votacoes/553286-2/orientacoes
⏱ Tempo: 0.73s | 📦 Registros: 0

Extract by ID:  47%|████▋     | 127/271 [01:32<01:12,  1.99it/s]

🌐 GET votacoes/553272-2/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  47%|████▋     | 128/271 [01:33<01:19,  1.80it/s]

🌐 GET votacoes/553269-2/orientacoes
⏱ Tempo: 0.68s | 📦 Registros: 0

Extract by ID:  48%|████▊     | 129/271 [01:33<01:20,  1.77it/s]

🌐 GET votacoes/553266-2/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  48%|████▊     | 130/271 [01:34<01:25,  1.66it/s]

🌐 GET votacoes/553262-2/orientacoes
⏱ Tempo: 0.69s | 📦 Registros: 0

Extract by ID:  48%|████▊     | 131/271 [01:35<01:16,  1.83it/s]

🌐 GET votacoes/553261-2/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  49%|████▊     | 132/271 [01:35<01:12,  1.92it/s]

🌐 GET votacoes/553260-2/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  49%|████▉     | 133/271 [01:36<01:20,  1.72it/s]

🌐 GET votacoes/553259-2/orientacoes
⏱ Tempo: 0.71s | 📦 Registros: 0

Extract by ID:  49%|████▉     | 134/271 [01:36<01:19,  1.72it/s]

🌐 GET votacoes/553258-2/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  50%|████▉     | 135/271 [01:37<01:30,  1.51it/s]

🌐 GET votacoes/553257-2/orientacoes
⏱ Tempo: 0.85s | 📦 Registros: 0

Extract by ID:  50%|█████     | 136/271 [01:38<01:20,  1.67it/s]

🌐 GET votacoes/553256-2/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  51%|█████     | 137/271 [01:38<01:21,  1.65it/s]

🌐 GET votacoes/553255-2/orientacoes
⏱ Tempo: 0.62s | 📦 Registros: 0

Extract by ID:  51%|█████     | 138/271 [01:39<01:27,  1.52it/s]

🌐 GET votacoes/553253-2/orientacoes
⏱ Tempo: 0.77s | 📦 Registros: 0

Extract by ID:  51%|█████▏    | 139/271 [01:40<01:24,  1.56it/s]

🌐 GET votacoes/553251-2/orientacoes
⏱ Tempo: 0.60s | 📦 Registros: 0

Extract by ID:  52%|█████▏    | 140/271 [01:40<01:20,  1.63it/s]

🌐 GET votacoes/553250-2/orientacoes
⏱ Tempo: 0.54s | 📦 Registros: 0

Extract by ID:  52%|█████▏    | 141/271 [01:41<01:28,  1.47it/s]

🌐 GET votacoes/553248-2/orientacoes
⏱ Tempo: 0.83s | 📦 Registros: 0

Extract by ID:  52%|█████▏    | 142/271 [01:42<01:31,  1.42it/s]

🌐 GET votacoes/553246-2/orientacoes
⏱ Tempo: 0.76s | 📦 Registros: 0

Extract by ID:  53%|█████▎    | 143/271 [01:42<01:29,  1.42it/s]

🌐 GET votacoes/553245-2/orientacoes
⏱ Tempo: 0.69s | 📦 Registros: 0

Extract by ID:  53%|█████▎    | 144/271 [01:43<01:23,  1.52it/s]

🌐 GET votacoes/553244-2/orientacoes
⏱ Tempo: 0.55s | 📦 Registros: 0

Extract by ID:  54%|█████▎    | 145/271 [01:43<01:15,  1.68it/s]

🌐 GET votacoes/553243-2/orientacoes
⏱ Tempo: 0.44s | 📦 Registros: 0

Extract by ID:  54%|█████▍    | 146/271 [01:44<01:05,  1.91it/s]

🌐 GET votacoes/553242-2/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  54%|█████▍    | 147/271 [01:44<01:09,  1.79it/s]

🌐 GET votacoes/553241-2/orientacoes
⏱ Tempo: 0.63s | 📦 Registros: 0

Extract by ID:  55%|█████▍    | 148/271 [01:45<01:15,  1.64it/s]

🌐 GET votacoes/253500-223/orientacoes
⏱ Tempo: 0.73s | 📦 Registros: 0

Extract by ID:  55%|█████▍    | 149/271 [01:46<01:06,  1.85it/s]

🌐 GET votacoes/472189-3/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  55%|█████▌    | 150/271 [01:46<01:00,  1.99it/s]

🌐 GET votacoes/472187-3/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  56%|█████▌    | 151/271 [01:46<00:56,  2.14it/s]

🌐 GET votacoes/471727-4/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  56%|█████▌    | 152/271 [01:47<00:54,  2.19it/s]

🌐 GET votacoes/253500-142/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  56%|█████▋    | 153/271 [01:48<01:10,  1.67it/s]

🌐 GET votacoes/253500-141/orientacoes
⏱ Tempo: 0.93s | 📦 Registros: 0

Extract by ID:  57%|█████▋    | 154/271 [01:51<02:47,  1.43s/it]

🌐 GET votacoes/253500-140/orientacoes
⏱ Tempo: 3.38s | 📦 Registros: 0

Extract by ID:  57%|█████▋    | 155/271 [01:51<02:08,  1.11s/it]

🌐 GET votacoes/467027-2/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:  58%|█████▊    | 156/271 [01:52<01:55,  1.01s/it]

🌐 GET votacoes/467025-2/orientacoes
⏱ Tempo: 0.77s | 📦 Registros: 0

Extract by ID:  58%|█████▊    | 157/271 [01:53<01:33,  1.23it/s]

🌐 GET votacoes/467023-2/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  58%|█████▊    | 158/271 [01:53<01:24,  1.33it/s]

🌐 GET votacoes/467022-2/orientacoes
⏱ Tempo: 0.59s | 📦 Registros: 0

Extract by ID:  59%|█████▊    | 159/271 [01:54<01:11,  1.56it/s]

🌐 GET votacoes/467020-2/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  59%|█████▉    | 160/271 [01:54<01:08,  1.63it/s]

🌐 GET votacoes/466193-2/orientacoes
⏱ Tempo: 0.55s | 📦 Registros: 0

Extract by ID:  59%|█████▉    | 161/271 [01:55<01:19,  1.39it/s]

🌐 GET votacoes/462366-2/orientacoes
⏱ Tempo: 0.96s | 📦 Registros: 0

Extract by ID:  60%|█████▉    | 162/271 [01:55<01:06,  1.63it/s]

🌐 GET votacoes/462253-2/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  60%|██████    | 163/271 [01:56<01:04,  1.68it/s]

🌐 GET votacoes/461790-2/orientacoes
⏱ Tempo: 0.54s | 📦 Registros: 0

Extract by ID:  61%|██████    | 164/271 [01:56<00:55,  1.93it/s]

🌐 GET votacoes/461789-2/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:  61%|██████    | 165/271 [01:57<00:52,  2.02it/s]

🌐 GET votacoes/461475-2/orientacoes
⏱ Tempo: 0.44s | 📦 Registros: 0

Extract by ID:  61%|██████▏   | 166/271 [01:57<00:48,  2.16it/s]

🌐 GET votacoes/461465-2/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  62%|██████▏   | 167/271 [01:58<00:44,  2.34it/s]

🌐 GET votacoes/461402-2/orientacoes
⏱ Tempo: 0.34s | 📦 Registros: 0

Extract by ID:  62%|██████▏   | 168/271 [01:58<00:56,  1.84it/s]

🌐 GET votacoes/461373-2/orientacoes
⏱ Tempo: 0.82s | 📦 Registros: 0

Extract by ID:  62%|██████▏   | 169/271 [01:59<00:58,  1.73it/s]

🌐 GET votacoes/461366-2/orientacoes
⏱ Tempo: 0.65s | 📦 Registros: 0

Extract by ID:  63%|██████▎   | 170/271 [01:59<00:53,  1.88it/s]

🌐 GET votacoes/461356-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  63%|██████▎   | 171/271 [02:00<00:51,  1.94it/s]

🌐 GET votacoes/461261-2/orientacoes
⏱ Tempo: 0.47s | 📦 Registros: 0

Extract by ID:  63%|██████▎   | 172/271 [02:01<00:56,  1.74it/s]

🌐 GET votacoes/461220-2/orientacoes
⏱ Tempo: 0.71s | 📦 Registros: 0

Extract by ID:  64%|██████▍   | 173/271 [02:01<00:54,  1.79it/s]

🌐 GET votacoes/461218-2/orientacoes
⏱ Tempo: 0.51s | 📦 Registros: 0

Extract by ID:  64%|██████▍   | 174/271 [02:01<00:49,  1.98it/s]

🌐 GET votacoes/461217-2/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  65%|██████▍   | 175/271 [02:02<00:45,  2.11it/s]

🌐 GET votacoes/461215-2/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  65%|██████▍   | 176/271 [02:02<00:48,  1.97it/s]

🌐 GET votacoes/461214-2/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  65%|██████▌   | 177/271 [02:03<00:49,  1.91it/s]

🌐 GET votacoes/460925-2/orientacoes
⏱ Tempo: 0.55s | 📦 Registros: 0

Extract by ID:  66%|██████▌   | 178/271 [02:03<00:44,  2.09it/s]

🌐 GET votacoes/460923-2/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  66%|██████▌   | 179/271 [02:04<00:42,  2.17it/s]

🌐 GET votacoes/460922-2/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  66%|██████▋   | 180/271 [02:04<00:39,  2.29it/s]

🌐 GET votacoes/459944-2/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  67%|██████▋   | 181/271 [02:05<00:39,  2.26it/s]

🌐 GET votacoes/459943-2/orientacoes
⏱ Tempo: 0.45s | 📦 Registros: 0

Extract by ID:  67%|██████▋   | 182/271 [02:05<00:39,  2.28it/s]

🌐 GET votacoes/459942-2/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  68%|██████▊   | 183/271 [02:06<00:37,  2.34it/s]

🌐 GET votacoes/459941-2/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  68%|██████▊   | 184/271 [02:06<00:41,  2.11it/s]

🌐 GET votacoes/459940-2/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  68%|██████▊   | 185/271 [02:07<00:50,  1.71it/s]

🌐 GET votacoes/253500-62/orientacoes
⏱ Tempo: 0.84s | 📦 Registros: 0

Extract by ID:  69%|██████▊   | 186/271 [02:07<00:43,  1.94it/s]

🌐 GET votacoes/267849-2/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  69%|██████▉   | 187/271 [02:08<00:54,  1.54it/s]

🌐 GET votacoes/510035-126/orientacoes
⏱ Tempo: 0.96s | 📦 Registros: 0

Extract by ID:  69%|██████▉   | 188/271 [02:09<00:47,  1.75it/s]

🌐 GET votacoes/510035-116/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  70%|██████▉   | 189/271 [02:09<00:41,  1.97it/s]

🌐 GET votacoes/510035-92/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  70%|███████   | 190/271 [02:09<00:38,  2.13it/s]

🌐 GET votacoes/510035-77/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  70%|███████   | 191/271 [02:10<00:35,  2.26it/s]

🌐 GET votacoes/510035-61/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  71%|███████   | 192/271 [02:10<00:33,  2.36it/s]

🌐 GET votacoes/510035-46/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  71%|███████   | 193/271 [02:11<00:33,  2.35it/s]

🌐 GET votacoes/1548579-198/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  72%|███████▏  | 194/271 [02:11<00:37,  2.06it/s]

🌐 GET votacoes/1548579-196/orientacoes
⏱ Tempo: 0.62s | 📦 Registros: 0

Extract by ID:  72%|███████▏  | 195/271 [02:12<00:54,  1.40it/s]

🌐 GET votacoes/1548579-194/orientacoes
⏱ Tempo: 1.24s | 📦 Registros: 11

Extract by ID:  72%|███████▏  | 196/271 [02:17<02:15,  1.80s/it]

🌐 GET votacoes/1548579-186/orientacoes
⏱ Tempo: 4.33s | 📦 Registros: 11

Extract by ID:  73%|███████▎  | 197/271 [02:17<01:41,  1.38s/it]

🌐 GET votacoes/1548579-170/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  73%|███████▎  | 198/271 [02:18<01:19,  1.08s/it]

🌐 GET votacoes/1548579-169/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  73%|███████▎  | 199/271 [02:18<01:03,  1.13it/s]

🌐 GET votacoes/1548579-168/orientacoes
⏱ Tempo: 0.41s | 📦 Registros: 0

Extract by ID:  74%|███████▍  | 200/271 [02:19<00:59,  1.20it/s]

🌐 GET votacoes/1548579-167/orientacoes
⏱ Tempo: 0.71s | 📦 Registros: 0

Extract by ID:  74%|███████▍  | 201/271 [02:19<00:48,  1.44it/s]

🌐 GET votacoes/1548579-166/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  75%|███████▍  | 202/271 [02:20<00:43,  1.57it/s]

🌐 GET votacoes/1548579-165/orientacoes
⏱ Tempo: 0.50s | 📦 Registros: 0

Extract by ID:  75%|███████▍  | 203/271 [02:20<00:48,  1.41it/s]

🌐 GET votacoes/1548579-164/orientacoes
⏱ Tempo: 0.88s | 📦 Registros: 0

Extract by ID:  75%|███████▌  | 204/271 [02:22<00:56,  1.19it/s]

🌐 GET votacoes/1548579-163/orientacoes
⏱ Tempo: 1.14s | 📦 Registros: 0

Extract by ID:  76%|███████▌  | 205/271 [02:22<00:46,  1.42it/s]

🌐 GET votacoes/1548579-162/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  76%|███████▌  | 206/271 [02:22<00:39,  1.64it/s]

🌐 GET votacoes/1548579-161/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  76%|███████▋  | 207/271 [02:23<00:38,  1.64it/s]

🌐 GET votacoes/1548579-160/orientacoes
⏱ Tempo: 0.60s | 📦 Registros: 0

Extract by ID:  77%|███████▋  | 208/271 [02:26<01:29,  1.42s/it]

🌐 GET votacoes/1548579-159/orientacoes
⏱ Tempo: 3.30s | 📦 Registros: 0

Extract by ID:  77%|███████▋  | 209/271 [02:27<01:09,  1.12s/it]

🌐 GET votacoes/1548579-146/orientacoes
⏱ Tempo: 0.42s | 📦 Registros: 0

Extract by ID:  77%|███████▋  | 210/271 [02:28<01:09,  1.13s/it]

🌐 GET votacoes/1548579-144/orientacoes
⏱ Tempo: 1.15s | 📦 Registros: 10

Extract by ID:  78%|███████▊  | 211/271 [02:29<01:04,  1.08s/it]

🌐 GET votacoes/1548579-126/orientacoes
⏱ Tempo: 0.96s | 📦 Registros: 10

Extract by ID:  78%|███████▊  | 212/271 [02:30<01:03,  1.07s/it]

🌐 GET votacoes/1548579-122/orientacoes
⏱ Tempo: 1.03s | 📦 Registros: 10

Extract by ID:  79%|███████▊  | 213/271 [02:31<01:07,  1.17s/it]

🌐 GET votacoes/1548579-114/orientacoes
⏱ Tempo: 1.39s | 📦 Registros: 10

Extract by ID:  79%|███████▉  | 214/271 [02:32<01:03,  1.11s/it]

🌐 GET votacoes/1548579-109/orientacoes
⏱ Tempo: 0.98s | 📦 Registros: 10

Extract by ID:  79%|███████▉  | 215/271 [02:33<00:53,  1.05it/s]

🌐 GET votacoes/1548579-101/orientacoes
⏱ Tempo: 0.57s | 📦 Registros: 0

Extract by ID:  80%|███████▉  | 216/271 [02:33<00:43,  1.25it/s]

🌐 GET votacoes/1548579-100/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  80%|████████  | 217/271 [02:34<00:35,  1.51it/s]

🌐 GET votacoes/1548579-99/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  80%|████████  | 218/271 [02:34<00:33,  1.59it/s]

🌐 GET votacoes/1548579-98/orientacoes
⏱ Tempo: 0.54s | 📦 Registros: 0

Extract by ID:  81%|████████  | 219/271 [02:35<00:28,  1.82it/s]

🌐 GET votacoes/1548579-97/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  81%|████████  | 220/271 [02:35<00:29,  1.74it/s]

🌐 GET votacoes/1548579-96/orientacoes
⏱ Tempo: 0.63s | 📦 Registros: 0

Extract by ID:  82%|████████▏ | 221/271 [02:36<00:25,  1.94it/s]

🌐 GET votacoes/1548579-95/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  82%|████████▏ | 222/271 [02:36<00:30,  1.62it/s]

🌐 GET votacoes/1548579-94/orientacoes
⏱ Tempo: 0.85s | 📦 Registros: 0

Extract by ID:  82%|████████▏ | 223/271 [02:37<00:29,  1.63it/s]

🌐 GET votacoes/1548579-93/orientacoes
⏱ Tempo: 0.60s | 📦 Registros: 0

Extract by ID:  83%|████████▎ | 224/271 [02:38<00:28,  1.66it/s]

🌐 GET votacoes/1548579-92/orientacoes
⏱ Tempo: 0.57s | 📦 Registros: 0

Extract by ID:  83%|████████▎ | 225/271 [02:38<00:28,  1.60it/s]

🌐 GET votacoes/1548579-91/orientacoes
⏱ Tempo: 0.67s | 📦 Registros: 0

Extract by ID:  83%|████████▎ | 226/271 [02:39<00:25,  1.77it/s]

🌐 GET votacoes/1548579-90/orientacoes
⏱ Tempo: 0.43s | 📦 Registros: 0

Extract by ID:  84%|████████▍ | 227/271 [02:39<00:22,  1.97it/s]

🌐 GET votacoes/1548579-89/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  84%|████████▍ | 228/271 [02:40<00:22,  1.94it/s]

🌐 GET votacoes/1548579-88/orientacoes
⏱ Tempo: 0.53s | 📦 Registros: 0

Extract by ID:  85%|████████▍ | 229/271 [02:40<00:23,  1.79it/s]

🌐 GET votacoes/1548579-87/orientacoes
⏱ Tempo: 0.65s | 📦 Registros: 0

Extract by ID:  85%|████████▍ | 230/271 [02:41<00:20,  1.96it/s]

🌐 GET votacoes/1548579-86/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  85%|████████▌ | 231/271 [02:41<00:24,  1.63it/s]

🌐 GET votacoes/1548579-85/orientacoes
⏱ Tempo: 0.85s | 📦 Registros: 0

Extract by ID:  86%|████████▌ | 232/271 [02:43<00:28,  1.35it/s]

🌐 GET votacoes/1548579-84/orientacoes
⏱ Tempo: 1.03s | 📦 Registros: 0

Extract by ID:  86%|████████▌ | 233/271 [02:43<00:23,  1.59it/s]

🌐 GET votacoes/2092056-118/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

Extract by ID:  86%|████████▋ | 234/271 [02:44<00:23,  1.57it/s]

🌐 GET votacoes/2092056-99/orientacoes
⏱ Tempo: 0.66s | 📦 Registros: 0

Extract by ID:  87%|████████▋ | 235/271 [02:44<00:23,  1.51it/s]

🌐 GET votacoes/2092056-98/orientacoes
⏱ Tempo: 0.72s | 📦 Registros: 0

Extract by ID:  87%|████████▋ | 236/271 [02:45<00:22,  1.59it/s]

🌐 GET votacoes/2092056-86/orientacoes
⏱ Tempo: 0.55s | 📦 Registros: 0

Extract by ID:  87%|████████▋ | 237/271 [02:45<00:19,  1.78it/s]

🌐 GET votacoes/2092056-83/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  88%|████████▊ | 238/271 [02:46<00:17,  1.94it/s]

🌐 GET votacoes/2092056-68/orientacoes
⏱ Tempo: 0.40s | 📦 Registros: 0

Extract by ID:  88%|████████▊ | 239/271 [02:46<00:15,  2.11it/s]

🌐 GET votacoes/2092056-67/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  89%|████████▊ | 240/271 [02:47<00:15,  1.96it/s]

🌐 GET votacoes/2416804-56/orientacoes
⏱ Tempo: 0.59s | 📦 Registros: 0

Extract by ID:  89%|████████▉ | 241/271 [02:48<00:20,  1.46it/s]

🌐 GET votacoes/2416804-54/orientacoes
⏱ Tempo: 1.08s | 📦 Registros: 11

Extract by ID:  89%|████████▉ | 242/271 [02:49<00:22,  1.30it/s]

🌐 GET votacoes/2416804-51/orientacoes
⏱ Tempo: 0.97s | 📦 Registros: 11

Extract by ID:  90%|████████▉ | 243/271 [02:50<00:24,  1.15it/s]

🌐 GET votacoes/2416804-48/orientacoes
⏱ Tempo: 1.09s | 📦 Registros: 11

Extract by ID:  90%|█████████ | 244/271 [02:51<00:28,  1.04s/it]

🌐 GET votacoes/2416804-43/orientacoes
⏱ Tempo: 1.44s | 📦 Registros: 11

Extract by ID:  90%|█████████ | 245/271 [02:52<00:25,  1.01it/s]

🌐 GET votacoes/2416804-31/orientacoes
⏱ Tempo: 0.88s | 📦 Registros: 0

Extract by ID:  91%|█████████ | 246/271 [02:52<00:20,  1.24it/s]

🌐 GET votacoes/2416826-60/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  91%|█████████ | 247/271 [02:53<00:19,  1.25it/s]

🌐 GET votacoes/2416826-59/orientacoes
⏱ Tempo: 0.77s | 📦 Registros: 0

Extract by ID:  92%|█████████▏| 248/271 [02:54<00:17,  1.32it/s]

🌐 GET votacoes/2416826-52/orientacoes
⏱ Tempo: 0.65s | 📦 Registros: 0

Extract by ID:  92%|█████████▏| 249/271 [02:57<00:35,  1.60s/it]

🌐 GET votacoes/2416826-49/orientacoes
⏱ Tempo: 3.57s | 📦 Registros: 11

Extract by ID:  92%|█████████▏| 250/271 [02:58<00:25,  1.24s/it]

🌐 GET votacoes/2481874-37/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  93%|█████████▎| 251/271 [03:01<00:37,  1.87s/it]

🌐 GET votacoes/2481874-35/orientacoes
⏱ Tempo: 3.34s | 📦 Registros: 0

Extract by ID:  93%|█████████▎| 252/271 [03:02<00:29,  1.58s/it]

🌐 GET votacoes/2481874-29/orientacoes
⏱ Tempo: 0.89s | 📦 Registros: 8

Extract by ID:  93%|█████████▎| 253/271 [03:03<00:24,  1.38s/it]

🌐 GET votacoes/2481874-16/orientacoes
⏱ Tempo: 0.90s | 📦 Registros: 0

Extract by ID:  94%|█████████▎| 254/271 [03:03<00:18,  1.08s/it]

🌐 GET votacoes/2481874-15/orientacoes
⏱ Tempo: 0.39s | 📦 Registros: 0

Extract by ID:  94%|█████████▍| 255/271 [03:04<00:13,  1.17it/s]

🌐 GET votacoes/2481874-14/orientacoes
⏱ Tempo: 0.33s | 📦 Registros: 0

Extract by ID:  94%|█████████▍| 256/271 [03:04<00:10,  1.40it/s]

🌐 GET votacoes/2481874-13/orientacoes
⏱ Tempo: 0.37s | 📦 Registros: 0

Extract by ID:  95%|█████████▍| 257/271 [03:05<00:10,  1.35it/s]

🌐 GET votacoes/2494647-7/orientacoes
⏱ Tempo: 0.79s | 📦 Registros: 8

Extract by ID:  95%|█████████▌| 258/271 [03:06<00:09,  1.44it/s]

🌐 GET votacoes/2481875-40/orientacoes
⏱ Tempo: 0.58s | 📦 Registros: 0

Extract by ID:  96%|█████████▌| 259/271 [03:06<00:09,  1.33it/s]

🌐 GET votacoes/2481875-38/orientacoes
⏱ Tempo: 0.88s | 📦 Registros: 8

Extract by ID:  96%|█████████▌| 260/271 [03:07<00:08,  1.28it/s]

🌐 GET votacoes/2481875-32/orientacoes
⏱ Tempo: 0.83s | 📦 Registros: 8

Extract by ID:  96%|█████████▋| 261/271 [03:08<00:06,  1.53it/s]

🌐 GET votacoes/2481875-17/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  97%|█████████▋| 262/271 [03:08<00:06,  1.47it/s]

🌐 GET votacoes/2481875-16/orientacoes
⏱ Tempo: 0.75s | 📦 Registros: 0

Extract by ID:  97%|█████████▋| 263/271 [03:09<00:05,  1.52it/s]

🌐 GET votacoes/2481875-15/orientacoes
⏱ Tempo: 0.60s | 📦 Registros: 0

Extract by ID:  97%|█████████▋| 264/271 [03:09<00:04,  1.74it/s]

🌐 GET votacoes/2481875-14/orientacoes
⏱ Tempo: 0.38s | 📦 Registros: 0

Extract by ID:  98%|█████████▊| 265/271 [03:10<00:04,  1.41it/s]

🌐 GET votacoes/2494658-8/orientacoes
⏱ Tempo: 1.02s | 📦 Registros: 8

Extract by ID:  98%|█████████▊| 266/271 [03:11<00:03,  1.66it/s]

🌐 GET votacoes/2481876-24/orientacoes
⏱ Tempo: 0.35s | 📦 Registros: 0

Extract by ID:  99%|█████████▊| 267/271 [03:11<00:02,  1.76it/s]

🌐 GET votacoes/2481882-23/orientacoes
⏱ Tempo: 0.48s | 📦 Registros: 0

Extract by ID:  99%|█████████▉| 268/271 [03:12<00:02,  1.29it/s]

🌐 GET votacoes/2481884-23/orientacoes
⏱ Tempo: 1.25s | 📦 Registros: 0

Extract by ID:  99%|█████████▉| 269/271 [03:13<00:01,  1.30it/s]

🌐 GET votacoes/2481886-23/orientacoes
⏱ Tempo: 0.75s | 📦 Registros: 0

Extract by ID: 100%|█████████▉| 270/271 [03:14<00:00,  1.49it/s]

🌐 GET votacoes/2481888-23/orientacoes
⏱ Tempo: 0.44s | 📦 Registros: 0

Extract by ID: 100%|██████████| 271/271 [03:14<00:00,  1.39it/s]

🌐 GET votacoes/2481890-23/orientacoes
⏱ Tempo: 0.36s | 📦 Registros: 0

In [55]:
loader.save_bronze(
    df=df_votacoesOrientacoes,
    dataset='votacoes_orientacao'
)

💾 Salvo em: data/bronze/votacoes_orientacao/votacoes_orientacao.parquet